### ISSUE TITLE
TaskItem does not support date with seconds and ms

### ISSUE THREAD

**Issue by gonella** [jsGanttImproved/jsgantt-improved#100]
Hi,

I'm trying the use the following code to add task item with seconds + ms, how it is not displaying correctly. Is it an issue or a limitation?

var g = new JSGantt.GanttChart(document.getElementById('embedded-Gantt'), 'hour');
g.setCaptionType('Complete');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)
g.setQuarterColWidth(36);
g.setDateTaskDisplayFormat('day dd month yyyy'); // Shown in tool tip box
**g.setDateInputFormat('yyyy-MM-dd HH:mm:ss.SSS');**
g.setDayMajorDateDisplayFormat('mon yyyy - Week ww') // Set format to display dates in the 'Major' header of the 'Day' view
g.setWeekMinorDateDisplayFormat('dd mon') // Set format to display dates in the 'Minor' header of the 'Week' view
g.setShowTaskInfoLink(1); // Show link in tool tip (0/1)
g.setShowEndWeekDate(0); // Show/Hide the date for the last day of the week in header for daily view (1/0)
g.setUseSingleCell(10000); // Set the threshold at which we will only use one cell per table row (0 disables).  Helps with rendering performance for large charts.
g.setFormatArr('Hour', 'Day', 'Week', 'Month', 'Quarter'); // Even with setUseSingleCell using Hour format on such a large chart can cause issues in some browsers

Add item like:

 g.AddTaskItem(new JSGantt.TaskItem(84225,   'Text',     '**2018-03-24 23:25:06.830**',           '2018-03-24 23:25:07.740',          'gtaskblue',  '',                 0, '',    0,     1,      69391,       1,     '',      '',      '', g ));

Thanks,
Adriano

**Comment by mariohmol** [comment]
Hi thanks for this!

I guess the first step is do a example on codepen so we can investigate, see this example

https://codepen.io/mariomol/pen/mQzBPV

**Comment by mariohmol** [comment]
Hi.. this is sooo unsual.. tasks withs seconds and ms? Well.. if u are still interested in that..reopen that we can investigate
