### ISSUE TITLE
Vertical scrollbar for longer charts?

### ISSUE THREAD

**Issue by sotomo** [jsGanttImproved/jsgantt-improved#101]
Is it possible to add a vertical scrollbar to a chart with lots of rows, so that the header will stay in view while scrolling down?

The other problem with longer charts is that the horizontal scrollbar is not on the page.

BTW, really appreciate the solution.  Better than Google's gantt chart!

**Comment by sotomo** [comment]
I found it easy to do this with CSS:

// Set height of chart after g.draw() to make sure it is not taller than the page
function setChartHeight() {
    var maxHeight = $(window).height() - 300; // browser height minus any 'white space'
    $(".gchartgrid").css("max-height", maxHeight + "px")
    $(".glistgrid").css("max-height", (maxHeight - 17) + "px") // assuming scrollbar is 17px high
}

Luckily the caption windows scrolls in sync with the chart!. Thanks!

**Comment by jontay81** [comment]
Did you experience the mouse-wheel scroll behavior being extremely slow when the chart has max-height set? It seems like the scroll speed is about 5% of its normal amount when I set max-height.

**Comment by jontay81** [comment]
Found a workaround [here](https://stackoverflow.com/questions/45154788/sluggish-scroll-behaviour-of-largeish-html-table-in-google-chrome?rq=1) to force gpu acceleration which makes it scroll quickly.

Add this line to sotomo's function to force gpu acceleration.

`$(".gchartgrid").css("transform","translate3d(0,0,0)")`

**Comment by mariohmol** [comment]
I guess this was fixed in new version, could u please check it there?
