### ISSUE TITLE
Does task pID parameter need to be numeric?

### ISSUE THREAD

**Issue by marksack** [jsGanttImproved/jsgantt-improved#103]
I have a project where the top-level parent tasks are created using a different process than their children and are stored in separate tables. Essentially, the parents are projects and the children are tasks within the projects. Both projects and tasks have unique numeric ids but it is possible for a project to have the same id as a task. Because jsgantt's numeric uniqueness requirement, I have to go through some hoops to load the projects and their tasks. If the pID parameter was left as a string instead of being converted to an int, the loading process would be much simpler. I could just add a prefix 'P' to the project ids and a prefix 'T' to the task ids to guarantee uniqueness.
I did a simple experiment by just removing the parseInt function as follow:

`	// var vID=parseInt(document.createTextNode(pID).data);
	var vID=document.createTextNode(pID).data;`

Then I loaded some tasks (parents and children) with the addTaskItem function and everything seemed to work fine. In the test, some of the pIDs were numeric and some were strings.
I admit that this was a very simple test. I did not try XML loading, dependencies, dynamically adding and removing tasks, etc.
Is there any reason why this change could not be made? It appears to be backwards compatible.

**Comment by mariohmol** [comment]
Check it out https://mariohmol.github.io/jsgantt-improved/docs/demo.html

**Comment by mariohmol** [comment]
fixed on 2.0.3
