### ISSUE TITLE
Year in format and quarter as per financial year are different

### ISSUE THREAD

**Issue by nighotatul** [jsGanttImproved/jsgantt-improved#104]
Year format is not their then how we add year format.

in quater format,every industry have different financial year then how we fix quarter format.

**Comment by mariohmol** [comment]
I almost sure that is impossible to make different quarters here... mixing months from different years? could u give an example?

**Comment by mariohmol** [comment]
Hi.. waiting for example, as soon as u report some data here we will investigate
thanks
