### ISSUE TITLE
when we use g.setUseSingleCell(1) then weekend gray color has been slip from their position.

### ISSUE THREAD

**Issue by nighotatul** [jsGanttImproved/jsgantt-improved#105]
i have attached screenshot for your demo.
![ganttchart](https://user-images.githubusercontent.com/37444019/42448349-86ec98c8-839a-11e8-8ae6-997177f1b998.PNG)

**Comment by mariohmol** [comment]
Can u double check with new version please? And it seems that UseSingleCell is not settled to 1, because is showing a lot of columns.. reopen if you still need this
