### ISSUE TITLE
Dependency arrow enhancements

### ISSUE THREAD

**Issue by sanj79** [jsGanttImproved/jsgantt-improved#107]
Hi,
Wonderful work on the Gantt Chart. Better than plenty of paid solutions available.
Having said that, can we add highlighting to the dependency arrows, like for example:

Whenever a taskbar is hovered over, all the links established with respect to that task (incoming and outgoing) should be highlighted so that it doesn't become a task for the user to check the links. Does the use-case sound fair ?

Also, sometimes common lines are used to join different arrows, even when the tasks they point to are not related, and in turn it becomes impossible to know which tasks land where.
Attaching a screenshot to make it easier to understand. Hope it can be corrected or a solution could be advised.

![jsganttimproved](https://user-images.githubusercontent.com/24490590/43391154-8a7502cc-940d-11e8-94ad-f75ab1301e85.PNG)

Lastly, more configuration options for css, like font-sizes, flexible width and height across the chart be it columns, rows, gantt chart container etc would be a nice addition.

Hope the suggestions get considered.

**Comment by mariohmol** [comment]
Please.. can u provide this data for testing?

**Comment by mariohmol** [comment]
Thanks for that.. on hover i make it stronger 
<img width="292" alt="captura de tela 2018-12-25 as 10 16 45 pm" src="https://user-images.githubusercontent.com/5495763/50427570-ddbe6280-0892-11e9-9fb6-4698ccc648c9.png">
