### ISSUE TITLE
Task displayed two weeks after tasks date

### ISSUE THREAD

**Issue by candicedalia** [jsGanttImproved/jsgantt-improved#109]
Hello,
the task at 2018-09-14 displays in the chart at the week 24/09 instead of 10/09.
Current date is 2018-09-13 by the way.
Thanks for your feed back.

![image sans titre](https://user-images.githubusercontent.com/31515753/45493791-d8b82600-b76f-11e8-89fe-71908858979b.png)

[jsgantt-improved.zip](https://github.com/jsGanttImproved/jsgantt-improved/files/2379640/jsgantt-improved.zip)

**Comment by caveman2st** [comment]
I'm watching that too.
![image](https://user-images.githubusercontent.com/8106747/46231426-276ae000-c36c-11e8-96c9-53718da1ebc5.png)

**Comment by samaya6529** [comment]
I encountered the same problem. Can anyone help?

**Comment by caveman2st** [comment]
yes, user the version of pull request 81: "Fix bar alignment #81"

**Comment by candicedalia** [comment]
Hi,
it works for me, thanks caveman2st.
