### ISSUE TITLE
Make column editable

### ISSUE THREAD

**Issue by dylanpnlearn** [jsGanttImproved/jsgantt-improved#110]
Thank you for your project. It is really useful for me. I just want to as that, is there any ways for me edit the columns directly? And also, I found some bugs when pulling the scrollbar to the rightmost end of the chart.

![default](https://user-images.githubusercontent.com/35573371/46337870-d7846580-c658-11e8-94fa-1916c9459ebb.PNG)

**Comment by dylanpnlearn** [comment]
I found the solution for chart scrollbar here #81 .
Also, for making cell editable, I did check here #61 . It enables event for clicking the cell, which really help if anyone wants to make the cell editable.

**Comment by eduardomourar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue test](https://trello.com/c/uXYk7eLZ/1-issue-test)

**Comment by mariohmol** [comment]
cool! #61 will be in next release
