### ISSUE TITLE
timeline not aligned correctly

### ISSUE THREAD

**Issue by samaya6529** [jsGanttImproved/jsgantt-improved#111]
To whom it is concerned,

I did not modify any part of the original code, however, the start date and end date of the time line bars did not appear to align correctly with the date legend. How come?

![image](https://user-images.githubusercontent.com/12404047/47293537-ffa22b80-d63c-11e8-97cc-c613c5859702.png)

**Comment by mariohmol** [comment]
I guess this was fixed in new version, could u please double check?
