### ISSUE TITLE
Horizontal scrolling is weird

### ISSUE THREAD

**Issue by MrMoronIV** [jsGanttImproved/jsgantt-improved#114]
In latest Chrome / Firefox there seem to be some issues with scrolling using the touchpad of my laptop.

Whenever I scroll sideways it goes really really slow in Chrome 
When I scroll sideways in Firefox using the actual scrollbar it is battling my movement.

Any idea?

This behavior is also seen on the demo page

**Comment by mariohmol** [comment]
Hi. i can reproduce this in Firefox on a desktop.. 
this is related with scroll where changes the scroll of the top as well.. we have to find something related to  firefox.. any ideas?

**Comment by mariohmol** [comment]
There is a release in 2.1.0 that is in test.. its a new way of rendering and it fixes this issue.. can u double check?
