### ISSUE TITLE
use the library for non-timed based charts

### ISSUE THREAD

**Issue by MastroLindus** [jsGanttImproved/jsgantt-improved#12]
Hi,

I am looking into this library because it does almost exactly what I need, except for the fact that it seems very dependent on timeUnits (hours, day, weeks, months, etc).

I would need it instead for displaying a list of tasks for which I don't know yet the duration, most of them would run only for a few seconds or less. I need instead to simply display the tasks based on their dependencies order, but apart from that assume that they all run the same X amount of time.
Moreover I would need to reuse the collapsable group tree on the left of the chart.

Is there a way already to do it properly? 

Otherwise I guess I could assign all tasks the duration of 1 hour and try to hide the top headers where the hours/days are displayed... would that kind of approach work?

Thanks again for the component by the way!

**Comment by MastroLindus** [comment]
alternatively, how much work would it be to modify the library to handle milliseconds, seconds and minutes?

**Comment by jsGanttImproved** [comment]
The original jsgantt had a minutes view but it was incredibly buggy so I ripped it out.  It also had the scope to create immense charts if someone switched into the view by accident from a normal gantt chart, although I have mitigated that problem somewhat.

I'd suggest one of two approaches:

1. Use the week view and look at the [customised date formats](http://jsganttimproved.x10host.com/#tOptionsFormatSpecifiers) for the headers (week view gets you up to 53 sequential numbers)
2. User the hour view, again look at [customised date formats](http://jsganttimproved.x10host.com/#tOptionsFormatSpecifiers) for the headers and set a very wide [column width for the hour column](http://jsganttimproved.x10host.com/#tOptionsLayout), (hour view gets you 24 sequential numbers.) You will probably need to play with css styles for vertical lines if you need them but there are simple examples commented out in the distributed file you can play with.

**Comment by eduardomourar** [comment]
I'm closing this for now.
