### ISSUE TITLE
Taskname click event is fired twices.

### ISSUE THREAD

**Issue by sreemat1993** [jsGanttImproved/jsgantt-improved#125]
When vEvent:{ taskname:console.log} and vEventClickRow both are defined the clicked event is fired twice

**Comment by sreemat1993** [comment]
Make sense. Sorry my mistake.
But I observed that the event is fired while page is refreshed each time.

**Comment by mariohmol** [comment]
We have events in this demo and u can see that does not show on load.. just on click https://jsganttimproved.github.io/jsgantt-improved/demo.html

**Comment by mariohmol** [comment]
I added some docs about it cause was missing. if this persists please reopen
