### ISSUE TITLE
How can I implement JSGantt-Improve using a sharepoint 2013 task list

### ISSUE THREAD

**Issue by dlc78866** [jsGanttImproved/jsgantt-improved#13]
I am using SharePoint 2013 and I do not like the limitations that the Web Gantt View has. I have  project tasks list already populated and do not want to export it into an xml file. I want JSGantt-Improve to pull the data from the sharepoint task table an generate the gantt view using JSGantt-Improve. Is there a way to do this?

**Comment by eduardomourar** [comment]
I'm closing this, but will reopen if more information is given.
