### ISSUE TITLE
How to use it in the vue framework?

### ISSUE THREAD

**Issue by zhangjing007** [jsGanttImproved/jsgantt-improved#130]
Hello, I want to know how to use under the vue framework.

**Comment by mariohmol** [comment]
Check this out https://stackblitz.com/edit/vue-sp2oj9

**Comment by zhangjing007** [comment]
> Check this out https://stackblitz.com/edit/vue-sp2oj9

ok  thanks !  I will go see it soon, thank you again.

**Comment by zhangjing007** [comment]
Hello, there is a question, how do I add the corresponding data to the custom column? Or can you look at the more comprehensive api documentation there?
The following code shows how to customize the column, but how to assign it?
` vAdditionalHeaders: {
          category: {
            title: 'Category'
          },
          sector: {
            title: 'Sector'
          }`

**Comment by zhangjing007** [comment]
Added in AddTaskItemObject, the information is not used

**Comment by mariohmol** [comment]
kind lost with the last question.. could u make it? this a new example with fetch an url .. simulating an api

https://stackblitz.com/edit/vue-jsgantt
