### ISSUE TITLE
Additional column not populated while add task manually.

### ISSUE THREAD

**Issue by sreemat1993** [jsGanttImproved/jsgantt-improved#136]
the exports.TaskItemObject = function (object) {
    return new exports.TaskItem(object.pID, object.pName, object.pStart, object.pEnd, object.pClass, object.pLink, object.pMile, object.pRes, object.pComp, object.pGroup, object.pParent, object.pOpen, object.pDepend, object.pCaption, object.pNotes, object.pGantt, object.pCost, object.pPlanStart, object.pPlanEnd);	    return new exports.TaskItem(object.pID, object.pName, object.pStart, object.pEnd, object.pClass, object.pLink, object.pMile, object.pRes, object.pComp, object.pGroup, object.pParent, object.pOpen, object.pDepend, object.pCaption, object.pNotes, object.pGantt, object.pCost, object.pPlanStart, object.pPlanEnd,**object**);
};};

The object parameter is not passed.

**Comment by mariohmol** [comment]
I dont get it.. the code we have is this

```
export const AddTaskItemObject = function (object) {
  if (!object.pGantt) {
    object.pGantt = this;
  }
  return this.AddTaskItem(TaskItemObject(object));
}```

**Comment by sreemat1993** [comment]
@mariohmol
The return statement call this function exports.TaskItemObject in which pDataObject is not passed

**Comment by mariohmol** [comment]
can u point out in the source where this should be changed?

**Comment by sreemat1993** [comment]
In task.ts 
Line number 136
export const TaskItemObject = function (object) {
  return new TaskItem(object.pID,
    object.pName,
    object.pStart,
    object.pEnd,
    object.pClass,
    object.pLink,
    object.pMile,
    object.pRes,
    object.pComp,
    object.pGroup,
    object.pParent,
    object.pOpen,
    object.pDepend,
    object.pCaption,
    object.pNotes,
    object.pGantt,
    object.pCost,
    object.pPlanStart,
    object.pPlanEnd,
    **object**
  );
}
Add the **object** in this function

**Comment by mariohmol** [comment]
Hi thanks for that, version 2.1.2 has this fix!
