### ISSUE TITLE
IE compatible

### ISSUE THREAD

**Issue by wisebobo** [jsGanttImproved/jsgantt-improved#137]
**Describe the bug**
The current code is base on the new standard, which can't be well support in IE.

**Issue Screenshots**
![image](https://user-images.githubusercontent.com/46515921/50881777-a668bd80-141d-11e9-899d-72f678631e0c.png)
![image](https://user-images.githubusercontent.com/46515921/50881754-951fb100-141d-11e9-8ca8-277362bcf17d.png)

**Fix Screenshots **
![image](https://user-images.githubusercontent.com/46515921/50881869-e92a9580-141d-11e9-8c46-11411a9a1870.png)

![image](https://user-images.githubusercontent.com/46515921/50881905-05c6cd80-141e-11e9-8476-f97b8abf3df9.png)

**Desktop (please complete the following information):**
 - Browser IE 11

**Comment by mariohmol** [comment]
Hi thanks for that.. why we need the slice in array?

**Comment by mariohmol** [comment]
Hi thanks for that, version 2.1.2 has this fix! I did a different loop and it might work.. can u double check please? if is not working please reopen! bests

**Comment by JackAlonso** [comment]
Hi, the bug in IE11 remains. The gantt doens't load and show the following error message.

Oi, o bug no IE11 continua. O gantt não carrega e mostra a mensagem de erro conforme o print abaixo.

** Bug in IE11 **
![image](https://user-images.githubusercontent.com/20502609/64448619-7c52c280-d0b4-11e9-9434-4f2259588e26.png)

I changed the line 1328 and works for me.

Alterei a linha conforme print abaixo e está carregando para mim. A versão utilizada é a 2.1.2.

**Fix screenshot**
![image](https://user-images.githubusercontent.com/20502609/64448834-f2efc000-d0b4-11e9-8775-4ceb486c376c.png)

**Comment by mariohmol** [comment]
thanks. released this change on 2.4.10
