### ISSUE TITLE
Grids are not alligned on the day format view

### ISSUE THREAD

**Issue by jlanao** [jsGanttImproved/jsgantt-improved#139]
**Describe the bug**
the rows between the left grid and the right grid are unalligned when i select the day format view. I made sure the zoom was 100% on my browser.

**To Reproduce**
1. Go to https://jsganttimproved.github.io/jsgantt-improved/demo.html
2. Click on Format: Day
3. Scroll down to a task

**Expected behavior**
Rows should appear in the same level. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46685353/51128895-fa491d00-17f6-11e9-8135-0ae56c50a1a8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mariohmol** [comment]
Seems to be missing the footer with days in gantt table

**Comment by mariohmol** [comment]
Fixed in 2.1.4

Thanks!
