### ISSUE TITLE
Cost, Printing, Exporting

### ISSUE THREAD

**Issue by pnunes2004** [jsGanttImproved/jsgantt-improved#14]
When will you have the cost part implemented? Will it have also Cost Planned VS Actual Cost?
How can i print the Gantt in a feasible manner? Will you have a button to do it?
Is it possible to export it to PDF also?

**Comment by thclark** [comment]
I'd be quite interested in printing too.

But, it's probably a bit out of scope of the core jsGanttimproved. Exporting to SVG or PDF or similar from scratch would be a nightmare - better to use some kind of third party plugin/library to capture the containing element's html then convert it.

## Possible libraries / approaches 
Choice of approach will likely be **specific to your backend** and the view that you're rendering the chart into. Relevant SO posts [here](https://stackoverflow.com/questions/28291112/how-to-turn-fully-rendered-html-page-using-django-into-pdf) and [here](https://stackoverflow.com/questions/23359083/how-to-convert-webpage-into-pdf-by-using-python) whose answers include:
- a **javascript** solution [html2canvas](http://html2canvas.hertzen.com) which is probably the best candidate were an export tool to be built right into jsGanttImproved.
- an **html** conversion service directly embeddable as a 'save to pdf' button in your rendered html, good potential if you've no backend [https://www.sejda.com/html-to-pdf](https://www.sejda.com/html-to-pdf) but might be susceptible to problems with viewport size 
- a few **python** base approaches if that's your cup of tea (mine is):
  - [pdfkit](https://pypi.python.org/pypi/pdfkit)
  - A few ideas from the django devs [here](https://docs.djangoproject.com/en/1.7/howto/outputting-pdf/#further-resources)
  - Of which the best looking is [xhtml2pdf](https://github.com/xhtml2pdf/xhtml2pdf)
- a generic binary tool you can run on your server called [htmldoc](https://michaelrsweet.github.io/htmldoc/index.html)

## Workaround
Today, I worked around by viewing the chart using chrome then simply saving as PDF via the print menu - I had to fiddle around with paper size settings, but was able to get the entire chart onto a single PDF for onward use without too much trouble.

**Comment by mariohmol** [comment]
As Cost we have now and exporting its better to use browser PDF, closing this and opened another one just for printing https://github.com/jsGanttImproved/jsgantt-improved/issues/122
