### ISSUE TITLE
Milestone and task bars go beyond end of grid to the right

### ISSUE THREAD

**Issue by codytheking** [jsGanttImproved/jsgantt-improved#141]
**Describe the bug**
The milestones and tasks extend beyond the right side of the grid, but only happens in the day format and works fine for the week, month, and quarter formats.

**To Reproduce**
1. Create two tasks.
2. Task with later due date will be sticking out past the right end of the grid.

**Expected behavior**
Grid should extend past (or at least even with) the end of the task with the latest due date.

**Screenshots**
![https://i.imgur.com/txDRT0K.png](https://i.imgur.com/txDRT0K.png)

**Desktop (please complete the following information):**
 - OS: Tested on Mac, Windows, Linux
 - Browser: Tested on Chrome, Firefox, Safari
 - Version: Chrome v71.0.3578.98

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: 9.0
 - Browser: Chrome
 - Version: v71.0.3578.99

**Additional context**

**Comment by mariohmol** [comment]
thanks for that! Can u provide the json with data?

**Comment by codytheking** [comment]
```
[
  {
    "pID": 1,
    "pName": "Define Chart API",
    "pStart": "",
    "pEnd": "",
    "pPlanStart": "",
    "pPlanEnd": "",
    "pClass": "ggroupblack",
    "pLink": "",
    "pMile": 0,
    "pRes": "Mario",
    "pComp": 0,
    "pGroup": 1,
    "pParent": 0,
    "pOpen": 1,
    "pDepend": "",
    "pCaption": "",
    "pNotes": "",
    "category": "",
    "sector": ""
  },
  {
    "pID": 11,
    "pName": "Chart Object",
    "pStart": "2018-06-20",
    "pEnd": "2018-07-20",
    "pClass": "gtaskpink",
    "pLink": "",
    "pMile": 0,
    "pRes": "Henrique",
    "pComp": 100,
    "pGroup": 0,
    "pParent": 1,
    "pOpen": 1,
    "pDepend": "",
    "pCaption": "",
    "pNotes": "",
    "category": "",
    "sector": ""
  },
  {
    "pID": 12,
    "pName": "Task Objects",
    "pStart": "2018-08-10",
    "pEnd": "2018-09-10",
    "pClass": "gtaskblue",
    "pLink": "",
    "pMile": 0,
    "pRes": "Henrique",
    "pComp": 40,
    "pGroup": 0,
    "pParent": 1,
    "pOpen": 1,
    "pDepend": "",
    "pCaption": "",
    "pNotes": ""
  }
]
```

**Comment by mariohmol** [comment]
here is working =(

**Comment by codytheking** [comment]
> what ang-jsoneditor version you have?

Not sure. I am just using the `jsgantt.js`, `jsgantt.css`, `index.html`, and `data.json` files.

**Comment by mariohmol** [comment]
It might be something else in your environment... to test..

Go here: https://jsganttimproved.github.io/jsgantt-improved/demo.html
And use `./fixes/bug141.json` in place of `./fixes/data.json`

**Comment by codytheking** [comment]
Everything worked fine on there.

**Comment by mariohmol** [comment]
great.. feel free to reopen if u need
