### ISSUE TITLE
tooltip displays hidden columns

### ISSUE THREAD

**Issue by hktr92** [jsGanttImproved/jsgantt-improved#142]
Hello,
I've implemented JSGantt in a project and the client doesn't want to see Duration, Completion and Notes columns. I disabled those columns but when tooltip is shown, those columns does display.

I've looked for documentation but i was unable to find any.

Is this a bug or it is a special config option?

**Comment by mariohmol** [comment]
here u can disable the columns and see the tooltip

https://jsganttimproved.github.io/jsgantt-improved/demo.html

maybe u are refreshing the view or the data and is calling render again?

**Comment by hktr92** [comment]
I've opened the source code and saw that there are two different methods: `setShowDur` and `setShowTaskInfoDur`, both which I couldn't find in documentation and / or demo.

Now everything works fine. Thank you for the support.
