### ISSUE TITLE
How I can set scroll to today date

### ISSUE THREAD

**Issue by dmitrydrynov** [jsGanttImproved/jsgantt-improved#145]
Hey guys,

How I can set scroll to today date?

I did try to use g.setScroolTo('today'); and vScrollTo: 'today' in config.
It's don't work

**Comment by mariohmol** [comment]
good question.. i dont know.. maybe after the last refactor this was lost? we have to investigate the code and see what we have so far...

**Comment by mariohmol** [comment]
@viniciusrc15 this is close to the #176

find using selector the position of the line of current date.. and scroll to that point

**Comment by mariohmol** [comment]
dup with #210
