### ISSUE TITLE
Border of the additional columns

### ISSUE THREAD

**Issue by jpussacq** [jsGanttImproved/jsgantt-improved#146]
**Describe the bug**
The top border of the additional columns is not being drawn. The same happens with the lower border.

**To Reproduce**
1. Add an additional column
2. Draw the gantt

**Expected behavior**
I imagine that it should be drawn in a similar way to the rest of the columns

**Screenshots**
![ganttop](https://user-images.githubusercontent.com/36697906/52484531-518fa280-2b95-11e9-89ca-09b842c9430a.png)
.

**Desktop:**
 - OS: Windows 10 & 7
 - Browser [chrome, IE]
 - Version v2.1.2

**Smartphone:**
Not tested

**Workaround**
Solved adding this:

```
.gadditional {
    border: #efefef 1px solid;
}
```

**Comment by mariohmol** [comment]
HI thanks for that!! Already on version 2.1.5
