### ISSUE TITLE
Fixed header for gantt chart and task list

### ISSUE THREAD

**Issue by sreemat1993** [jsGanttImproved/jsgantt-improved#149]
Is it possible make gantt chart header and task list header as fixed?
Chart with larger number of dataset is difficult to scroll through the chart.

**Comment by mariohmol** [comment]
I tried but its not possible to fix vertical and horizontal.. so I choose for horizontal..

do you have a print or something to show this use case?

**Comment by mariohmol** [comment]
i dont know if is feaseable.. if u find something may help us.. please reopen

**Comment by nidu** [comment]
Hi, i've made a dirty prototype for fixed header here - https://github.com/nidu/jsgantt-improved
Currently only tested it with demo.

Basic idea is:

1. user sets component height explicitly
2. split the table into header table and content table
3. sync vertical scroll for table content and chart content
4. new vertical scrolls impose some restrictions on existing horizontal scroll, so it's reimplemented too using scroll syncing

Some drawbacks:

1. Have to calculate scrollbar width in styles. Don't know how bad is it.
2. Column widths are fixed. It's easier to sync header and content tables. Widths can be synced with JS, but that's a lot of effort while i'm pretty happy with fixed column width.
3. I'm using flex for it. Didn't see it in the codebase, so not sure if it breaks any compatibility promises. I guess it could be done without flex also.

**Comment by mariohmol** [comment]
Hi! Thanks for this @nidu !!

The new version has this features.. could you please check it out and see if this makes the same that you expect?

**Comment by mariohmol** [comment]
@viniciusrc15 you did this right?

**Comment by nidu** [comment]
@mariohmol which version do you mean? I'm using 2.2.9 (just `npm install`ed couple of days ago).

I can see in produced html that for table both header and content are inside one table and i'm not sure it's possible to make fixed header with this setup.

Moreover i don't see a way to enable fixed header in current sources. I expect there should be some way to set height, but can't see any in `draw.ts`.

**Comment by viniciusrc15** [comment]
@mariohmol No, I didn't. I maked only scroll overflow-y of the mains right and left simultaneously, but I can will trying make later, in moment I'm busy. Okay?

**Comment by mariohmol** [comment]
@viniciusrc15 thanks!  I was wondering if u did this back in time..

but its ok .. @nidu did it...

@nidu can u pls make a PR with your change?

**Comment by nidu** [comment]
@mariohmol i'm still working on it and testing, trying to reduce amount of changes necessary. That's potentially breaking change since it changes some core styles (like introducing flex and making fixed width for columns). Also there are scrollbar size related manipulations and i'm not sure if there can be any compatibility issues.

**Comment by mariohmol** [comment]
Awesome work @nidu !!!

thanks

**Comment by nidu** [comment]
@mariohmol no problem, i needed this functionality! Thank you for the library!
