### ISSUE TITLE
Main Group Task

### ISSUE THREAD

**Issue by pnunes2004** [jsGanttImproved/jsgantt-improved#15]
Is it possible to split the "main group task" (i.e. that has other tasks in it) with different colors according to milestones inside them?
For instance i have the following:

Main task
           task 1
           task 2
           milestone 1
           task 3
           task 4
           milestone 2

and according to this, the "Main Task" should hva two colors

**Comment by eduardomourar** [comment]
I'm closing this, but will reopen if more information is given.
