### ISSUE TITLE
How do I set onclick event to a specific cell "help wanted"

### ISSUE THREAD

**Issue by calvintts** [jsGanttImproved/jsgantt-improved#150]
I want to customize and bind function to specific cells with parameters in it. I tried to setOptions with VEvents but it does not allow me to pass parameter or it will invoke right way.

Thank you!

**Comment by mariohmol** [comment]
Hi.. in docs we have this

https://github.com/jsGanttImproved/jsgantt-improved/blob/develop/Documentation.md

````
vEvents: {
        taskname: console.log,
        res: console.log,
        dur: console.log,
        comp: console.log,
        startdate: console.log,
        enddate: console.log,
        planstartdate: console.log,
        planenddate: console.log,
        cost: console.log
      },```

did u try that?

**Comment by calvintts** [comment]
yes, I tried calling a function with 
test = (something) ={console.log(something);}
  g.setOptions({
          vUseSort:0,
          vEvents: {
            taskname: test(something),
             },
        });

but it triggered the function when the page is loaded but on working on clicking.

I would like to know how to use g.setEvents() function on a specific cell. I tried to use it but I assumed it has to be called from the task but I could not call it from my task because I loaded the data from external xml. 

for your example reference, my code: 
var g = new JSGantt.GanttChart(document.getElementById('gdiv'), 'day');
      if (g.getDivId() != null) {
        test = (something) =>{
          console.log(something)
        }
        g.setCaptionType('Resource'); 
        g.setDayMajorDateDisplayFormat('dd mon');
        g.setDateTaskDisplayFormat('dd month yyyy HH:MI');
        JSGantt.parseXML('testgantt.xml', g)
        g.setOptions({
          vUseSort:0,
          vEvents: {
            taskname: test(something),
        });
        g.Draw();
      } else {
        alert("Error, unable to create Gantt Chart");
      }

**Comment by geeksilva97** [comment]
Hi @calvintts 
In your code, the ** test ** function is called (so it only executes on the load). On the line `taskname: test(something)`
Try using this code 

```javascript
var g = new JSGantt.GanttChart(document.getElementById('gdiv'), 'day');
 if (g.getDivId() != null) {
        test = (something) =>{
          console.log(something)
        }
        g.setCaptionType('Resource'); 
        g.setDayMajorDateDisplayFormat('dd mon');
        g.setDateTaskDisplayFormat('dd month yyyy HH:MI');
        JSGantt.parseXML('testgantt.xml', g)
        g.setOptions({
          vUseSort:0,
          vEvents: {
            taskname: test, 
        });
        g.Draw();
      } else {
        alert("Error, unable to create Gantt Chart");
      }
```

**Comment by calvintts** [comment]
hi @geeksilva97 
I used your code and it works. However, I want to assign a function to a cell/row in the table
I do not understand what this means
**setEvents():
Controls events when a task is click in table data. You have to pass an object with the column and function. ex.: { taskname: console.log, res: console.log }**
and how to use it.
Can anyone show me an example of how to use it? Please and thanks.

**Comment by mariohmol** [comment]
like this?

``` 
{ taskname: event => {
 fetch('myapp'+event.id)
} 
}
```

**Comment by geeksilva97** [comment]
> hi @geeksilva97
> I used your code and it works. However, I want to assign a function to a cell/row in the table
> I do not understand what this means
> **setEvents(): Controls events when a task is click in table data. You have to pass an object with the column and function. ex.: { taskname: console.log, res: console.log }**
> and how to use it.
> Can anyone show me an example of how to use it? Please and thanks.

Glad it went right!

**Comment by geeksilva97** [comment]
@calvintts 
For each cell in the table you can bind a function, which in turn will be triggered by click. To pass a function you can't use the parentheses, because this will run the function. You need pass the function name (that is a object).

This concept is knowledge by **callback function**.

See more at https://developer.mozilla.org/en-US/docs/Glossary/Callback_function

**Comment by mariohmol** [comment]
I'm closing for now.. if is something we need to implement.. please reopne.

thanks @geeksilva97

**Comment by calvintts** [comment]
@mariohmol 
{ taskname: event => {
 fetch('myapp'+event.id)
} 
}
this would bind the function to every cell right? I wanted to bind it to specific row/cell only. 
Right now I am using the same approach and a switch statement to check if it is the right cell. I was wondering if there is a more dynamic way instead of binding it manually. 

Sorry for the trouble and thank you for replying.

**Comment by geeksilva97** [comment]
There is no other way. For that particular need you should do this same verification (as you are already doing with the `switch`).

**Comment by abeeching1** [comment]
> Hi @calvintts
> In your code, the ** test ** function is called (so it only executes on the load). On the line `taskname: test(something)`
> Try using this code
> 
> ```js
> var g = new JSGantt.GanttChart(document.getElementById('gdiv'), 'day');
>  if (g.getDivId() != null) {
>         test = (something) =>{
>           console.log(something)
>         }
>         g.setCaptionType('Resource'); 
>         g.setDayMajorDateDisplayFormat('dd mon');
>         g.setDateTaskDisplayFormat('dd month yyyy HH:MI');
>         JSGantt.parseXML('testgantt.xml', g)
>         g.setOptions({
>           vUseSort:0,
>           vEvents: {
>             taskname: test, 
>         });
>         g.Draw();
>       } else {
>         alert("Error, unable to create Gantt Chart");
>       }
> ```

So in this example here how would you go about defining 'something' so that when each row is clicked the console would log a different value e.g the name of the task?

**Comment by mariohmol** [comment]
For a specific row and column we dont have any listener, maybe if there is more people asking for this we can try to think about a solution for that
