### ISSUE TITLE
No text boxes or Dropdown list shown i-e editing not allowed in chart in release 2.1.2

### ISSUE THREAD

**Issue by shahzaib4106** [jsGanttImproved/jsgantt-improved#152]
I am unable to edit this , as i am not showing text boxes or drop down lists after implementing in release2.1.2

**Comment by mariohmol** [comment]
can u please show in an example like this https://codepen.io/mariomol/pen/mQzBPV

**Comment by relusion** [comment]
Same issue here.  No editors are available. it's all readonly.  using the sample app code from your repository.

**Comment by mariohmol** [comment]
this is just for internet explorr , right?

**Comment by relusion** [comment]
not really, I tested it in FF and Chrome.

**Comment by mariohmol** [comment]
If u go to this link for instance.. on the left pane.. i can see inputs and selects... do u see the same?

**Comment by relusion** [comment]
I am sorry. what link? I see no URLs embeded  inside your message.

**Comment by mariohmol** [comment]
sorry.. this link .. https://jsganttimproved.github.io/jsgantt-improved/demo.html

**Comment by mariohmol** [comment]
hi.. if this is still and issue.. please reopen
we have a new version with a lot of thigs.. needs to be retested..

thanks
