### ISSUE TITLE
how to add an image to the initial activity of the project (pname)

### ISSUE THREAD

**Issue by jopehi** [jsGanttImproved/jsgantt-improved#154]
Hello everyone, greetings

I would like to know if it is possible to add an icon image to the main activity of the project in the pname column, I need it to add actions such as opening a form for example.

it's possible?

Thanks for such an excellent project

Joseph37

**Comment by mariohmol** [comment]
I think you can pass a html as a name.. ex.: `pName: "Define Chart <strong>API</strong>",`

**Comment by jopehi** [comment]
hey mario, thanks for your guidance.

I have tried, but when generating the diagram, in the name of the activity it presents the html code and not the name with its desired appearance.

What I can be doing wrong?

**Comment by mariohmol** [comment]
Can u please push an example like this https://codepen.io/mariomol/pen/mQzBPV

**Comment by jopehi** [comment]
To be more precise, I share an image of what happens

<a href='https://i.imgur.com/dzc72fk.jpg'>https://i.imgur.com/dzc72fk.jpg</a>

in the main activity it does not accept code, but in the subactivities if it accepts.

**Comment by mariohmol** [comment]
owww thats true.. i remember this..
fixed on 2.1.7

thanks!

**Comment by jopehi** [comment]
ready mario, I'm fine, thank you
