### ISSUE TITLE
Bug Vue-jsgantt

### ISSUE THREAD

**Issue by JackFront** [jsGanttImproved/jsgantt-improved#156]
Hello bro. I was testing and reading your library, and I was curious to see how it works in Vue, and I did not succeed because of this image bug, just telling you if you have not seen. ;)

![bug vue jsgantt](https://user-images.githubusercontent.com/43053055/53355735-6fd0fe80-3908-11e9-92b8-fc3639e43b87.png)

**Comment by mariohmol** [comment]
is working here.. 

i can see that it cant find the data.json `https://jsganttimproved.github.io/jsgantt-improved/fixes/data.json` 

try to use another url ?

**Comment by JackFront** [comment]
Oh it's ok, sorry bro and thanks for fast answer, you can talk me if have draggable grid in gantt?

**Comment by mariohmol** [comment]
draggable tasks in the grid? not yet =)
