### ISSUE TITLE
Space between Grid and Chart

### ISSUE THREAD

**Issue by StephenMulryan** [jsGanttImproved/jsgantt-improved#157]
Hi,

I have hid a number of the fields using the following commands:

` g.setShowRes(0);
 g.setShowStartDate(0);
 g.setShowEndDate(0);
`

There is now a space left between the Grid and the Chart. Is it possible to make the chart fill this void?

I see that this issue was previously addressed in #16 but it is not clear what the fix is? 

![spacebetweengridandchart](https://user-images.githubusercontent.com/3050277/53476792-21884080-3a6b-11e9-9801-9ef945d64fb1.png)

**Comment by StephenMulryan** [comment]
I ended up altering the width parameter of .gmainright to be 75% of the content and .gmainleft to be 25% of the content.

**Comment by mariohmol** [comment]
Thanks..

i created a troubleshooting are for this 
https://github.com/jsGanttImproved/jsgantt-improved/blob/develop/Documentation.md#troubleshooting

**Comment by Sayali4535** [comment]
Hi,
I have altered the width parameter of .gmainright to be 75% of the content and .gmainleft to be 25% of the content.

But its not working. Please help.

Thanks.

**Comment by StephenMulryan** [comment]
A good idea would be to attach your altered CSS file and an image showing the Gantt chart and grid that you are seeing.

**Comment by Sayali4535** [comment]
Hi,
I have attached my altered css and an image showing the gantt chart and grid.
Please check.
![gantt-chart-css](https://user-images.githubusercontent.com/20036206/57059516-67fc5480-6cd3-11e9-9de5-c7324a6582b3.png)
![gantt-chart](https://user-images.githubusercontent.com/20036206/57059524-6d599f00-6cd3-11e9-9a51-af55904b83c5.png)


Thanks,
Sayali.

**Comment by StephenMulryan** [comment]
Have you played around with the settings for Column widths based on what frequency you select?

Check out method calls under the Layout section:
https://github.com/jsGanttImproved/jsgantt-improved/blob/master/Documentation.md

The changing of .gmainright and .gmainleft worked for me but I mostly use the Month frequency.

**Comment by Sayali4535** [comment]
Thanks a lot.
Its working now. 
I had altered my component's css file instead of main css file 'style.css'.

**Comment by adewiranataputra** [comment]
![gambar](https://user-images.githubusercontent.com/29900822/61032032-e15aa680-a3ea-11e9-91b6-6b7274985ebb.png)
I have a problem with g.draw (), an error that is displayed like this, can you provide a solution?

**Comment by hoangdev92** [comment]
Hello 
I am trying to add it to rails but an error has occurred

![Screenshot from 2020-07-23 17-45-58](https://user-images.githubusercontent.com/68582193/88278395-7e456480-cd0c-11ea-95fd-d7e477c16df3.png)

**Comment by mariohmol** [comment]
@hoangdev92 it seems that is missing the jsgantt js in your html

**Comment by rhuanbarreto** [comment]
This instruction is not valid anymore once flex columns are being used.
