### ISSUE TITLE
Vertical Scrollbar for ganttchart

### ISSUE THREAD

**Issue by mertheyecan** [jsGanttImproved/jsgantt-improved#158]
Hello,
sorry fixed it quickly.

**Comment by mariohmol** [comment]
u did anything special to make it work?

**Comment by mertheyecan** [comment]
```
$( ".gmainleft" ).scroll(function() {
  console.log(this.scrollTop);
  $('.gmainright').scrollTop(this.scrollTop);
});
```

Just added this to main html.

**Comment by jolewis-ddn** [comment]
Unfortunately, this only seems to work until you change the pFormat value. Once you change it, even if you change it back to the initial value, vertical scrolling stops working - i.e. the Gantt chart no longer scrolls vertically, though the task list scrolls properly.

**Comment by nidu** [comment]
@jolewis-ddn what is the issue? If i set Height to 300px on the [demo page](https://jsganttimproved.github.io/jsgantt-improved/docs/demo.html) - vertical scroll works.

Also you say that code above is not working after changing pFormat. Do you mean when user selects format in upper-left corner? If yes - you can put the code into `afterDraw` callback.

**Comment by mariohmol** [comment]
@nidu thanks for you awesome work!!!

i think this can be closed than.. right? 

if this still an issue @jolewis-ddn can tell us and then we can reopen this
