### ISSUE TITLE
Trim space between task list and chart

### ISSUE THREAD

**Issue by hacqua** [jsGanttImproved/jsgantt-improved#16]
I'm using the "setShow..." methods to hide all columns in the task list except for the task name, but it seems the chart itself remains in its original position regardless of how many columns are in the list, so there is a huge blank space between the two. Is there a way to force the chart to start right after the task name in this case?

**Comment by giovanitadei** [comment]
I have the same problem. Not sure if I'm missing something. Any guidance would be really appreciated.

**Comment by giovanitadei** [comment]
@hacqua , I managed to correct this by changing the hard-coded left container width from 532px to 177px. This is definitely not a real solution, as the container should adapt its size in accordance to the columns that we choose to display on it, but if you intend to use the component showing only the name tree column on the left container, then this workaround might be enough.

In jsgantt.css, look for the entries that are commented as "LC width". You'll find them in the definitions for the .gchartcontainer, .glistgrid and .glistlbl classes. Change their values from 532px to 177px and the chart should display properly when only the name column is showing in the left pane.

Hope that helped. Cheers.

**Comment by hacqua** [comment]
@giovanitadei, thanks!
I ended up hiding the task list altogether by changing these:
.gchartgrid: from **overflow: auto** to **overflow: visible**
.gchartlbl:	from **overflow: hidden** to **overflow: visible**
Then I'm showing the task name at the right of each bar instead of the resource name. Works for my purposes ;-)

**Comment by KillGorack** [comment]
Thanks! Was hoping someone came into this one!

**Comment by mariohmol** [comment]
fixed in v2!
