### ISSUE TITLE
Sort By pID

### ISSUE THREAD

**Issue by sgokulnath** [jsGanttImproved/jsgantt-improved#162]
**Is your feature request related to a problem? Please describe.**
By default, the items in the gantt chart gets sorted by the date. Would like to have the sort option by another field. 

**Describe the solution you'd like**
I wish to sort by pID. And i am not able to remove the default sort either.

**Describe alternatives you've considered**
I tried to remove the default sort using setUseSort(0) and also tried the below code:

  public editorOptions: GanttEditorOptions;
  public data: any;
  @ViewChild(GanttEditorComponent) editor: GanttEditorComponent;
  vUseSort = 'false';

  constructor(public fb: FormBuilder) {
  }

  ngOnInit() {
    this.data = this.initialData();  
    this.editorOptions = {
      vUseSort: this.vUseSort === 'true'
    };
    this.editor.setOptions(this.editorOptions);
    // this.editorOptions.onChange = this.change.bind(this);
  }

 But it doesn't work. Kindly suggest an idea to solve this problem.

**Comment by mariohmol** [comment]
Isnt that be an issue using the ng-jsgantt? Or change this issue to use pure js to test the gantt component..

**Comment by mariohmol** [comment]
In this example we have the sort checkbox.. this works for u https://jsganttimproved.github.io/jsgantt-improved/demo.html ?

**Comment by mariohmol** [comment]
hi.. as was no answer here will close.. feel free to open again

**Comment by AndresGaPa98** [comment]
I resolved this issue with **vUseSort : 'true'**
And not with
vUseSort = 'false';

constructor(public fb: FormBuilder) {
}

ngOnInit() {
this.data = this.initialData();
this.editorOptions = {
vUseSort: this.vUseSort === 'true'
};
this.editor.setOptions(this.editorOptions);

**Comment by AndresGaPa98** [comment]
because vUseSort: this.vUseSort === 'true' always return false, cuz 'false' is not equals to 'true'
