### ISSUE TITLE
Last task bar overflows for pPlanEnd

### ISSUE THREAD

**Issue by sukanyasg** [jsGanttImproved/jsgantt-improved#163]
**Describe the bug**
If there is a `pPlanEnd` defined for the last task bar, the bar extends beyond the chart div and the last two weeks are not populated 

**To Reproduce**
Use this set of data
```
[
	{
		"pid": 1,
		"pStart": "2019-03-07",
		"pEnd": "2020-07-31",
		"pPlanEnd": "2022-03-22",
		"pName": "step 1"
	},
	{
		
		"pid": 2,
		"pStart": "2022-03-23",
		"pEnd": "2023-12-14",
		"pPlanEnd": "2024-03-06",
		"pName": "step 2"
	},
	{
		"pid": 3,
		"pStart": "2024-03-07",
		"pEnd": "2025-08-26",
		"pPlanEnd": "2026-08-12",
		"pName": "step 3"
	},
]
```

**Expected behavior**
The dates should populate until the end of the last task bar and the task bar should not extend beyond the last date

**Screenshots**
<img width="1057" alt="Screen Shot 2019-03-15 at 11 34 56 AM" src="https://user-images.githubusercontent.com/7634917/54447054-67edc880-4716-11e9-8bd8-77b269819ed7.png">

**Desktop (please complete the following information):**
 - OS: OS X Yosemite [10.10.5]
 - Browser: Google chrome V 72.0.3626.121

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by vizFlux** [comment]
+1

**Comment by mariohmol** [comment]
Tried to reproduce this without success!

If you go in this link

* https://jsganttimproved.github.io/jsgantt-improved/demo.html

And change the data input to this `./fixes/planend.json`, you will see your data working 

If is not please reopen this
