### ISSUE TITLE
Error while ng build --prod in events.ts file.

### ISSUE THREAD

**Issue by saiHemanthGitHub** [jsGanttImproved/jsgantt-improved#167]
**Describe the bug**
Error while ng build --prod in angular 6 project.
**ERROR in node_modules/jsgantt-improved/src/events.ts(197,51): error TS2339: Property 'forEach' does not exist on type 'NodeListOf<Element>'.** 

**To Reproduce**
1. Take npm install jsgantt-improved
2. execute "ng build --prod"

**Expected behavior**
The error should not come and build should be success.

**Screenshots**
**Additional context**
Error:
**ERROR in node_modules/jsgantt-improved/src/events.ts(197,51): error TS2339: Property 'forEach' does not exist on type 'NodeListOf<Element>'.**

**Comment by mariohmol** [comment]
fixed on #165
