### ISSUE TITLE
Javascript error on resizing browser

### ISSUE THREAD

**Issue by schweighart** [jsGanttImproved/jsgantt-improved#168]
When the browser is resized the following error is visibile in the console:

jsgantt.js:1247 Uncaught TypeError: Cannot set property 'scrollTop' of null
    at jsgantt.js:1247

Can be reproducesd here: https://jsganttimproved.github.io/jsgantt-improved/

Reproduced this error with Chrome and Firefox

**Comment by mariohmol** [comment]
thanks!
