### ISSUE TITLE
Need highlighted features.

### ISSUE THREAD

**Issue by saiHemanthGitHub** [jsGanttImproved/jsgantt-improved#170]
![gantt](https://user-images.githubusercontent.com/12952098/54983165-458b6300-4fd2-11e9-998a-3b4d61a330cc.PNG)

Hi, Team needs highlighted features shown in the screenshot. How to achieve...?

**Comment by mariohmol** [comment]
What is this? can u exaplain more?

**Comment by saiHemanthGitHub** [comment]
How can I show highlighted values in the major header like **start day dd/mm/yyyy - end day dd/mm/yyyy**

currently there is no option for **vDayMajorDateDisplayFormat** in header like **start day dd/mm/yyyy - end day dd/mm/yyyy**

**Comment by mariohmol** [comment]
there is a lot of formats..  https://github.com/jsGanttImproved/jsgantt-improved/blob/master/src/draw.ts#L85 

This is a week view? `vWeekMajorDateDisplayFormat`
