### ISSUE TITLE
Error when scrolls the page.

### ISSUE THREAD

**Issue by saiHemanthGitHub** [jsGanttImproved/jsgantt-improved#171]
**Describe the bug**
Getting error when the page height differentiates. Find in the attached screenshot.

**To Reproduce**
1. Install the dependency.
2. Run the page.
3. Open inspect element and apply scrolling top to bottom or bottom to top.
4. See error.

**Expected behavior**
The error
![error-1](https://user-images.githubusercontent.com/12952098/54985583-0f041700-4fd7-11e9-88be-a6f74dff7417.PNG)
 should not come.

**Screenshots**

**Comment by mariohmol** [comment]
this was fixed already.. please check the latest version
