### ISSUE TITLE
Error in the documentation examples

### ISSUE THREAD

**Issue by andreabonadei** [jsGanttImproved/jsgantt-improved#175]
In the documentation examples some vEvents names are wrong. For example the events for the click on startDate and endDate should be "start" and "end" not "startdate" "enddate".

**Comment by mariohmol** [comment]
can u fill a PR ou show in what files/lines?

**Comment by andreabonadei** [comment]
I've created the PR #177

**Comment by mariohmol** [comment]
thank you
