### ISSUE TITLE
Grid & Chart Headers

### ISSUE THREAD

**Issue by StephenMulryan** [jsGanttImproved/jsgantt-improved#176]
At the moment when you scroll down the page the Grid & Chart header disappear out of view.

I would like if the Grid & Chart headers were floating and followed down the page as you scrolled.

**Comment by mariohmol** [comment]
Thanks..its a good idea..

**Comment by mariohmol** [comment]
@viniciusrc15 will give a try

**Comment by mariohmol** [comment]
Thanks again @viniciusrc15 .. 
@StephenMulryan  check this out on 2.1.16

**Comment by StephenMulryan** [comment]
Hi @mariohmol. I downloaded release 2.1.2 to try test this. I updated the css and js files but could not find any difference in the header. Is there something extra needed for this?

**Comment by mariohmol** [comment]
@StephenMulryan  isnt working on latest version?

**Comment by StephenMulryan** [comment]
@mariohmol No, when I tried the latest version in May it was fixing the headers by default and there was no obvioud options to turn it on.

However I went ahead and implemented it. 

![image](https://user-images.githubusercontent.com/3050277/61958006-6bdd0180-afb8-11e9-84d2-b3263aa310ba.png)

**Comment by mariohmol** [comment]
I see.. because we did this in the version of this month... if u have any comments about it would be great =)
