### ISSUE TITLE
Undefined link after click

### ISSUE THREAD

**Issue by evanega3** [jsGanttImproved/jsgantt-improved#178]
Hello everyone, nice Gantt Chart you have here.

I am having the following issue:

When a link inside the table is clicked, after the click event it changes the TaskName to **undefined**.

![WhatsApp Image 2019-04-01 at 15 15 37](https://user-images.githubusercontent.com/968968/55356825-39e7e280-5491-11e9-82b8-4b187a65da90.jpeg)

**What I'm generating from my api**
```
g.AddTaskItem(new JSGantt.TaskItem(309, 
"<a href='http://test.te/admin/dashboard/review-task/309'>Photographer1</a>", 
"06/30/2018", 
"09/10/2018", 
"gtaskblue", 
"", 
0, 
"Trey Gonzales", 
0, 
0, 
82, 
0, 
0, 
"", 
"", 
g));
```

It should remain unchanged after the click. This issue does not happen on the grouped tasks. Only the ones that do not have anything below them.

**Comment by mariohmol** [comment]
I guess related to task name be a html? try justa  text please

**Comment by evanega3** [comment]
Yes sir, is there any way that the task name remain as HTML, it is more intuitive than the pLink inside the tooltip.

Thank you.

**Comment by mariohmol** [comment]
in this example we have a title with a html.. what is different in your side?  can u provide a data json to reproduce this error? https://jsganttimproved.github.io/jsgantt-improved/demo.html

**Comment by mariohmol** [comment]
i gotcha.. when is not editable. bug confirmed

**Comment by evanega3** [comment]
Exactly, do you know how can I do a quick fix on this?

**Comment by mariohmol** [comment]
found.. will be fixed in 1 hour.. if u can retest

**Comment by evanega3** [comment]
Of course, thank, let me know as soon as you push the new versiojn.

Thank you so much!

**Comment by mariohmol** [comment]
check v 2.1.12

**Comment by mariohmol** [comment]
sorry.. use v 2.1.13
