### ISSUE TITLE
Question: Multiple Bars Same Row

### ISSUE THREAD

**Issue by Belleye** [jsGanttImproved/jsgantt-improved#183]
Hi, I'm hoping to use jsgantt-improved for historical asset time usage mapping. Is it possible to have multiple bars on the same row with sub-minute level precision? Any code snippets would be great :) I'm a noob.

**Comment by mariohmol** [comment]
minute level precision in the chart? it will be needed to code a new view.. we have the smallest day, but should be needed to have a hour or minute level..

**Comment by sgjoshi** [comment]
Will be useful to show multiple statuses of any task, e.g. started, expected delay, delayed etc on single bar with different colors 
![image](https://user-images.githubusercontent.com/14075258/62266276-4f701780-b445-11e9-865b-3592e537fca8.png)

**Comment by mariohmol** [comment]
Hi @sgjoshi , we have that showing in the grid.. a little different than this layout.. but we have like start/end bar and planstart/planend bars

**Comment by armxm** [comment]
Hi  @sgjoshi, u can set pgroup as 2 in the parent element and get this result
<img width="778" alt="example" src="https://user-images.githubusercontent.com/11752588/67008868-44f02080-f10c-11e9-9e35-1d601961d640.PNG">

**Comment by mariohmol** [comment]
Thanks @armxm  Good catch!
