### ISSUE TITLE
Number of rows limitation

### ISSUE THREAD

**Issue by PedroPinto-GV** [jsGanttImproved/jsgantt-improved#185]
Hello.

I'm experiencing a problem when loading more than 1030 rows on the chart.
Some tasks don't get correctly grouped to it's parent and then they get dependent of a group instead of another task. I've verified the json data created and the group and dependent relation is correct.

**Comment by mariohmol** [comment]
Could u provide a data.json or a codepen with this example?

**Comment by PedroPinto-GV** [comment]
I´ve attached a data.json file with the data we pretend to view in the gantt chart.
There's another attachment were you can view what happens at a certain point of the chart.
1. A task that "looks" like a group but is a task and is not a task of that group.
2. A dependent line is getting out of a group and only tasks have dependents.

Thanks for your attention.
![Gantt](https://user-images.githubusercontent.com/25327084/55864457-7217b100-5b74-11e9-8c63-df4f57310b7e.png)
[data.json.zip](https://github.com/jsGanttImproved/jsgantt-improved/files/3062836/data.json.zip)

**Comment by PedroPinto-GV** [comment]
Hello again.

Have you managed to replicate this issue?
Is it planned a correction?
Thank you for your attention.

**Comment by sunnyqijoinhand** [comment]
hi , there is a wrong value for pGroup for this task
{
        "pID": 1160,
        "pName": "<span title='Tube Connection - a definir'><strong>Tube Connection</strong></span> <a target=\"_blank\" onclick=\"window.open(&quot;/smarti/apps/BeOnGO/Intervencoes/Intervencoes.php?po=window&amp;id=26112624&quot;);\" title=\"Tube Connection - a definir\" style=\"cursor: pointer; text-decoration: underline; color: rgb(8, 61, 141);\">a definir</a>",
        "pStart": "",
        "pEnd": "",
        "pPlanStart": "2019-02-02",
        "pPlanEnd": "2019-02-02",
        "pClass": "gtaskred",
        "pLink": "",
        "pMile": 0,
        "pRes": "",
        "pComp": "0",
        "pGroup": 1,  <!-----here must be 1 to show a group
        "pParent": 1156,
        "pOpen": 1,
        "pDepend": "1159",
        "pCaption": "0%",
        "pCost": "",
        "pNotes": "",
        "IdInterventionPrecedent": "26112352"
    }

**Comment by PedroPinto-GV** [comment]
Thanks for you answer @sunnyqijoinhand, but this task is not a group. 
The group has pId 1156 and tasks have pId between 1157 and 1160.
The pId 1156 has pGroup set to 1.

**Comment by sunnyqijoinhand** [comment]
exports.AddTaskItem = function(value) {
                var vExists = false;
                for (var i = 0; i < this.vTaskList.length; i++) {
                    //if (this.vTaskList[I].getID() == value.getID()) { 
                    if (this.vTaskList[i].getOriginalID() == value.getOriginalID()) { 
			console.log( value.getOriginalID()+" dudu " );
                        i = this.vTaskList.length;
                        vExists = true;
                    }
                }
                if (!vExists) {
                    this.vTaskList.push(value);
                    this.vProcessNeeded = true;
                }
            };

**Comment by sunnyqijoinhand** [comment]
I think 
getID --- auto give a id to task by JSGantt
getOriginalID --- this is from your json

**Comment by sunnyqijoinhand** [comment]
if you DO NOT want to modify exports.AddTaskItem,
please modify:
exports.hashKey = function(key) {
                //return this.hashString(key) % 10000;
                return '_ID_' + key;
};
1675077039 - pID=1156 doesn't show because 
getID() returned a same value as other tasks.

**Comment by sunnyqijoinhand** [comment]
@mariohmol  please update code:
 exports.hashString  to avoid generate DUPLICATED getID(). Thanks!

**Comment by mariohmol** [comment]
@PedroPinto-GV : In the data you sent there is a child for 1672807494 called Tube connection... 
 so with value `"pParent": 821,`


```
 {
    "pID": 825,
    "pName": "<span title='Tube Connection - a definir'><strong>Tube Connection</strong></span> <a target=\"_blank\" onclick=\"window.open(&quot;/smarti/apps/BeOnGO/Intervencoes/Intervencoes.php?po=window&amp;id=26113111&quot;);\" title=\"Tube Connection - a definir\" style=\"cursor: pointer; text-decoration: underline; color: rgb(8, 61, 141);\">a definir</a>",
    "pStart": "",
    "pEnd": "",
    "pPlanStart": "2019-02-02",
    "pPlanEnd": "2019-02-02",
    "pClass": "gtaskred",
    "pLink": "",
    "pMile": 0,
    "pRes": "",
    "pComp": "0",
    "pGroup": 0,
    "pParent": 821,
    "pOpen": 1,
    "pDepend": "824",
    "pCaption": "0%",
    "pCost": "",
    "pNotes": "",
    "IdInterventionPrecedent": "26112606"
  },
```

**Comment by sunnyqijoinhand** [comment]
@mariohmol  , this issue was:
exports.hashString(key) returned only a 4-bit number such as 6689 based on original pID from JSON.
when user's json pID is 1156 , this value may be same with others. 
exports.AddTaskItem will check getID() , the task pID=1156 is not added to Task List.

**Comment by sunnyqijoinhand** [comment]
I changed code below in my js:
            exports.hashString = function(key) {
                if (!key) {
                    key = 'default';
                }
                key += '';
                var hash = 1234567;
                for (var i = 0; i < key.length; i++) {
                    if (key.charCodeAt) {
                        hash = (hash << 8) + hash + key.charCodeAt(i);
                    }
                    hash = hash & hash;
                }
                return (hash >>> 0);
            };
            exports.hashKey = function(key) {
                return this.hashString(key) % 1000000 + 90000000;
            };

**Comment by mariohmol** [comment]
@sunnyqijoinhand i dont remember now but we had to add the has in the past to solve.. i don think u can change the hash that way http://www.cse.yorku.ca/~oz/hash.html

**Comment by sunnyqijoinhand** [comment]
TASK 1675077039 was not shown because getID() returns a value same with others.
After modify exports.hashString(key) , it is displayed correctly.
So , make a PR to upgrade exports.hashString(key) to avoid this issue?
![Snip20190429_2](https://user-images.githubusercontent.com/49417816/56899070-20a07900-6ac5-11e9-9a74-9dca6765676e.png)

**Comment by mariohmol** [comment]
Ths big data example is confusing.. he did a print about `1672807494`

**Comment by mariohmol** [comment]
i did a version `2.1.18`  without the `% 10000` .. it will make big numbers..

**Comment by sunnyqijoinhand** [comment]
@mariohmol  that's great!

**Comment by sunnyqijoinhand** [comment]
exports.hashString = function(key) {
if (!key) {
key = 'default';
}
key += '';
var hash = 1234567;
for (var i = 0; i < key.length; i++) {
if (key.charCodeAt) {
hash = (hash << 8) + hash + key.charCodeAt(i);
}
hash = hash & hash;
}
return (hash >>> 0);
};
exports.hashKey = function(key) {
return this.hashString(key) % 1000000 + 90000000;
};

========================
you will get a task id : 9xxxxxxxx .  this id will be large enough  for users. :-)

**Comment by mariohmol** [comment]
u cannot change this var `hash` it will loose the hash distribution

**Comment by PedroPinto-GV** [comment]
@mariohmol . Yes, task pId-825 has pParent 821 but in the picture i've send is the task below my point (1).
The other Tube Connection child (my point (1)) is in the wrong place.
I believe it could has relation with @sunnyqijoinhand answers.
I will try version 2.1.18 and will give feedback.
Thanks.

**Comment by sunnyqijoinhand** [comment]
@mariohmol 
var hash = 5381;
I don't understand why hash must be 5831.

**Comment by mariohmol** [comment]
https://stackoverflow.com/questions/10696223/reason-for-5381-number-in-djb-hash-function

**Comment by PedroPinto-GV** [comment]
I'm failing to find the version 2.1.18 to download.
Can you help.
