### ISSUE TITLE
I modified the codes , add a new parameter Height to control GANTT's height.

### ISSUE THREAD

**Issue by sunnyqijoinhand** [jsGanttImproved/jsgantt-improved#188]
jQuery 1.8+

var g = new JSGantt.GanttChart( DIV , 'day', 500);

jsgantt.css - modified :
vertical-align:top -----> for left and right alignment 
....
font-size:12px always ---> Chrome will not display small text

![Snip20190424_1](https://user-images.githubusercontent.com/49417816/56632838-5214e100-668e-11e9-9c02-c6c548c6bd6b.png)
![Snip20190424_2](https://user-images.githubusercontent.com/49417816/56632839-54773b00-668e-11e9-9cf1-1ba234e3d4ef.png)
![Snip20190424_3](https://user-images.githubusercontent.com/49417816/56632842-55a86800-668e-11e9-8396-574e5d7060b1.png)
![Snip20190424_4](https://user-images.githubusercontent.com/49417816/56632844-5640fe80-668e-11e9-801a-c102935990e3.png)

 less than 12px.

jsgantt.js - modified : 
scroll left , right will be scrolled too.
scroll right , left will be scrolled too.

[Modified_Version_jsgantt.zip](https://github.com/jsGanttImproved/jsgantt-improved/files/3110557/Modified_Version_jsgantt.zip)

**Comment by sunnyqijoinhand** [comment]
Please consider remove all IE6,7,8 codes from css and js.

**Comment by mariohmol** [comment]
would be awesome if u could put this in a Pull Request.. fork.. clone to your computer.. push the changes and create a new pull request..

**Comment by mariohmol** [comment]
Hi.. waiting a PR for this changes =)
