### ISSUE TITLE
add onclick event to all tasks

### ISSUE THREAD

**Issue by nasari123** [jsGanttImproved/jsgantt-improved#192]
hello, as the titler said. i want to add onclick event to all tasks (like the mouseover that shows the tooltip), when i click i do some codes.
 and i added it by customising the main js file (jsgantt.js), and my modification cannot move to a custom file (custom.js for example).

those are the line I've added in diffirent locations:
//define the id of the task
this.getOriginalID = function () { return _id; };
//add the id of the task as a parametre on the addTooltipListeners()
events_1.addTooltipListeners(this, this.vTaskList[i].getTaskDiv(), vTmpDiv2, this.vTaskList[i].getOriginalID);
//now to the event
exports.addListener('click', function (e) { 
        //mycode
    }, pObj1);

is there any other way  to add that event in a custom file?

**Comment by sunnyqijoinhand** [comment]
jQuery:

$('#divID div.gchartcontainer div.gmainleft table>tbody>tr.gname').on('click',function(){
});

**Comment by sunnyqijoinhand** [comment]
if you want to add some custom event on clicking 'task name' , 'start' , 'end' ...
please use like this
g.setEvents({
		taskname:function(task){
			console.log(task);
			alert( task.getID() + ' , ' + task.getName() + ' , ' + task.getOriginalID() );
		}
		,start:function(task){
			$('#OSgwnGantt2>div.gchartcontainer>div.gmainright').scrollLeft( task.getStartX()-50 );
		}
		,planstart:function(task){
			$('#OSgwnGantt2>div.gchartcontainer>div.gmainright').scrollLeft( task.getStartX()-50 );
		}
		,end:function(task){
			$('#OSgwnGantt2>div.gchartcontainer>div.gmainright').scrollLeft( task.getEndX()-50 );
		}
		,planend:function(task){
			$('#OSgwnGantt2>div.gchartcontainer>div.gmainright').scrollLeft( task.getEndX()-50 );
		}
});

**Comment by mariohmol** [comment]
Its a good a idea to make a PR implementing events for tasks...

**Comment by nasari123** [comment]
@sunnyqijoinhand  am not able to use jquery on this case,  so i used just javascript. 
el = document.querySelector("#GanttChartDIV div.gchartcontainer div.gmainleft table>tbody>tr.gname");
            el.onclick = function myFunction(){
                g.setEvents({
                    taskname:function(task){
                        alert(task);
                    console.log(task.getID());
                    alert( task.getID() + ' , ' + task.getName() + ' , ' + task.getOriginalID() );
                    }
                   
                    });
            }
i know that am selecting just the first element , but nothing is happen.
if a added an alert in the first line of myFunction it works.
el.onclick = function myFunction(){
                alert("task");
                g.setEvents({
                    taskname:function(task){
                        alert(task);
                    console.log(task);
                    alert( task.getID() + ' , ' + task.getName() + ' , ' + task.getOriginalID() );
                    }
                   
                    });
            }
.. but the g.setEvents() not.

**Comment by sunnyqijoinhand** [comment]
Hi , 
please use as below:

var g = new JSGantt.GanttChart( document.getElementById('myDIV') , 'day');
g.setEvent({
		taskname:function(task){
			console.log(task);
			alert( task.getID() + ' , ' + task.getName() + ' , ' + task.getOriginalID() );
		}
		,start:function(task){
			$('#OSgwnGantt2>div.gchartcontainer>div.gmainright').scrollLeft( task.getStartX()-50 );
		}
		,planstart:function(task){
			$('#OSgwnGantt2>div.gchartcontainer>div.gmainright').scrollLeft( task.getStartX()-50 );
		}
		,end:function(task){
			$('#OSgwnGantt2>div.gchartcontainer>div.gmainright').scrollLeft( task.getEndX()-50 );
		}
		,planend:function(task){
			$('#OSgwnGantt2>div.gchartcontainer>div.gmainright').scrollLeft( task.getEndX()-50 );
		}
});

**Comment by sunnyqijoinhand** [comment]
var g = new JSGantt.GanttChart( document.getElementById('myDIV') , 'day');
g.setEvent({
    taskname: myFunc
    ,start:myFunc
    ,planstart: myFunc
    ,end: myFunc
    ,planend: myFunc
});
function myFunc(task){
    //task is object for this TASK you click
    console.log(task);
    alert( task.getID() + ' , ' + task.getName() + ' , ' + task.getOriginalID() );
}

**Comment by sunnyqijoinhand** [comment]
> Its a good a idea to make a PR implementing events for tasks...

@mariohmol  Task row click event will conflict with task name event, start event ....
I prefer to use g.setEvent() to provide different events for columns click event in task rows.

**Comment by nasari123** [comment]
you forget an 's' to g.setEvent  =====> g.setEvents
&& it workes man, thanks a lot @sunnyqijoinhand

**Comment by mariohmol** [comment]
i was thinking about clicking in the task bar.. we dont have events binded for that yet

**Comment by nasari123** [comment]
> i was thinking about clicking in the task bar.. we dont have events binded for that yet

@mariohmol  my first code is doing that. 
I added a click event bellow the mouseover event (show tool tip) and it works :)

**Comment by mariohmol** [comment]
make a PR?

**Comment by nasari123** [comment]
i write the line that i've added in the main file 
----------------

//define the id of the task
this.getOriginalID = function () { return _id; };

//print the id os the task in the tool tip
this.newNode(vTaskInfo, 'span', null, 'gTtTitle', pTask.getOriginalID());

//add the id of the task as a parametre on the addTooltipListeners()
events_1.addTooltipListeners(this, this.vTaskList[i].getTaskDiv(), vTmpDiv2, this.vTaskList[i].getOriginalID);

//now to the event
exports.addListener('click', function (e) {
//##mycode is open a modal template to edtit task/sync new data with the database
}, pObj1);


----------------





these is the new file , if you want to compare with yours, or to know where to add those lines 

[jsgantt_modified.zip](https://github.com/jsGanttImproved/jsgantt-improved/files/3128002/jsgantt_modified.zip)

**Comment by abeeching1** [comment]
Are there any examples anywhere of setting an onClick event to a task bar? I have it working on the row columns but haven't been able to work out setting an event on the task bar itself. Thanks

**Comment by mariohmol** [comment]
reopen to have this in a PR? @nasari123

**Comment by samCoder0123** [comment]
**[Urgent]**

Hello Experts,

Is there any way to achieve the taskbar click event in angular ?
Any help would be really appreciated.

**Comment by mishellscripts** [comment]
On click events are working fine on the cells but I need to register the click event on the taskbar itself. Is this possible? Thanks in advance

**Comment by mariohmol** [comment]
Hi, now on version 2.7.0 that will trigger the event for headers as well!
