### ISSUE TITLE
A bug if the starting and ending dates contain 00 minutes.

### ISSUE THREAD

**Issue by abvas** [jsGanttImproved/jsgantt-improved#194]
It does not correctly show if the dates are specified with minutes equal to 00. For example, the start is May 01, 2019 00:00 and end May 02, 2019 00:00. This is exactly one day. But the table shows - 2 days, and the strip takes two days - May 1 and May 2. It also writes 48 hours, not 24 hours. How can this be fixed?
![Image 10](https://user-images.githubusercontent.com/47285364/57221768-fe4cb500-7008-11e9-9838-4e2f22acff66.png)
![Image 20](https://user-images.githubusercontent.com/47285364/57221776-0a387700-7009-11e9-8f68-8f378743c620.png)

**Comment by mariohmol** [comment]
fixed on 2.1.19! thaks
