### ISSUE TITLE
Safari in Mac OS X cannot get correct Right-Offset

### ISSUE THREAD

**Issue by sunnyqijoinhand** [jsGanttImproved/jsgantt-improved#195]
Please see screenshot and my "demo.html"
I think something wrong in getOffset(). The reason may be "numeric precision".
I checked getOffset(), it contains many add/sub/mul/div operations.

![Snip20190507_1](https://user-images.githubusercontent.com/49417816/57266681-9c935600-70af-11e9-8197-53a23298f39e.png)
![Snip20190507_2](https://user-images.githubusercontent.com/49417816/57266684-9c935600-70af-11e9-96da-3fd0ae2a301a.png)

**Comment by sunnyqijoinhand** [comment]
[demo.html.zip](https://github.com/jsGanttImproved/jsgantt-improved/files/3150507/demo.html.zip)

**Comment by sunnyqijoinhand** [comment]
IE/Firefox/Chrome OK. Safari cannot display right offset when more than 365 days between mindate and maxdate

**Comment by mariohmol** [comment]
well.. this is very odd.. in just safari as well.. and u right.. its a hard fix

**Comment by mahmad2504** [comment]
I observe same on windows Chrome and Opera but same data appears ok on Firefox and IE

**Comment by mariohmol** [comment]
@nidu does that fix u did with margin fixes this?

**Comment by nidu** [comment]
It shouldn't i can see Day format on the screen, but it affected only month and quarter

**Comment by nidu** [comment]
It shouldn't i can see Day format on the screen, but it affected only month and quarter

**Comment by mariohmol** [comment]
Hi guys, there is a new released which we changed a lot of things.. maybe its fixed now?

feel free to reopen if needed
