### ISSUE TITLE
Is there no way to add additional columns to the tooltip?

### ISSUE THREAD

**Issue by JulLeuverink** [jsGanttImproved/jsgantt-improved#196]
Is there a way i can show my additional taskheaders + data in the tooltip?

I've tried to solve this myself and it was pretty easy to add the additional headers. Now i'm struggling to add the object data too.

`pTask` in `exports.createTaskInfo` does not contain the additional columns.

**Comment by mariohmol** [comment]
the idea of tooltip its to show an example.. you should make your own..

but i guess could have a better way to handle this.. like passing a HTML template and use this when render the tooltip..

**Comment by mariohmol** [comment]
added the a feature to custom template for tooltip.. check demo
