### ISSUE TITLE
The current date line shows today - 2 days (and the bars: today - 3 days) 

### ISSUE THREAD

**Issue by savobalac** [jsGanttImproved/jsgantt-improved#197]
The blue vertical current date line shows today - 2 days, not today.

All bars are either 2 or 3 days 'early', e.g. a task of 13 May (on tool tips) shows as either 10 or 11 May.

Image taken today 10 May 2019:

![image](https://user-images.githubusercontent.com/4201816/57535631-83520a00-733a-11e9-9f19-98a2c28cc2df.png)

Dates for one task from my app:

![image](https://user-images.githubusercontent.com/4201816/57535756-be543d80-733a-11e9-8573-5718c08e7866.png)

Windows 10 Home, Chrome Version 74.0.3729.131 (Official Build) (64-bit)

I downloaded the latest version of jsGanttImproved (2.1.2)

**Comment by nasari123** [comment]
have you tried with a different browser? or tried an early version of jsgantt-improved ?
check you system date is set correctly.
would provide the json data ?

**Comment by mariohmol** [comment]
tested it ou on current version and is working pretty good.. reopen fi u still with this
