### ISSUE TITLE
sortTasks function goes infinite loop when sort a task with specific pID

### ISSUE THREAD

**Issue by MichelleZhang** [jsGanttImproved/jsgantt-improved#198]
**Describe the bug**

sortTasks function goes infinite loop when sort a task with a sepcific pID: 5cddcd414cedfd00019f87c3

**To Reproduce**
1. I define only one task in the gantt diagram to debug this issue
rawTask's id is '5cddcd414cedfd00019f87c3'.
const task = {
        'pID': rawTask.id,
        'pName': rawTask.name || rawTask.id,
        'pStart': this.parseHqTime(rawTask.startTime),
        'pEnd': this.parseHqTime(rawTask.endTime),
        'pStatus': status,
        'pClass': this.REQUEST_TASK_STATUS[status],
        'pMile': 0,
        'pRes': '',
        'pGroup': isGroup,
        'pParent': 0,
        'pOpen': 0,
        'pCaption': '',
        'pRawData': rawTask
      };
2. Add line to print out the sortIdx
for (let j = 0; j < sortArr.length; j++) {
    for (let i = 0; i < pList.length; i++) {
      if (pList[i].getID() == sortArr[j].getID()) {
        console.log("set pList " + pList[i].getID() + " to " + sortIdx);
        pList[i].setSortIdx(sortIdx++);
        sortIdx = sortTasks(pList, pList[i].getID(), sortIdx);

      }
3. You will see it go to infinite loop even though itself is the only task.

**Expected behavior**
It should not loop forever when there is no loop in the topology. One and only one task is defined.

**Screenshots**

**Desktop (please complete the following information):**
iOS
Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mariohmol** [comment]
Hi thanks for reporting this.. do u have a suggestion to fix this issue?

**Comment by mariohmol** [comment]
fixed!
