### ISSUE TITLE
Add support for JSON import and export

### ISSUE THREAD

**Issue by eduardomourar** [jsGanttImproved/jsgantt-improved#20]

**Comment by russelmadere** [comment]
I need this for work. I forked the project and will look at implementing a set of functions to handle a json load.

**Comment by eduardomourar** [comment]
Russel, thanks! This will be an excellent improvement.

**Comment by russelmadere** [comment]
Question - How far back do we support IE? Do we want to support IE 5? I ask because I'm looking at the for ... in statement and it is only supported in IE 6 and later.

**Comment by eduardomourar** [comment]
we can work with IE 11+, because all others microsoft stopped giving support this year.

**Comment by russelmadere** [comment]
Excellent. My code handles back to IE 6. I just created a pull request. If I did it wrong, let me know., please.

**Comment by charliehavanese** [comment]
Hello, not quite a pull request but here is a snippet of how I successfully use json data to create the gantt chart. I hope this is useful to someone.

ps: Thank you Eduardo and Ricardo for creating this :)

        function GetGanttJsonDataFromDatabase() {
            $.ajax({
                type: 'POST',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                url: '/GetGanttJsonFromDatabase',
                async: false,
                success: function (data) {
                    var jsonData = JSON.parse(data.d);
                    DrawProjectGantt(jsonData);
                },
                error: function () {
                    alert("Error processing -GetGanttJsonDataFromDatabase");
                } 
            }); 
        };
        function DrawProjectGantt(jsonData) {
            var g = new JSGantt.GanttChart(document.getElementById('GanttFile'), 'month'); //new gantt div
            if (g.getDivId() != null) {
                g.setShowTaskInfoLink(1); // Show link in tool tip (0/1)
                g.setDayMajorDateDisplayFormat('dd mon');
                g.setDateTaskDisplayFormat('dd month yyyy HH:MI');
                g.setUseToolTip(1);
                g.setUseFade(1);
                g.setUseMove(1);
                g.setUseRowHlt(1);
                g.setUseSort(0);
                g.setShowRes(0);
                g.setShowDur(0);
                g.setShowComp(0);
                g.setShowStartDate(0);
                g.setShowEndDate(0);
                g.setShowEndWeekDate(1);
                g.setShowDeps(1);
                g.setShowTaskInfoRes(1);
                g.setShowTaskInfoDur(1);
                g.setShowTaskInfoComp(1);
                g.setShowTaskInfoStartDate(1);
                g.setShowTaskInfoEndDate(1);
                g.setShowTaskInfoLink(1);
                g.setShowTaskInfoNotes(1);
                g.setShowSelector("Top");
                g.setFormatArr("Week", "Month", "Quarter");
                g.setCaptionType('Duration');  
                g.setScrollTo("Today");
                g.setUseSingleCell(0);
                g.setLang("en");
                var pParent, pID, pName, pStart, pEnd, pClass, pLink, pMile, pRes, pComp, pGroup, pParent, pOpen, pDepend, pCaption, pNotes, pGroup;
                for (i = 0; i < jsonData.length; i++) {
                    pParent = 0;
                        pID = jsonData[i].pID;
                        pName = jsonData[i].pName;
                        pStart = jsonData[i].pStart
                        pEnd = jsonData[i].pEnd;
                        pClass = jsonData[i].pClass;
                        pComp = jsonData[i].pComp;
                        pLink = jsonData[i].pLink;
                        pMile = jsonData[i].pMile;
                        pRes = jsonData[i].pRes;
                        pNotes = jsonData[i].pNotes;
                        pGroup =0;
                        g.AddTaskItem(new JSGantt.TaskItem(pID, pName, pStart, pEnd, pClass, pLink, pMile, pRes, pComp, pGroup, pParent, pOpen, pDepend, pCaption, pNotes, g));
                };
                g.Draw();
            } else {
                alert("Error, unable to create Gantt Chart");
            };
        };

**Comment by dannythomas13** [comment]
So happy to see this improvement being considered but I am confused as to whether this is to be done or has been completed? If it does work, can I ask within which version? Thanks

**Comment by mariohmol** [comment]
included in v2
