### ISSUE TITLE
The bigdata.json file cannot be applied.

### ISSUE THREAD

**Issue by JimmyCheng** [jsGanttImproved/jsgantt-improved#201]
**Describe the bug**

**To Reproduce**
1. Go to jsgannt-improved folder.
2. Change the file demo.html, line 130, value="./fixes/bigdata.json"
3. Start the server, run 'node server.js'.
4. Try page: http://localhost:8081/demo.html  there is no response.

**Expected behavior**
It should display the gantt chart.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version: >v2.02

**Comment by mariohmol** [comment]
Hi.. i'm so sorry.. its a bug on last version that a console.log was there @jonathanlassen  check it out

**Comment by mariohmol** [comment]
fixed on v2.2.2 .. thanks

**Comment by mariohmol** [comment]
that is still taking a long time to render.. that was better before.. have to investigate..

**Comment by jonathanlassen** [comment]
data.json is rendering fine, but bigdata.json is hanging on my local machine. I never started the application with that file in the past, however, so don't have anything to compare to. Investigating...

**Comment by mariohmol** [comment]
yeah.. i just remove the extra console logs that we left on code last time ....kkkk 

but i dont know why.. this was rendering before.. i will reopen for future investigation

**Comment by jonathanlassen** [comment]
What is the expected render time for bigdata.json? Just tried bigdata.json with a number of previous versions (so far back to 2.0.9), and they also do not render the chart, although some info is being logged to the console. Is there a version where bigdata.json is successfully rendering to a chart?

**Comment by mariohmol** [comment]
check it out https://github.com/jsGanttImproved/jsgantt-improved/pull/190

**Comment by mariohmol** [comment]
maybe around 2.1.16

**Comment by jonathanlassen** [comment]
fixed in #205; also, we have added a demo file that uses the bigdata.json dataset
