### ISSUE TITLE
The Gannt chart row height is not configurable.

### ISSUE THREAD

**Issue by JimmyCheng** [jsGanttImproved/jsgantt-improved#202]
**Is your feature request related to a problem? Please describe.**
In the jsgantt.css file, update line 781, change the table height to other value. e.g. 60px.
then the dependency line in the graph is not aligned.

**Describe the solution you'd like**
When the row height is changed, the dependency line should be aligned.

**Additional context**
I have a solution, will provide a pull request.

**Comment by mariohmol** [comment]
Hi!

Thanks for that! I could not reproduce this issue.. I made this smaller and it looks good.. can u please send a picture or steps to make it?

**Comment by JimmyCheng** [comment]
Steps to reproduce:
1. in the root folder of jsgantt-improved, run `node server.js`
2. visit http://localhost:8081/demo.html, now the row height is normal. ( i am using data.json.)
3. go to file docs/jsgantt.css line 780, update to `height: 60px !important;`
4. refresh http://localhost:8081/demo.html

the dependency arrow is not aligned.
![Screen Shot 2019-06-05 at 10 41 48 am](https://user-images.githubusercontent.com/1861821/58922547-babba700-877e-11e9-8cb7-17f33f0e31e5.png)

In my pull request, the dependency arrow start location is calculated based on the row location, not the cell.

**Comment by mariohmol** [comment]
gotcha!! released on v2.2.3. Thank you!!
