### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by derpflanz** [jsGanttImproved/jsgantt-improved#208]
When copying the code verbatim, I get an error "lang not found". Easily fixed by changing it into "en_US".

Also, the example seems to have the issue that the task always ends 'today' instead of the date given.

**Comment by mariohmol** [comment]
Hi there!! What task have this issue? cant find this issue here..

**Comment by derpflanz** [comment]
In this example: https://github.com/jsGanttImproved/jsgantt-improved/blob/develop/Documentation.md

The AddTaskItemObject method has pGroup set to 1, making it a group, without tasks, causing it to run until "today".

**Comment by mariohmol** [comment]
Hi.. you mean this https://github.com/jsGanttImproved/jsgantt-improved/commit/f678a1087a3869c01e38a9ec49ecb2d47da73745 ? 

thanks
