### ISSUE TITLE
Bug in task complete calculation

### ISSUE THREAD

**Issue by mahmad2504** [jsGanttImproved/jsgantt-improved#21]
Group task is showing wrong work progress, probably because weighted average is not considered while computing the completion progress. It would be good if there is option of just showing what user has mentioned in XML file and bypass the implemented 
![untitled](https://cloud.githubusercontent.com/assets/15646324/21861229/c3f6359a-d855-11e6-8aa0-a9f03c6e5e86.png)
group completion logic

**Comment by eduardomourar** [comment]
@mahmad2504, thanks for your input. We have released v1.7.5.3 with a weighted average. Let us know if that was what you had in mind.

**Comment by mahmad2504** [comment]
Great.
