### ISSUE TITLE
vScrollTo: 'today' not working

### ISSUE THREAD

**Issue by capricorn05** [jsGanttImproved/jsgantt-improved#210]
**Describe the bug**
when I use vScrollTo: 'today', it does not have any effect on the position of the scroll and consequently does not move to the correct location

**To Reproduce**

**Expected behavior**
when using vScrollTo: 'today' the expected behaviour is that the scroll moves to the location where the blue line is displayed for the current day.

**Screenshots**

**Desktop (please complete the following information):**
 - chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mariohmol** [comment]
released on v2.4.1
