### ISSUE TITLE
Bad method name

### ISSUE THREAD

**Issue by Adrish-ASProg** [jsGanttImproved/jsgantt-improved#211]
In task.js / task.ts files, there's no "setComp" method but two "setCost", where one of them is updating "vComp" attribute

`this.setCost = function (pCost) {
    vComp = parseInt(document.createTextNode(pCost).data);
};`

**Comment by mariohmol** [comment]
awesome man!! u found a lot of things to improve here!!

could u please put this in the PR as well?

**Comment by mariohmol** [comment]
#214  fixed on this PR... right?
