### ISSUE TITLE
Issues with Dates

### ISSUE THREAD

**Issue by Adrish-ASProg** [jsGanttImproved/jsgantt-improved#212]
When providing invalid date using edit mode or "setStart" / "setEnd" methods, an error is thrown but the date is still set as NaN/NaN/NaN, preventing from switching to edit mode after that. (Constantly throwing "RangeError: Invalid time value")

Moreover, the function "getMinDate" (and I guess getMaxDate too) throws error when no tasks are left in the chart, as the method is directly using vTasklist[0] without checking before if it exists, so we can not empty the chart.
Edit: I just see `if (this.vTaskList.length > 0)` in the Draw method, but this is before using `processRows` method which can delete some tasks so this do not prevent from calling getMinDate and getMaxDate

**Comment by mariohmol** [comment]
thanks!!

could u provide a PR so we can merge in?

**Comment by mariohmol** [comment]
this is on #215 as well.. right?

**Comment by mariohmol** [comment]
released on 2.2.7

**Comment by Adrish-ASProg** [comment]
Yep, #215 should fix this

**Comment by mariohmol** [comment]
do u use angular / react or vue? because when changes here its needed to update the other components

**Comment by Adrish-ASProg** [comment]
Yes i'm using Angular, what do you mean by "the other components" ?
Are the changes needed in docs/*.js files ? If so I'll make changes here too, sry

**Comment by mariohmol** [comment]
dont need the docs.. cause i need to push the new version to npm anyway..

check this component https://github.com/jsGanttImproved/ng-gantt

**Comment by Adrish-ASProg** [comment]
I don't understand what you mean
Changes I made should affect ng-gantt the same way it affects other components, as they depend on the same 'jsgantt-improved' package, doesn't it ?

**Comment by mariohmol** [comment]
Yes... but... i have to update the jsgantt-improved in 2 files:

* https://github.com/jsGanttImproved/ng-gantt/blob/master/package.json#L32
* https://github.com/jsGanttImproved/ng-gantt/blob/master/ng-gantt/package.json#L21

increase the ng-gantt version and then publish on npm again
