### ISSUE TITLE
Updating Completion

### ISSUE THREAD

**Issue by Adrish-ASProg** [jsGanttImproved/jsgantt-improved#213]
When using edit mode and updating completion, `setCompVal` method is used and so vCompVal property is updated.
But `getCompStr` and `getCompVal` method are first checking the "vComp" value and so updated values are not taken into account if "vComp" is set.

**Comment by mariohmol** [comment]
Hi!! Thanks again..

to make it clear.. could u provide a json data to test and maybe a PR with this solution/

**Comment by mariohmol** [comment]
from #214 , will be on next release!! thans again

**Comment by Adrish-ASProg** [comment]
No, wait for another PR, this bug is not fixed with the PR I sent, it's only fixing #211 yet

**Comment by mariohmol** [comment]
This is #215 right?

**Comment by mariohmol** [comment]
2.2.7
