### ISSUE TITLE
What is the most effective way to clear the gantt chart?

### ISSUE THREAD

**Issue by dchaboya** [jsGanttImproved/jsgantt-improved#218]
I'm aware of removing individual task items with RemoveTaskItem, but is there a way to more effectively clear the gantt and start fresh? Or, do you recommend to iterate over the task list and remove the items one-by-one? If removing items by iterating over the list, at what point do you call the Draw method? After each removal, or when all items have been removed?

Great work by the way!

**Comment by mariohmol** [comment]
Thats a good question.. we dont have a method to clear all .. I just did this (ClearTasks)

Another option is removing one by one and call draw at the end is an option.

Another option is to make the gant again .. like  `g = new JSGantt.GanttChart(document.getElementById('GanttChartDIV'), 'day');`

This change is released on v2.2.8

**Comment by Adrish-ASProg** [comment]
I can't get the ClearTasks method to work, is it working for you ?

First, I have to add `this.ClearTasks = task_1.ClearTasks;` in draw.js to have access to the method. But no tasks are cleared when I use it, as the "draw" method is testing if the length of the list is > 0

However tasks are deleted by "processRow" method if they have their property "vToDelete" to true
So `vTaskList = [];` in the "ClearTasks" method shouldn't be replaced by something like `this.vTaskList.map(task => task.setToDelete(true));` ?

**Comment by mariohmol** [comment]
You are totally right! To make it more easier to test.. i've included in the demo page a button to clear tasks...

released on 2.2.9

thanks!

**Comment by dchaboya** [comment]
Thanks pointing out that issue, Adrish.  I was trying to figure out why it wasn't working as expected. Thanks mariohmol for you prompt response.
