### ISSUE TITLE
Ability to update pClass and pNotes

### ISSUE THREAD

**Issue by nidu** [jsGanttImproved/jsgantt-improved#220]
**Is your feature request related to a problem? Please describe.**
Ability to update task class and notes parameters for a task. There are getters but no setters.

**Describe the solution you'd like**
I call `.setClass`, `.setNotes` for a task, then call `g.Draw()` and class and notes are updated in the view.

**Describe alternatives you've considered**

1. Recreating entire component.
2. Manually updating class and notes after each `Draw` call.

**Comment by mariohmol** [comment]
good catch..implemented on release 2.2.11
