### ISSUE TITLE
Ability to pass callback after to call after drawing is complete

### ISSUE THREAD

**Issue by nidu** [jsGanttImproved/jsgantt-improved#221]
**Is your feature request related to a problem? Please describe.**
I have to customize styling for some rows. In my case i have to paint first level rows in green and second level rows in yellow. Since classes for `tr`s do not include information about the level - i'm doing some postprocessing after calling `Draw`. It works fine until i switch the format (Day -> Week e.g.). It calls `Draw` which invalidates my customization and i can't intercept this moment easily.

**Describe the solution you'd like**
Add following options:

- `vBeforeDraw()` - called in the top of `Draw`. I don't really need it at the moment, but it would be good for consistency.
- `vAfterDraw()` - called in the bottom of `Draw`. Here i can call all my customization.

**Describe alternatives you've considered**

1. Monitor DOM mutations which is complicated and potentially bad for performance
2. Patch library to add level classes to `tr`s like `gtasklevel-1`, `gtasklevel-2`, ...
3. Maintain format switch outside the component

**Comment by mariohmol** [comment]
good idea.. released on 2.2.10
