### ISSUE TITLE
Facility to add custom elements to the chart

### ISSUE THREAD

**Issue by nidu** [jsGanttImproved/jsgantt-improved#222]
**Is your feature request related to a problem? Please describe.**
My data set has task start/end date and a deadline. Deadline is just a single date. I'd like to show this deadline somehow. Easiest option i can think of is to draw a long vertical line for deadline.

First i tried to use plan dates for it, but

1. Plan start date doesn't make sense here and only brings confusion. I can set it to start date, but if start date = plan start date - plan bar is not shown. 
2. If task is not started - i have nothing to show.

**Describe the solution you'd like**
I'd like to add custom elements to the chart somehow. As the problem is quite generic, i guess solution can be pretty generic too.

Add some helper methods to `GanttChart` like `dateToX(date: Date|string)` to get X coordinate for a given date inside a `getChildRow()` instance (i think `getOffset` method does something similar). With this way using new `afterDraw` callback i can draw all my lines after Draw call. Since these elements can be outside the time range `[getMinDate(), getMaxDate()]`, it would also require adding optional parameters like `vMinDate` and `vMaxDate`.

**Describe alternatives you've considered**

1. Literally add new entity type *Deadline*, but it sounds too inflexible.
2. A kind of middle ground is to add task parameter like `pAdditionalElements: {startDate, endDate, className}[]` (not a very good name). `startDate` and `endDate` will determine position and width (one of them can be null, width is 1 in this case). Height can also be passed as a parameter, but can be configured with CSS also. For my case here i can just pass a single item.
3. Do it with plan dates. Start plan date would be some arbitrary but common date and plan end date would be the deadline.

**Comment by mariohmol** [comment]
Thank you.. released on v2.3.0
