### ISSUE TITLE
Does your gantt chart allow you to move tasks on a gantt chart?

### ISSUE THREAD

**Issue by it19862** [jsGanttImproved/jsgantt-improved#225]
**Is your feature request related to a problem? Please describe.**
Not

**Describe the solution you'd like**
1. Does your gantt chart allow you to move tasks on a gantt chart?
 
If "yes".
2. Will the start of the dependent task be moved?

![01](https://user-images.githubusercontent.com/18245828/61182853-f715d900-a641-11e9-988e-40a8a286ff40.gif)

**Describe alternatives you've considered**
Not

**Additional context**
Not

**Comment by mariohmol** [comment]
no sorry... there is a issue for that #117
