### ISSUE TITLE
Pass vTooltipTemplate as a callback optionally

### ISSUE THREAD

**Issue by nidu** [jsGanttImproved/jsgantt-improved#227]
**Is your feature request related to a problem? Please describe.**
If the task is in progress (< 100%) - end date may be unknown, but there's no way to show it. If i pass empty end date - current date is used. The display is correct on the chart, but label in tooltip may be misleading. It shows something like "End Date: <current_date>", while task is not actually finished yet.

Unfortunately i don't think tooltip template would allow conditional logic.

Please advise how this situation can be handled otherwise.

**Describe the solution you'd like**
For me if task is not complete - don't show end date in the tooltip.

However some workflows would consider current behavior correct. So maybe we could pass callback `vTooltipTemplate(task): HTML` or `vTooltipTemplate(task, node)`?

**Describe alternatives you've considered**
1. Remove end date from the tooltip
2. Manually control tooltip

**Comment by mariohmol** [comment]
Thank you!! I will merge both today.. test and give feedvack =)

**Comment by mariohmol** [comment]
is this on #224 or #223 ?

**Comment by nidu** [comment]
Neither, working on it

**Comment by nidu** [comment]
What do you think would be the better way?

`vTooltipTemplate(pTask): string` is the simplest option and it allows using template syntax, since returned string can be processed.

`vTooltipTemplate(pTask, node): void` is more powerful as it allows async initialization and i suppose some other features.

**Comment by mariohmol** [comment]
to be honest.. i do not want to work in this tooltip.. i think everyone will have his own tooltip layout.. 

Here we have a `Custom Tooltip Template` already

https://jsganttimproved.github.io/jsgantt-improved/demo.html

**Comment by nidu** [comment]
But do i understand correctly that template is static? For example i'd like to hide end date for the tasks that are still in progress.

**Comment by mariohmol** [comment]
uhmmmmmm i see.. we need to pass a callback function that returns an html..

**Comment by mariohmol** [comment]
i could not understand this `vTooltipTemplate(pTask, node): void is more powerful as it allows async initialization and i suppose some other features.`

but i think we should have something like :
on `createTaskInfo` we check if `vTooltipTemplate` its a function or a string.. and use one or another way.. what u think?

**Comment by nidu** [comment]
Yeap, that's the simplest and good enough option.

About async - potentially you can populate `node` with some `Loading...` HTML, then call server method, and then replace `node` HTML with data from server since you have a reference to the node. Don't know how useful it actually is.

Similar option for `vTooltipTemplate(pTask)` would be to return `string | Promise<string>`.

**Comment by mariohmol** [comment]
yeah.. i think a return promise that gives the final html ts the best option!!

thanks =)

**Comment by nidu** [comment]
I didn't notice before - tooltip is created when the component is created. This way i don't think supporting promise makes a lot of sence as it may eagerly produce a lot of requests.

I've implemented the change meanwhile ([here](https://github.com/nidu/jsgantt-improved/commit/acbdf00396b95dc5f79e11e788799f965e95ffc0)), but it requires more work to support updating tooltip after promise is done while the tooltip is open.

**Comment by mariohmol** [comment]
in my mind this is easy.. i can try to make something here to show u..

**Comment by nidu** [comment]
Ok, it was easy, but how do you think - what to show while tooltip is loading? Just "Loading..." or don't show tooltip at all or allow custom content somehow? Maybe i'm overthinking it a bit, but still would like to have a sound feature

**Comment by mariohmol** [comment]
We could have a Loading text there.. but coming from the i18n.  i think its ok

**Comment by mariohmol** [comment]
released on 2.3.1  

thanks @nidu
