### ISSUE TITLE
Issue when number of tasks are greater than 255

### ISSUE THREAD

**Issue by mahmad2504** [jsGanttImproved/jsgantt-improved#231]
When i added more than 255 tasks in gantt, last task is duplicated and appears as extra in the gantt chart. (Only in chart view )

I commented cloneNode and it looks ok now. 

else if (this.vFormat == 'day') {
                //vTmpTBody.appendChild(vTmpRow.cloneNode(true));
            }

**Comment by mariohmol** [comment]
I dont see this ...

if u change the data input to this `./fixes/data255.json` on https://jsganttimproved.github.io/jsgantt-improved/demo.html you will see..

if this is specific for your data.. put the data here so we can test it out

**Comment by antonio-silva** [comment]
Last task is duplicated, this happens in the day format. Even in the demo there is that mistake

**Comment by mariohmol** [comment]
you are right!

fixed on next release =)

**Comment by mariohmol** [comment]
published on v2.3.5
