### ISSUE TITLE
setShowEndWeekDate() still shows the weekend

### ISSUE THREAD

**Issue by minasm** [jsGanttImproved/jsgantt-improved#232]
Hello there,

I am trying to hide weekends from the chart on Day view but could not manage it. Found a closed ticket here (marked as duplciatate) but that did not help asll well.

_setShowEndWeekDate()_ is not removing weekend days but it just makes a strange view. Wondering if I am missing any configuration settings.
![image](https://user-images.githubusercontent.com/2103447/61879725-8ac19200-aeeb-11e9-8612-a237b3daffc1.png)

![image](https://user-images.githubusercontent.com/2103447/61879857-c2303e80-aeeb-11e9-83cf-081dbe097210.png)

My settings are as follows;

```
                    g.setCaptionType('Complete');
                    g.setQuarterColWidth(36);
                    g.setUseSort(0);
                    g.setDateTaskDisplayFormat('day dd month yyyy');
                    g.setDayMajorDateDisplayFormat('mon yyyy - Week ww');
                    g.setWeekMinorDateDisplayFormat('dd mon');
                    g.setShowTaskInfoLink(1);
                    g.setShowEndWeekDate(1);
                    g.setUseSingleCell(10000);
                    g.setRowHeight(40);
                    g.setShowRes(1);
                    g.setScrollTo('today');
                    g.setFormatArr('Day', 'Week', 'Month', 'Quarter');
```

**Comment by mariohmol** [comment]
I think u got this wrong:

|_setShowEndWeekDate():_|Controls whether the major heading in "Day" view displays the week end-date in the appropriate format (see [below](#user-content-display-date-formats)), defaults to 1 (show date)|



We dont have a feature to hide weekends in the chart.. but is a good idea

**Comment by mariohmol** [comment]
I did a implementation of this on 2.3.3 .. not quite sure if is 100% working.. but in a fast test i did here is working.. 
bests

**Comment by minasm** [comment]
@mariohmol thanks a lot for the fast response! Works like a charm. And you are right, this is a nice addition to the library.
One thing though, on Day view the `.tinytext div` has a font size of 2px.

**Comment by mariohmol** [comment]
yes... i was testing around because now the space is very small.. any suggestion for size that would not break?

**Comment by mariohmol** [comment]
i did a change to fit the max space possivel.. is on new version
