### ISSUE TITLE
Allow only-planned tasks

### ISSUE THREAD

**Issue by agarciacalvo** [jsGanttImproved/jsgantt-improved#234]
**Is your feature request related to a problem? Please describe.**
In my app I have only-planned tasks (with Plan start date and Plan end date, and without actual dates) and launched tasks (with actual and Plan dates). However, when I add to a task only the Plan dates, the component assumes those as the actual dates.

**Describe the solution you'd like**
I would like the actual dates to appear empty and the task rectangle to appear as planned ones.

**Describe alternatives you've considered**
This might be a breaking change instead of a bug. Perhaps we would need a flag to activate this behavior. In order to propose a PR, I really wouldn't know where to start.

**Additional context**
Look at "Test 5" task:
![issue](https://user-images.githubusercontent.com/18212145/61950851-78a92780-afaf-11e9-8cec-af0051fb9615.png)

**Comment by mariohmol** [comment]
Good point.. plan dates are new and we didnt think about having just with plan dates.. people usually do normal dates..

but is a good idea to have this and should be too hard to fix

**Comment by mariohmol** [comment]
released on 2.3.6

thanks for the idea

**Comment by agarciacalvo** [comment]
Awesome! Thank you so much for your work.

One more little thing. Would it also be possible to show empty actual dates in the grid?

![CF8F3B66-B59D-404D-A937-2FAEDCDF0C7F](https://user-images.githubusercontent.com/18212145/61990969-44cf1000-b04a-11e9-83e5-53383b3ef6ca.jpeg)

**Comment by sgjoshi** [comment]
You said 

> released on 2.3.6

but I am unable to find it on releases page, it shows 2.2.11 as latest

**Comment by agarciacalvo** [comment]
Here you are https://www.npmjs.com/package/jsgantt-improved

**Comment by sgjoshi** [comment]
Thank you
