### ISSUE TITLE
column order editing

### ISSUE THREAD

**Issue by mateusbrazza** [jsGanttImproved/jsgantt-improved#236]
I want to change the column order and assuming I created 2 columns with AdditionalHeaders

today is like this

Start date | End date | newcolumn1 | newcolumn2

I want it to be like this
newcolumn1 |Start date | End date | newcolumn2

**Comment by mariohmol** [comment]
cool.. thats a good idea.. have a solution for this.. will be good that i 'm going to separate more the draw.ts that is too big

**Comment by mariohmol** [comment]
Hi.. released version 2.4.0 .. that has part of the refactor of draw function.. so now we have the option

```
|_setColumnOrder:_ |Set order of the columns that will be displayed, the default value is : `[  'vShowRes','vShowDur','vShowComp','vShowStartDate','vShowEndDate','vShowPlanStartDate','vShowPlanEndDate','vShowCost','vAdditionalHeaders','vShowAddEntries']` }|
````

**Comment by mateusbrazza** [comment]
thanks for the help but in case of a
	AdditionalHeaders: {project: {title: 'Project'},  Effort: {title: 'Effort'} },
how could you leave them apart
example
['Project','Start Date','End Date',','Effort']

Thanks a lot for the help

**Comment by mateusbrazza** [comment]
I don't know if this is the best practice but I got it
AdditionalHeaders: {
				project: {title: 'Project'},
                                pStart:{title:'Start Date'},
				pEnd:{title:'End Date'},
		                Effort: {title: 'Effort'}
                              },

**Comment by mariohmol** [comment]
awesome... good idea.. if that worked.. lets keep like that.. but indeed.. i didnt make something to order aditional headers differente from the other columns
