### ISSUE TITLE
Plan End date

### ISSUE THREAD

**Issue by sgjoshi** [jsGanttImproved/jsgantt-improved#237]
I am trying to set Start, End, PlanStart and PlanEnd dates. However I found that if End is replaced by PlanEnd. 
e.g. Start date of task is 8-May-2019, End date is 8-May-2019 and I give PlanStart as 10-May-2019 and PlanEnd as 12-May-2019, then the chart shows Start date as 8-May-2019 and it shows 12-May-2019 as date for both End Date and Plan End Date

Please help me

**Comment by mariohmol** [comment]
i could not reproduce here.. u mean the bar on chart show wrong or the table?

i submitted a new data testing this on https://jsganttimproved.github.io/jsgantt-improved/demo.html

Check the`Test Plan End`

**Comment by mariohmol** [comment]
If you still have this.. please submit a data as an example or some print screens. Feel free to reopen

**Comment by sgjoshi** [comment]
Data I used is this:
```
g.AddTaskItem(new JSGantt.TaskItem(
    6, '6: Part-1 (Grid 7 to 10)', '2019-05-08', '2019-05-08', 'ggroupblack', '', 0, '--', 100, 1, 5, 1, '', 'Part-1 (Grid 7 to 10)', 'Some Notes text', g,0,'2019-05-10','2019-05-11' ));
```
So I am passing pStart and pEnd both as '2019-05-08' and then passing pPlanStart as '2019-05-10' and pPlanEnd as '2019-05-11'. But when chart is rendered, it shows both pEnd and pPlanEnd as '2019-05-11' (In the left pane). I noticed that if planStart and planEnd are not passed then it uses values of pStart and pEnd

**Comment by sgjoshi** [comment]
Further observation:
I removed planned dates from group task and added to child task. As said, for child task dates are correct. However, if my child task's planned end date is not shown in parent (group). I havent passed planned end date to parent, so it shows pEnd as planned end date (2019-05-08) but my child task has planned end date 2019-05-11 and I think it should rollup to parent

**Comment by sgjoshi** [comment]
Please help me understand this

**Comment by mariohmol** [comment]
Hi.. yes.. the group wil

**Comment by sgjoshi** [comment]
Mario, thanks for reopneing, I was unable to do so. I am still not getting 2 bars when planned and actual dates are different. I expected to see 2 overlapping bars

**Comment by sgjoshi** [comment]
I am still struggling with tooltip when planned and actual dates are different. In such case, I get a new bar on top of task bar, so hovering over it doesnt trigger tooltip for task. Please help.

**Comment by mariohmol** [comment]
indeed.. fixing here..

**Comment by mariohmol** [comment]
the tooltip in plan task is now working on 2.4.5 =)

**Comment by sgjoshi** [comment]
Thanks a lot @mariohmol ! It works great.
Actually I didnt take the new version, I am using older one and had made lot of changes for my requirements. Since the repo shows changes you made, I directly made those in jsgantt.js and it works great! Thank you so much!

**Comment by mariohmol** [comment]
all right! if you have PR with some ideas.. would be great

**Comment by Nikhilbk1705** [comment]
@sgjoshi Hello do you able to solve the overlapping of bars for planstart and planend with start and end..if yes please share the solution

**Comment by Nikhilbk1705** [comment]
> Mario, thanks for reopneing, I was unable to do so. As for planned dates different from actuals, I see overlapping bars for nongroup tasks, but not for group tasks. One more observation: When I am hovering over "gplan", the tooltip doesnt show up Can you please help on this?

have u able to find the solution for this issue? Currently i am facing the same issue

**Comment by jf-ashishyadav** [comment]
@mariohmol Hi Can we set dueDatebase  chart bar green and red

**Comment by mariohmol** [comment]
Yes, you can color bars by due date status using the `pClass` parameter. Compute the class in your own code before adding each task, then pass it as the 5th argument to `TaskItem`:

```js
function getBarClass(endDate) {
  const now = new Date();
  return new Date(endDate) < now ? 'gtaskred' : 'gtaskgreen';
}

g.AddTaskItem(new JSGantt.TaskItem(
  1, 'My Task', '2024-01-01', '2024-03-01',
  getBarClass('2024-03-01'),  // pClass — red if overdue, green if on time
  '', 0, '', 0, 0, 0, 1
));
```

Built-in color classes available for `pClass`:
- `gtaskblue`, `gtaskred`, `gtaskgreen`, `gtaskyellow`, `gtaskorange`, `gtaskpurple`
- `ggroupblack` (for group/parent tasks)

You can also define your own CSS class and jsgantt will apply it to the bar element.

There is no automatic due-date coloring built in — you compute the class yourself based on your logic and pass it in. This gives you full control over the coloring rules.
