### ISSUE TITLE
Custom top level styles can mess with headers

### ISSUE THREAD

**Issue by nidu** [jsGanttImproved/jsgantt-improved#238]
**Describe the bug**
Some style like for example `body > * { display: flex; }` can cause incorrect scrollbar size calculation, which leads to incorrect widths for some elements like headers when vertical scrollbar is enabled.
It's related to recent fixed header support.

**To Reproduce**
1. Add style `body > * { display: flex; }`
2. Set `vTotalHeight` to small enough value to enable vertical scroll.

**Expected behavior**
Headers must be visible.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 73

**Additional context**

**Comment by mariohmol** [comment]
Thanks @nidu !

released on 2.4.2
