### ISSUE TITLE
Easy way to add additional columns in the table

### ISSUE THREAD

**Issue by munjalpatel** [jsGanttImproved/jsgantt-improved#24]
What would be an easy way to add additional columns in the table view? If someone can point me into the right direction, I can implement this on my own and then create a pull request.

**Comment by GeekSilva97** [comment]
Has anyone got it?

**Comment by Jasin2069** [comment]
Agree, This would be very useful to have.

**Comment by solvix** [comment]
@munjalpatel - Were you able to get an answer on this one?  I, too, would do it myself ... just want to check with others to see if they've done it themselves -OR- if our team has already created the functionality.  Thanks, Brent

**Comment by mariohmol** [comment]
Hi, 

this is a good feature to have, thanks for suggestion.

Released in v2.0.6 

How to use

```
g.setOptions({
vAdditionalHeaders: { // Add data columns to your table
      category: {
        title: 'Category',
translate: 'myKey' // this can be used to have a column name with different languages, provide the translate key in custom translations 
      },
      sector: {
        title: 'Sector'
      }
   } 
})
```

and data with those columns:

```
{
    "pID": 1,
    "pName": "Define Chart API",
    "pStart": "",
    "pEnd": "",
    "pPlanStart": "",
    "pPlanEnd": "",
    "pClass": "ggroupblack",
    "pLink": "",
    "pMile": 0,
    "pRes": "Brian",
    "pComp": 0,
    "pGroup": 1,
    "pParent": 0,
    "pOpen": 1,
    "pDepend": "",
    "pCaption": "",
    "pNotes": "Some Notes text",
    "category": "Planning",
    "sector": "CMO"
  },
  {
    "pID": 11,
    "pName": "Chart Object",
    "pStart": "2018-06-20",
    "pEnd": "2018-07-20",
    "pClass": "gmilestone",
    "pLink": "",
    "pMile": 1,
    "pRes": "Shlomy",
    "pComp": 100,
    "pGroup": 0,
    "pParent": 1,
    "pOpen": 1,
    "pDepend": "",
    "pCaption": "",
    "pNotes": "",
    "category": "Executive",
    "sector": "CEO"
  }
```

**Comment by do-borisov** [comment]
@mariohmol, Not sure, but I've checked that too and made the changes which were related there into the task.ts. Still not succeeding to add just a simple additionalHeader manually via the object.

**Comment by mariohmol** [comment]
I did this in a demo:  https://jsganttimproved.github.io/jsgantt-improved/demo.html

Try to run this example uncommenting this 
https://github.com/jsGanttImproved/jsgantt-improved/blob/develop/docs/index.js#L107

Here is working.. shows the task with aditional column category as 'test'

**Comment by mariohmol** [comment]
test with release 2.1.2

**Comment by do-borisov** [comment]
@mariohmol awesome. Able to pass additionalHeader -> values now via the TaskItemObject. Thanks.
