### ISSUE TITLE
Translation for Japanese

### ISSUE THREAD

**Issue by mariohmol** [jsGanttImproved/jsgantt-improved#241]
**Is your feature request related to a problem? Please describe.**

A user has asked a translate for japanese

https://github.com/jsGanttImproved/ng-gantt/issues/11

**Describe the solution you'd like**

We need to have a translation like the others here

* https://github.com/jsGanttImproved/jsgantt-improved/blob/master/src/lang.ts

**Comment by mariohmol** [comment]
@yeheshuah help us =)

**Comment by yeheshuah** [comment]
> @yeheshuah help us =)

https://github.com/jsGanttImproved/jsgantt-improved/pull/249

**Comment by mariohmol** [comment]
Thank you @yeheshuah , released on  v 2.4.8
