### ISSUE TITLE
Additional data to be passed on to jsgantt.js

### ISSUE THREAD

**Issue by sgjoshi** [jsGanttImproved/jsgantt-improved#242]
Question: I wanted to pass some additional data variables to jsgantt.js file. Idea is to pass data such as "task start delayed by n days", "task end delayed by n days" etc. Based on this data I want to add additional DIV elements inside the gantt bar with different colors. How to do this?

**Comment by nidu** [comment]
Hi, just pass additional attributes when creating a task. You can later access them via `task.getDataObject().yourCustomAttr`. See example [here](https://github.com/jsGanttImproved/jsgantt-improved/blob/master/docs/index.js#L198), which also adds custom HTML to the chart based on the custom attribute.

**Comment by sgjoshi** [comment]
Thanks nidu, but I dont want additional columns in left pane.  Just want to pass data so that I can put different colors in the bar

**Comment by nidu** [comment]
It doesn't create new column in the table, see example [here](https://jsganttimproved.github.io/jsgantt-improved/demo.html) - there's no Deadline column.

**Comment by sgjoshi** [comment]
Yes, I can see that there is no column for deadline, but I was unable to understand how you passed data for deadline.

**Comment by nidu** [comment]
See [json data](https://jsganttimproved.github.io/jsgantt-improved/fixes/data.json) - there's `deadline` attribute for some tasks.

**Comment by sgjoshi** [comment]
ok, got that. but I still have a problem. call me a noob, but I am getting data from database and then in a loop I am doing `g.AddTaskItem(new JSGantt.TaskItem(......)` so this will take data for predefined variables and I dont know how to add custom values here

**Comment by nidu** [comment]
Look up example in [readme](https://github.com/jsGanttImproved/jsgantt-improved/blob/master/README.md) for `g.AddTaskItemObject` - notice two custom attributes there - `category` and `sector`

**Comment by nidu** [comment]
Look up example in [readme](https://github.com/jsGanttImproved/jsgantt-improved/blob/master/README.md) for `g.AddTaskItemObject` - notice two custom attributes there - `category` and `sector`

**Comment by sgjoshi** [comment]
Right, problem is in my case I am not passing key:value pairs. Your example here also shows additional columns but I think thats due to the vAdditionalHeaders. Looks like I will have to remove new JSGantt.TaskItem from the code and use key:value syntax. Thanks a lot, I will try that now

**Comment by sgjoshi** [comment]
Yes, that worked !! Thank you so much @nidu !! I think now I can proceed with what I intend to do.

**Comment by mariohmol** [comment]
Great guys! Is anything we can make better in the docs to make it clear?

**Comment by sgjoshi** [comment]
Well, I would say these things are not clear in the documentation. It talks about additional headers but doesnt say that we can pass additional data without adding columns. So maybe we can add a small section like "Passing additional data" or something like that. If I may, I would suggest a detail review of docs.

**Comment by mariohmol** [comment]
what you mean passing data without addig columns? because if u pass the object with the data.. he will accept but is not going to show...

or you are talking specific for `deadline` column

**Comment by sgjoshi** [comment]
Yes that was with reference to deadline.

What I mean is this: Document should mention that additional headers setting adds columns to table on the left side, but if its omitted and some custom variables are are added to `g.AddTaskItem` then those can be accessed inside the JS code using `task.getDataObject().yourCustomAttr`. I didnt know this till @nidu guided me through.
also, `new JSGantt.TaskItem` takes only fixed set of variables and you cant add custom variables here since the data is passed simply as values and not as key:value pairs.

**Comment by mariohmol** [comment]
I see.. so I guess the fix here is to show the column deadline the same it shows the same for other columns like planstartdate / startdate, enddate / planenddate

**Comment by nidu** [comment]
@mariohmol i don't think this is the case here. If i understand correctly documentation doesn't make it clear that you can add custom data which won't appear in the data table (my first understanding was the same). So a section in documentation would suffice: on passing custom data and on either adding a column for it or just using it to draw something on the chart. For example a simple walkthrough on this example with `deadline` that we have on the demo page.

**Comment by sgjoshi** [comment]
I agree with @nidu but will just want to add that document should make it clear that we can pass custom data with additional columns to show it, as well as without adding columns.

**Comment by mariohmol** [comment]
can u make a PR with a suggestion of doc about it @sgjoshi ?

**Comment by sgjoshi** [comment]
Well, if you mean Pull Request, I tried it but was unable to add one.

**Comment by mariohmol** [comment]
You can fork the repo.. push the change to your repo and create a pull request here.. if u have issues with that we can help you out

**Comment by sgjoshi** [comment]
I will need some help. Here is what I understand:

- I fork the repository
- I update documentation (tell me which files, only readme.md ?)
- then create PR

is that right?

**Comment by mariohmol** [comment]
yes!

**Comment by sgjoshi** [comment]
@mariohmol - I have updated Documentation.md and created a PR. Please review.
