### ISSUE TITLE
Help on how to print label in taskbar

### ISSUE THREAD

**Issue by juniorschen** [jsGanttImproved/jsgantt-improved#244]
Like this?

![Sem título](https://user-images.githubusercontent.com/46031261/63022763-f60edc00-be79-11e9-85cc-12db9f4d5a1d.png)

**Comment by mariohmol** [comment]
thats a new idea.. should not be difficult to implement..

we need to change this line to receive another value

https://github.com/jsGanttImproved/jsgantt-improved/blob/master/src/draw.ts#L656

**Comment by mariohmol** [comment]
use v.2.4.6  and include in your task the property like `"pBarText": "ex. bar text",`

**Comment by shradhakarnawat** [comment]
It still doesn't work. I am using the latest version.

**Comment by mariohmol** [comment]
Check this example:
https://jsganttimproved.github.io/jsgantt-improved/docs/demo.html

In the `Test Bar Task`, we have the label in middle.

Can you provide a code that shows this error?
