### ISSUE TITLE
We have the possibility to use the minutes filter in a customizable way (1 minute, 15 minutes, 30 minutes)

### ISSUE THREAD

**Issue by juniorschen** [jsGanttImproved/jsgantt-improved#245]
Like this?

![Capturar](https://user-images.githubusercontent.com/46031261/63096544-92051a00-bf44-11e9-9886-b42c8ffeca66.PNG)

**Comment by mariohmol** [comment]
thanks for the example layout.. this is dup to #144

**Comment by BondJamesBond700** [comment]
Thanks Mariohmol

Can you tell how to view/test filter in the demo https://jsganttimproved.github.io/jsgantt-improved/docs/demo.html

**Comment by mariohmol** [comment]
what u mean about test filter?
