### ISSUE TITLE
Incorrect date format in Japanese localization

### ISSUE THREAD

**Issue by yeheshuah** [jsGanttImproved/jsgantt-improved#250]
- In case of English localization, there is correct date format.
![English localization (correct)](https://user-images.githubusercontent.com/4284139/63664858-a3330e00-c803-11e9-9702-cd23c5613eb7.png)
- In case of Japanese localization, currently there is incorrect date format.
![Japanese localization (correct)](https://user-images.githubusercontent.com/4284139/63664927-f6a55c00-c803-11e9-9743-4bc02097c97e.png)
In above case, correct date format should be "2019年8月26日（月）" (yyyy年m月d日（DAY）)

**Comment by Nickyg56** [comment]
Which view format are you seeing this label (day, week, month)?

**Comment by yeheshuah** [comment]
> Which view format are you seeing this label (day, week, month)?

year month day (wekday)

**Comment by yeheshuah** [comment]
I. Am. Sorry.

I can use HourMajorDateDisplayFormat to set format.
![image](https://user-images.githubusercontent.com/4284139/63997092-70a55000-cb38-11e9-939a-7c0490160318.png)
