### ISSUE TITLE
Access original ID

### ISSUE THREAD

**Issue by dbugit** [jsGanttImproved/jsgantt-improved#254]
I need to access the original id.
Is there a way or is there a way to revert the hashkey created?

Thank you,
AP

**Comment by mariohmol** [comment]
`getOriginalID()` should work.. have you seen this?

**Comment by mariohmol** [comment]
nice!

can you share the drag n drop?

what u mean about add attributes? we have this right `vAdditionalHeaders`?

**Comment by mariohmol** [comment]
hi... you can fill a new issue if u would like to keep working on this.. thanks

**Comment by dbugit** [comment]
Sorry... but didn't had time before...
I will open a new issue..

Thanks
