### ISSUE TITLE
Add click event and info on elements of connection between bars to determine from => to direction.

### ISSUE THREAD

**Issue by nikola-kljaic** [jsGanttImproved/jsgantt-improved#256]
**Problem**
Problem that I have is when I click on connection I need on click action to to lunch dialog.
Also I need depending on connection direction from => to to find items in data structure.
Currently there is no info on connection elements what they connect, there are from classes but there is no to classes
Current connectiion in IDs and classes
complete_177622 => glineh gDepId177622 gDepFSArw ("no connection to") complete_177623 
![image](https://user-images.githubusercontent.com/21431881/64851069-f506d100-d616-11e9-98a1-b8ea25e38718.png)

**Solution**
In order to implement this dialog I will need attached click event and info from and to bar on connection.
Purposed solution:
complete_177622 => glineh gDepId177622 gNextDepId177623  gDepFSArw => complete_177623

**Alternatives solution that I tried**
I was able to attach click event on after draw but problem is that I can not get to which bar connection is pointing.

Thoughts?

**Comment by mariohmol** [comment]
Hi.. there is already a click event for the task right?

**Comment by nikola-kljaic** [comment]
Hi, 
As I know it there is an hover event on and I think click as well.
BTW I created PR that adds this option.
I tried to submit it but could not do it.
It said I do not have permissions to create PR for this repo.

**Comment by mariohmol** [comment]
thats very weird.. this is public should work!

I created this, see if that is what you done:

https://github.com/jsGanttImproved/jsgantt-improved/pull/261

**Comment by nikola-kljaic** [comment]
Aaa nice. Thanks :)
I do not know but could not create it.

**Comment by mariohmol** [comment]
awesome!
to be sure..so what we have working in this PR?

**Comment by nikola-kljaic** [comment]
So, on connections (dependencies) I added data Ids and click event.
So I can when connection is clicked to extract classes and parse it.
When I have info about start and end of connection.
I can find this data in my data structure and in my case open modal and do some actions on modal.
I have also added after and before draw on connection level.
So if needed I can react on this events.

**Comment by mariohmol** [comment]
this is already merged right? if u need more .. please reopen  =)
