### ISSUE TITLE
Lib is producing warnings in Angular prod build.

### ISSUE THREAD

**Issue by nikola-kljaic** [jsGanttImproved/jsgantt-improved#257]
**Bug description**
Warning appears in console when jsgantt-imporved is build on Angular app.
WARNING in Invalid property name '        filter' at 12237:2. Ignoring.

WARNING in Invalid property name '        filter' at 12245:2. Ignoring.

WARNING in Invalid property name '        filter' at 12252:2. Ignoring.

WARNING in Invalid property name '        filter' at 12259:2. Ignoring.

WARNING in Invalid property name '        filter' at 12267:2. Ignoring.

WARNING in Invalid property name '        filter' at 12275:2. Ignoring.

**To Reproduce**
1. install npm jsgantt-improved --save in your angular project
2. run ng b --prod
3. see errors.

**Expected behavior**
Warnings should not appear when build is finished.

**Screenshots**
![image](https://user-images.githubusercontent.com/21431881/65441191-46d70480-de2a-11e9-836d-229527b2e3bd.png)
![image](https://user-images.githubusercontent.com/21431881/65441098-1ee7a100-de2a-11e9-9bb7-ca13eaa51762.png)

**Desktop (please complete the following information):**
 - Windows 10 OS X64, version 1703, build 15063.1988
 - node version 10.16.0
 - npm version 6.9.0

**Comment by mariohmol** [comment]
if u can open the final JS and see what are those lines about..

**Comment by nikola-kljaic** [comment]
it is on console I do not think I can expand them.

**Comment by mariohmol** [comment]
Thanks!

Are you sure it appears when u add this module?

because i revisited here and we have some code like `pTool.style.filter = 'alpha(opacity=0)';` , but this is supported.. so i dont know if this warning makes any sense at all  

here is that it real exists https://www.w3schools.com/jsref/prop_style_filter.asp

**Comment by nikola-kljaic** [comment]
Yeah, I think it started when I added it.
Let me check tomorrow and will report back.
Also if I find time will test with that commented to see what is going on.

**Comment by mariohmol** [comment]
can u please test this component for angular?

https://github.com/jsGanttImproved/ng-gantt

if the warning still there.. please open a issue on ng-gantt project!

thanks
