### ISSUE TITLE
Bug in endDateTime

### ISSUE THREAD

**Issue by juniorschen** [jsGanttImproved/jsgantt-improved#258]
**Describe the bug**
If the end time is midnight (00:00:00), the chart goes to the end of the other day.

Ex: start: 2019/09/25 22:00:00
end: 2019/09/26 00:00:00

The graph goes to what would be the 27th at 00:00:00.

![Sem título1](https://user-images.githubusercontent.com/46031261/65609432-2623c180-df86-11e9-944a-8c2c834861f3.png)

![Capturar2](https://user-images.githubusercontent.com/46031261/65609439-29b74880-df86-11e9-997e-cb0672bd83fc.PNG)

Expect: 
![Sem título2](https://user-images.githubusercontent.com/46031261/65609446-2cb23900-df86-11e9-9bdd-ce6c4da282ec.png)

![Capturar3](https://user-images.githubusercontent.com/46031261/65609450-2fad2980-df86-11e9-8e23-398704f80392.PNG)

**Comment by mariohmol** [comment]
Hi!

You implemented the hour view right? thats awesome.. could you share with us?

bests

**Comment by juniorschen** [comment]
> Hi!
> 
> You implemented the hour view right? thats awesome.. could you share with us?
> 
> bests

I just used the pFormat property with the time format and passed dates with times in my data

**Comment by mariohmol** [comment]
sorry.. could not understand.. can u share the code? thanks!

**Comment by mariohmol** [comment]
@juniorschen could u figure it out?

**Comment by juniorschen** [comment]
@mariohmol Sorry, we ended up buying a gantt component at the time, today I was seeing my issues and I closed because I no longer work with this component. I can't remember for sure about this problem, but it was something related to the block when the end of the day was midnight, but at the time I was starting web development, so it could be some mistake on my side.
