### ISSUE TITLE
XMLHttpRequest JSON - Deprecated on Chrome

### ISSUE THREAD

**Issue by gfweigand** [jsGanttImproved/jsgantt-improved#259]
Hi people,

Today is the first time I used jsgantt (it looks very grateful). With my last version of Google Chrome doesn't work. This is the message on Console window:

"jsgantt.js:1509 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."
"exports.parseJSON 1509"

 - OS: Windows 10
 - Browser Google Chrome 
 - Version 77.0.3865.90 (Build oficial) (64 bits)

Thank's in advance

**Comment by mariohmol** [comment]
thats true.. released a v2.5.0 with fetch when this exists on browser
