### ISSUE TITLE
Get data after vEditable

### ISSUE THREAD

**Issue by nguyennam0705** [jsGanttImproved/jsgantt-improved#265]
I dont know get data after startdate/enddate change

**Comment by mariohmol** [comment]
I think u have to try this


setEventsChange(): | Controls events when a task row is cliked. Pass a function to execute ex.: { taskname: function(task, event, cell, column){ console.log(task, event, cell, column); } }
-- | --


https://github.com/jsGanttImproved/jsgantt-improved/blob/master/docs/index.js#L78

**Comment by 3AUCE** [comment]
@nguyennam0705 did you find a solution to this. i cant seem to figure out how to properly get this to work.

**Comment by mariohmol** [comment]
@3AUCE  this is related to the other issue you opened right?

**Comment by 3AUCE** [comment]
> @3AUCE this is related to the other issue you opened right?

yes, but i figured it out. doing it differently though.

**Comment by mariohmol** [comment]
could u share to us?

**Comment by 3AUCE** [comment]
the application i created allowed for users to enter in hours to a specific phase/project. i then created a submit button that iterated through a list of employees and projects and dynamically generated a query expression that looks like this. 
```
inputHours = document.querySelector('#GanttChartDIVchild_'+PID+' > td.gadditional.gadditional-'+employeeName+' > input').value
```
