### ISSUE TITLE
Seconds, minutes and milliseconds as options for the format

### ISSUE THREAD

**Issue by nicolaswallmeyer** [jsGanttImproved/jsgantt-improved#267]
**Is your feature request related to a problem? Please describe.**
First of all I would like to thank you for your gantt chart it works really good and performs just fine. But there is one Issue I'm having trouble with:
I am using the gantt chart for jobs, which have very low runtimes. e.g. 2 Milliseconds. It would be great if it would be possible to change the format to such low intervals.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mariohmol** [comment]
Hi!

Thanks for that..

dup to #144
