### ISSUE TITLE
is there a way to dynamically populate the vAddtionalHeaders object with a JSON return? 

### ISSUE THREAD

**Issue by wmunsell** [jsGanttImproved/jsgantt-improved#268]
I'm using express routing to query a local database and i would like to plug the JSON response into the vAdditionalHeaders object. is this possible and/or could you provide instructions or an example?

**Comment by mariohmol** [comment]
Hi.. with `JSGantt.parseJSON('http://localhost/data.json', g);` u can get the data from a backend.. 

then u can set the aditional headers.. based in a hardcoded object or a response from a fetch

```
g.setOptions({
  vAdditionalHeaders: { // Add data columns to your table
      category: {
        title: 'Category'
      },
      sector: {
        title: 'Sector'
      }
    }
});```

right?

**Comment by mariohmol** [comment]
that worked?

**Comment by wmunsell** [comment]
not exactly but i did figure it out. what i did was format my GET response to match the needed format and assigned it to a variable. i then plugged that variable into the GetAdditionalHeaders object. vAdditionalHeaders: headers,
