### ISSUE TITLE
No "shadow" planned task rendered

### ISSUE THREAD

**Issue by Olivier-Boudeville-EDF** [jsGanttImproved/jsgantt-improved#272]
Hi,

(not necessarily a bug; this is mostly an understanding issue)

Seeing for example https://jsganttimproved.github.io/jsgantt-improved/demo.html it seems that jsgantt-improved is able (if I understand correctly) to display an actual task (ex: in red) and in its background its planned version (ex: in light pink) altogether. It seems a neat feature!

I tried to reproduce that on my local clone, tweaking an example XML file with different actual and planned dates in the hope to see the same: 

	<pStart>2020-07-08 8:15:00</pStart>
	<pEnd>2020-07-16 7:10:38</pEnd>

	<pPlanStart>2020-07-04 8:15:00</pPlanStart>
	<pPlanEnd>2020-07-14 7:15:38</pPlanEnd>

However only the actual task is displayed (no "shadow" planned task can be seen).

Are there specific conditions to meet in order to enable the rendering of the planned "shadow" tasks as well? (I could not find in the documentation an information about that feature)

Thanks in advance for any hint!

Best regards,

Olivier.

**Comment by mariohmol** [comment]
I long time dont toucn the xml version of it.. included this new fields on xml export/import

**Comment by Olivier-Boudeville-EDF** [comment]
Thanks for your answer (of course my question did not relate to the XML of Microsoft Project, but to the one defined and used by jsgantt-improved)
Does it mean that, in order to populate and render a Gantt, no external XML file shall be used anymore, and that one shall prefer either using a JSON file for that, or to define one's Gantt programmatically? (if yes, maybe the doc should be updated then)

**Comment by mariohmol** [comment]
JSON is prefered... but you can load via a xml as well. i implemented the new fields in XML importer.. upgrade to latest jsganttimproved

**Comment by Olivier-Boudeville-EDF** [comment]
Thanks for your answer! In my setting (Firefox 70.0.1 on Arch Linux with a few plugins) I was not able anymore to display a Gantt by using the "External XML File" button (I did not test the JSON loading yet), however by modifying the embedded code I could indeed see that when planned and actual dates differ, the former are indeed displayed "shadowed" in the background, which is neat indeed. Thanks again!

**Comment by Olivier-Boudeville-EDF** [comment]
If it can help (and as I was able to reproduce the issue, and unless I am mistaken), I think that the error regarding XML loading is:

TypeError: pXmlDoc.getElementsByTagName is not a function jsgantt.js:4910:24

**Comment by mariohmol** [comment]
Can u share the code you are using?

**Comment by Olivier-Boudeville-EDF** [comment]
Sure; I attach the rather minimal XML test with said issue, whose JSON counterpart works fine (I switched my planning generation from XML to JSON anyway, and it works OK now)
[gantt-test.zip](https://github.com/jsGanttImproved/jsgantt-improved/files/3825004/gantt-test.zip)
Many thanks for this useful tool!

**Comment by mariohmol** [comment]
=)
