### ISSUE TITLE
pID as UUID

### ISSUE THREAD

**Issue by duohedron** [jsGanttImproved/jsgantt-improved#275]
**Is your feature request related to a problem? Please describe.**
I store the tasks in a database and I use UUID as task ID. It would be nice if the same ID could be used as pID.
It works right now if the UUID doesn't have 'FF' in it.

**Describe the solution you'd like**
Instead of searching for 'FF', 'FS' etc... check the last two characters.
`vDepend[k] = vDepList[k].substring(0, vDepList[k].toUpperCase().indexOf('FF')); `
`vDepend[k] = vDepList[k].substring(0, vDepend[k].length - 3);`

Of course it should be checked if it is a valid UUID

**Comment by mariohmol** [comment]
good catch.. released on 2.5.4
