### ISSUE TITLE
Dependency arrows getting overlaped on pGroup=2.

### ISSUE THREAD

**Issue by rafaelvnunes** [jsGanttImproved/jsgantt-improved#277]
**Describe the bug**
When we have a pGroup=2 for overlaping tasks, the dependencies drawings get overlaped as well. I'll leave a screenshot bellow illustrating it.

**To Reproduce**
1. Set a task object with the property pGroup as 2
2. Create two subtask objects, one starting or finishing in the middle of the other dates interval
3. Create anoher task entry, and make one of the subtask from previous step dependent of this one
4. See the dependency linking arrow get overlaped.

**Expected behavior**
The arrow not getting overlaped.

**Screenshots**
![image](https://user-images.githubusercontent.com/32306797/68509546-f12ab000-024f-11ea-9532-19c530430206.png)

**Additional context**
On more complex ocasions it can get harder to see the arrows.

**Comment by mariohmol** [comment]
can u send me this json?

**Comment by RafaelNunesUSP** [comment]
[
	{
		"pID":206,
		"pName":"Graphs Test",
		"pStart":"2019-01-01",
		"pEnd":"2019-12-31",
		"pClass":"gnogantt",
		"pLink":"",
		"pMile":0,
		"pComp":0,
		"pGroup":1,
		"pParent":0,
		"pOpen":1,
		"pCaption":"Proj",
		"predecessor":""
	},
	{
		"pID":275,
		"pName":"Pre-Project",
		"pStart":"2019-01-01",
		"pEnd":"2020-01-01",
		"pClass":"gnogantt",
		"pLink":"",
		"pMile":1,
		"pComp":0,
		"pGroup":1,
		"pParent":206,
		"pOpen":1,
		"pCaption":"Mile",
		"pNotes":"",
		"predecessor":""
	},
	{
		"pID":-2050515367,
		"pName":"Teste1",
		"pStart":"2019-01-01",
		"pEnd":"2019-01-11",
		"pPlanStart":"2019-01-01",
		"pPlanEnd":"2019-01-11",
		"pClass":"gtaskblue",
		"pLink":"",
		"pMile":0,
		"pComp":0,
		"pGroup":2,
		"pParent":275,
		"pOpen":1,
		"pCaption":"Task",
		"pNotes":"",
		"predecessor":"",
		"appendedTaskId":1208
	},
	{
		"pID":1208,
		"pName":"Teste1",
		"pStart":"2019-01-01",
		"pEnd":"2019-01-11",
		"pClass":"gtaskblue",
		"pLink":"",
		"pMile":0,
		"pComp":0,
		"pGroup":0,
		"pParent":-2050515367,
		"pDepend":"",
		"pOpen":1,
		"pCaption":"Task",
		"pNotes":"",
		"project":"206"
	},
	{
		"pID":12098745,
		"pName":"Teste2",
		"pStart":"2019-01-12",
		"pEnd":"2019-01-16",
		"pPlanStart":"2019-01-12",
		"pPlanEnd":"2019-01-16",
		"pClass":"gtaskblue",
		"pLink":"",
		"pMile":0,
		"pComp":0,
		"pGroup":2,
		"pParent":275,
		"pOpen":1,
		"pCaption":"Task",
		"pNotes":"",
		"predecessor":"1208",
		"appendedTaskId":1209
	},
	{
		"pID":8745,
		"pName":"Appointments Interval",
		"pStart":"2019-01-11",
		"pEnd":"2019-01-12",
		"pClass":"gappointment",
		"pLink":"",
		"pMile":0,
		"pComp":0,
		"pGroup":0,
		"pParent":12098745,
		"pDepend":"",
		"pOpen":1,
		"pCaption":"Appointments Interval",
		"pNotes":"",
		"project":"206"
		},{
		"pID":1209,
		"pName":"Teste2",
		"pStart":"2019-01-12",
		"pEnd":"2019-01-16",
		"pClass":"gtaskblue",
		"pLink":"",
		"pMile":0,
		"pComp":0,
		"pGroup":0,
		"pParent":12098745,
		"pDepend":"1208",
		"pOpen":1,
		"pCaption":"Task",
		"pNotes":"",
		"project":"206"
	},
	{
		"pID":1220317130,
		"pName":"Teste3",
		"pStart":"2019-01-17",
		"pEnd":"2019-01-17",
		"pPlanStart":"2019-01-17",
		"pPlanEnd":"2019-01-17",
		"pClass":"gtaskblue",
		"pLink":"",
		"pMile":0,
		"pComp":0,
		"pGroup":2,
		"pParent":275,
		"pOpen":1,
		"pCaption":"Task",
		"pNotes":"",
		"predecessor":"1209",
		"appendedTaskId":1210
	},
	{
		"pID":1210,
		"pName":"Teste3",
		"pStart":"2019-01-17",
		"pEnd":"2019-01-17",
		"pClass":"gtaskblue",
		"pLink":"",
		"pMile":0,
		"pComp":0,
		"pGroup":0,
		"pParent":1220317130,
		"pDepend":"1209",
		"pOpen":1,
		"pCaption":"Task",
		"pNotes":"",
		"project":"206"
	}
]

**Comment by mariohmol** [comment]
HI there..I´m trying to reproduce this error.. but i can see this on top..


but I included a zindex for this lines to be on top!
