### ISSUE TITLE
If pStart and pPlanStart are the same, .gtaskbarcontainer.gplan is Missing

### ISSUE THREAD

**Issue by FaySmash** [jsGanttImproved/jsgantt-improved#279]
**Describe the bug**
If pStart and pPlanStart are the same, .gtaskbarcontainer.gplan is Missing. Inside the Gantt Diagram, the bar of the task doesn't show the planned start and end date.

**To Reproduce**
1. Download this repo
2. go inside fixes/data.json
3. search for `"pName": "Define Variables",`
4. replace the following lines with:
```
    "pStart": "2019-06-25",
    "pEnd": "2019-07-17",
    "pPlanStart": "2019-06-25",
    "pPlanEnd": "2019-07-18",
```
5. open demo.html and look for the task "Define Variables"

**Expected behavior**
Both bars should start on the 2019-06-25. The task bar should reach until 2019-07-17. The planned task bar should reach until 2019-07-18.

**Screenshots**
Expected:
![expected](https://user-images.githubusercontent.com/30392780/69142490-35774500-0ac7-11ea-9aa3-b37d844e81ea.PNG)

Reality (notice the missing planned task bar at the end)
![reality](https://user-images.githubusercontent.com/30392780/69142496-37d99f00-0ac7-11ea-9705-051ddedda9a1.PNG)

**Comment by FaySmash** [comment]
@agarciacalvo @mariohmol any updates on this matter?

**Comment by mariohmol** [comment]
Thank you!

released on + jsgantt-improved@2.5.9 , if u can double check pls

**Comment by FaySmash** [comment]
I can verify that the issue is fixed. Thanks @agarciacalvo @mariohmol !

**Comment by agarciacalvo** [comment]
Verified, thanks a lot.
