### ISSUE TITLE
Access and pull data from jsgantt-improved 

### ISSUE THREAD

**Issue by 3AUCE** [jsGanttImproved/jsgantt-improved#280]
Is it possible to access and pull data from jsgantt after the user edits the information? 
is there a functioning example of this that everyone can access?

my thought is to utilize the vEditable option to allow users to enter data. then when the user is complete, they could submit there changes to a backed database that will house the data.

**Comment by mariohmol** [comment]
check it out https://github.com/jsGanttImproved/jsgantt-improved/blob/master/docs/index.js#L199

**Comment by 3AUCE** [comment]
not sure why i didn't catch this earlier but my issue is that i made the additional headers also editable and im trying to pull the entered value from that. im currently pulling the value entered through the unique class name the div is given (i.e. "gadditional gadditional-additionalHeaderName") and then navigating to the input through the child of that div (i.e. document.getElementsByClassName("gadditional gadditional-additionalHeaderName")[i].children[0].children[0].value)
