### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by 3AUCE** [jsGanttImproved/jsgantt-improved#286]
The json data that is being passed to the gantt object is not getting displayed. im sure it has to be a configuration issue on my end but im at a total loss in trying to figure out where it could be at. 

**Expected behavior**
![image](https://user-images.githubusercontent.com/12951311/74354524-7fe82500-4d89-11ea-810f-014923b352ca.png)

within the image above, you can see that within the chart, the cells are blank with the exception of the project name (not sure why the name works but nothing else does). on the right, you can see a print out of the object that is getting passed to the gantt object that contains all of my information. for example, if you look at pNum, its populated within my json object but its not being populated within the view. 

any ideas on what might be causing this? 

side note: the json object on the right is only the first project within the gantt chart "090668 Valve Turning Program".

**Comment by 3AUCE** [comment]
is there a minimum list of headers needed before the addition of additional headers? basically all of my headers are being generated dynamically based off of the users input.

**Comment by mariohmol** [comment]
Hi! Could you figure it out?

I answered in stackoverflow, maybe we can continue there?
