### ISSUE TITLE
page rendering problem on iOS

### ISSUE THREAD

**Issue by eduardomourar** [jsGanttImproved/jsgantt-improved#29]
**Overview of the Issue:** Problem when loading web page on iOS.
**Motivation for or Use Case:** Background is blurred on iOS beyond recognition.
**Version(s):** N/A, refers to web page only.
**Browsers and Operating System:** All browsers on iOS.
**Reproduce the Error:**
![ios](https://cloud.githubusercontent.com/assets/16357187/22397731/6d932ee4-e55f-11e6-860d-b6fe4a84669c.jpeg)

**Related Issues:** N/A
**Suggest a Fix:** No idea, still investigating. But it is a known issue (see [here](http://stackoverflow.com/questions/36686654/fixed-background-images-disappear-on-iphone-ipad))

**Comment by RickCardoso** [comment]
**Pending test:** open the new webpage (from commit #38 ) on iOS and see if icons are rendering.

**Comment by eduardomourar** [comment]
The right pane (with the graph itself) gets reduced to zero width (and no horizontal scrollbar):

![image](https://user-images.githubusercontent.com/16357187/28249571-92ba348c-6a58-11e7-9e65-e667eee836ae.png)
