### ISSUE TITLE
Multiple objects on a single row?

### ISSUE THREAD

**Issue by plutocow** [jsGanttImproved/jsgantt-improved#290]
Hi, I'm exploring gantt libraries at the moment.
I'm looking at the documentation but I can't seem to find the answer.

Is it possible to do multiple objects on a single row?
Example:

![Example](https://user-images.githubusercontent.com/2157845/76156537-91291500-612e-11ea-9c9a-670871bab7a8.png)

**Comment by mariohmol** [comment]
We can do one after another... but not above 

check the Draw Task Items..
https://github.com/jsGanttImproved/jsgantt-improved/blob/master/docs/demo.gif
