### ISSUE TITLE
how to do editable information withihn a column and bind it for a method in vue?

### ISSUE THREAD

**Issue by dmitriyignatiev** [jsGanttImproved/jsgantt-improved#292]

**Comment by dmitriyignatiev** [comment]
Hello, could you please show use methods. For example i would like to have an option to make column editable for user. Also how to use methods which are listed in documentations, but there is no examples. Thank you in advance

**Comment by mariohmol** [comment]
You mean this?

https://github.com/jsGanttImproved/jsgantt-improved/blob/master/docs/index.js#L78

If you needs more docs... pls reopen
