### ISSUE TITLE
Remove delay to tooltip dismiss

### ISSUE THREAD

**Issue by luccasr73** [jsGanttImproved/jsgantt-improved#293]
** Is your feature request related to a problem? Please describe. **
I have a problem because of the time it takes for the tooltip to disappear and it keeps plugging other things in my interface

** Describe the solution you'd like **
I want to remove the animation on hiding tooltip

** Describe alternatives you've considered **
None

** Additional context **
None

**Comment by mariohmol** [comment]
There is an option vTooltipDelay, if you put this 0 it will remove the delay
