### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'list.find')

### ISSUE THREAD

**Issue by dmitriyignatiev** [jsGanttImproved/jsgantt-improved#294]
Hi, i'm trying to get data from row which i click using function below

```
function editValue(list, task, event, cell, column) {
  const found = list.find(item => item.pID == task.getOriginalID());
  consol.log("list " + event)
  if (!found) {
    return;
  }
  else {
    found[column] = event ? event.target.value : '';
    console.log(event.target.value)
  }
}
```
but this function only recieve an error how it could be fixed? Thank you in advance
`TypeError: undefined is not an object (evaluating 'list.find')`

**Comment by mariohmol** [comment]
There was a function before that did the .bind() passing the Taskslists.

I changed it now to have this list been passed as a parameter
+ jsgantt-improved@2.5.6

Here is the demo example without and working
https://github.com/jsGanttImproved/jsgantt-improved/blob/master/docs/index.js#L97

thanks for the tip!
