### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined at new exports.GanttChart (jsgantt.js:774)

### ISSUE THREAD

**Issue by Cirlao** [jsGanttImproved/jsgantt-improved#295]
Hello. I'm trying to use the improved version for the first time. The older ones worked just fine!
I've just replaced the .JS and .CSS files and when I try to run, I got the message: "jsgantt.js:774 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at new exports.GanttChart (jsgantt.js:774)."
This line of jagantt.js contains: "if (this.vDiv && this.vDiv.nodeName.toLowerCase() == 'div')"

P.S. I'm using the external XML file.

**Comment by mariohmol** [comment]
Thats a very strange error!

But thanks for reporting this, included this fix on the latest version..
thanks
