### ISSUE TITLE
Wrong duration in full chart view

### ISSUE THREAD

**Issue by fryktoria** [jsGanttImproved/jsgantt-improved#296]
The Duration of tasks in Quarter mode is not correct

1. Go to the Format line. 
2. Select Quarter view. In this screen, it is shown just as two dots after Month
3. The duration shown is not correct. See image full_view.png (wrong duration) in comparison to month_view.png (correct duration)

Screenshots
![month_view](https://user-images.githubusercontent.com/58485561/79662306-379c1780-81bd-11ea-9453-56e5302fae9c.png)
![full_view](https://user-images.githubusercontent.com/58485561/79662327-38cd4480-81bd-11ea-8ac6-291b82a26bf8.png)

Desktop
 - OS: Linux Mint 17.3
 - Browser Mozilla Firefox  66.03

**Comment by mariohmol** [comment]
Hi, I think all duration issues was fixed on + jsgantt-improved@2.5.8

could u doubl check please?
