### ISSUE TITLE
Duration of Planned Tasks is always shown in weeks

### ISSUE THREAD

**Issue by fryktoria** [jsGanttImproved/jsgantt-improved#297]
The duration of planned tasks is always shown in weeks, regardless of the view selection (Hour, Day, Week, Month)

**Screenshots**
![planned_duration](https://user-images.githubusercontent.com/58485561/79664525-d9bbff80-81bd-11ea-8328-53983f6ece06.png)

**Desktop 
 - OS:Linux Mint 17.3
 - Browser Firefox 66.03

**Comment by mariohmol** [comment]
good catch, thank you!

fixed on 2.5.8
