### ISSUE TITLE
Planned tasks below tooltip appear in tooltip

### ISSUE THREAD

**Issue by fryktoria** [jsGanttImproved/jsgantt-improved#298]
When a tooltip overlaps a planned tasks, which is shown with the default color, the task is shown in the tooltip.

Desktop 
 - OS: Linux Mint 17.3
 - Browser Firefox 66.03

![tooltip](https://user-images.githubusercontent.com/58485561/79668658-1e946600-81bf-11ea-9741-cc47e4aabb01.png)

**Comment by mariohmol** [comment]
You are right, thanks for this.

fix on 2.5.7
