### ISSUE TITLE
Show format option in Drop-down box rather div in table cell

### ISSUE THREAD

**Issue by noddy09** [jsGanttImproved/jsgantt-improved#301]
Format heading and its options (Day, Month, Year) has css _overflow: hidden_. this css property may sometime cause to hide it's content.
Rather changing that property, it could be great if same options will be shown in drop-down.
Because anyways user have to choose only one option at a time. 
So rendering all options at a time as in <td> may not cause problem in default styling, but it will surely hide format options in some styling combos, example: (.gmainleft reduced width + increase font-size) etc.

**Comment by mariohmol** [comment]
What elements in specific ar u taling aout to have drop down? can you point out with printscreems?

**Comment by mariohmol** [comment]
Hi, reopen when u have more info

thanks
