### ISSUE TITLE
Customizing the left panel with custom variables

### ISSUE THREAD

**Issue by groseg** [jsGanttImproved/jsgantt-improved#302]
Is it possible to customize the left panel to display values from custom variables? I have a dynamic data set, I can not change the data set. In my data set I have the followings:

"host": "string text",//root
 "pid": "string text",//parent
 "tid":  "string text",//child
 "name": "string text",
  "id": 1,//number

My data set has different keys and different value data types than what I see available: 
"pID": 121,
"pName": "Grandchild1",
 "pParent": 12,

I was wondering it is possible to make customizations to display my data set.
Thank you so much

**Comment by mariohmol** [comment]
Yes you can, look over this on the demo

```
vAdditionalHeaders: { // Add data columns to your table
      category: {
        title: 'Category'
      },
      sector: {
        title: 'Sector'
      }
    },
```
