### ISSUE TITLE
Any server-side companion application?

### ISSUE THREAD

**Issue by brentfraser** [jsGanttImproved/jsgantt-improved#304]
I've reviewed the doc and issues but didn't see much on an open source server-side companion application.  What is being used on servers to manage the project data?

**Comment by mariohmol** [comment]
Hi!

That depends... can be any Web Services.... I use nodejs for instance

**Comment by brentfraser** [comment]
Ok.  I thought I would ask before I re-invented the wheel.  My plan is to use use django with a Postgres database.  I'll create various tables such as Project, Task, and Effort, then have django generate the json on-demand from jsgantt-improved on the client.  Thanks!

**Comment by mariohmol** [comment]
Awesome =)
