### ISSUE TITLE
Error while ng build --prod in jsgantt.css file.

### ISSUE THREAD

**Issue by 362032664** [jsGanttImproved/jsgantt-improved#305]
Describe the bug
Error while ng build --prod in angular 8 project.
ERROR in node_modules/jsgantt-improved/dist/jsgantt.css(696:12): An unhandled exception occurred:Unknown word

To Reproduce

1.Take npm install --save jsgantt-improved ng-gantt
2. For better styling, add below line to your main style.css file @import "~jsgantt-improved/dist/jsgantt.css";
3.execute "ng build --prod"

Expected behavior
The error should not come and build should be success.

Screenshots
The cause of the error may be that the _filter is not a css attribute
Error:
ERROR in node_modules/jsgantt-improved/dist/jsgantt.css(696:12): An unhandled exception occurred:Unknown word.

**Comment by mariohmol** [comment]
Hi there,

we have a ng-gant module.. have u see?
