### ISSUE TITLE
In react, how to change the name of the headers of the table

### ISSUE THREAD

**Issue by gargmohit3890** [jsGanttImproved/jsgantt-improved#306]
How can we change the name of the headers of the table and for the column which has task name, there is no header for it. so how can I add the name of this column?

Secondly, the heading of the task groups(Define Chart API, Task Objects, Code Javascript, and Draw Task Bars) is not editable. how can we make them editable?

**Comment by mariohmol** [comment]
Hi!

We have the React module, https://github.com/jsGanttImproved/react-jsgantt

If you have issues with this can u please open the request there? thanks!
