### ISSUE TITLE
The pBarText option used to include text inside a task bar - doesn't work

### ISSUE THREAD

**Issue by shradhakarnawat** [jsGanttImproved/jsgantt-improved#309]
**Describe the bug**
The documentation cites an optional parameter in TaskItem i.e pBarText, which can be used to include text inside a tak bar. But when I use the parameter, no data is added in my taskbar.  

**To Reproduce**
Pass the following data -
{
      'pID': 1,
      'pName': 'Define Chart API v2',
      'pStart': '',
      'pEnd': '',
      'pClass': 'ggroupblack',
      'pLink': '',
      'pMile': 0,
      'pRes': 'Brian',
      'pComp': 0,
      'pGroup': 1,
      'pParent': 0,
      'pOpen': 1,
      'pDepend': '',
      'pCaption': '',
      'pBarText' : 'This is bar text',
      'pNotes': 'Some Notes text'
    }
**Expected behavior**
In the taskbar of Define Chart API v1, on the black taskbar (As I've used ggroupblack or any other color taskbar which I can use) - It must show "This is bar text"

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Linux
 - Browser : Firefox

**Additional context**

**Comment by O3DigitechSolutions** [comment]
I agree, this option doesn't work 
![image](https://user-images.githubusercontent.com/22743532/86889166-9a85b680-c0fb-11ea-94bb-b8b9c0dc456c.png)

**Comment by mariohmol** [comment]
It's working in this example:

https://jsganttimproved.github.io/jsgantt-improved/docs/demo.html

**Comment by mariohmol** [comment]
Can u make a demo like or send me the data.json that its not working?

**Comment by mariohmol** [comment]
Tested again and its working in the live demo
