### ISSUE TITLE
Is there a way to include custom header in the tooltip

### ISSUE THREAD

**Issue by O3DigitechSolutions** [jsGanttImproved/jsgantt-improved#310]
How can I include a custom header in the displayed tooltip 
![image](https://user-images.githubusercontent.com/22743532/86889685-6fe82d80-c0fc-11ea-9898-a6fc64852ef8.png)

**Comment by O3DigitechSolutions** [comment]
After checking the documentation on async tooltip, i find out this can be resolved by getting the task current moused on, and fetching the needed property from it like below:

` getTooltipTemplate(taskAll: any) {    
      return new Promise((resolve, reject) => {
        const delay = Math.random() * 300;
        setTimeout(() => {
          var task = taskAll.getAllData().pDataObjec;
          console.log(task.getLevel(),task.location);
         let  template =                    
                     <tr>
                     <td style='text-align:center;background-color:#1a237e;color:white;border:1px solid black;'>Period</td>
                     <td style='background-color:white;border:1px solid black;'>${task.startDate } to ${task.endDate }</td>
                    </tr>
                     <tr>
                        <td style='text-align:center;background-color:#1a237e;color:white;border:1px solid black;'>Location</td>
                        <td style='background-color:white;border:1px solid black;'>${task.location}</td>
                     </tr>
                     <tr>
                        <td style='text-align:center;background-color:#1a237e;color:white;border:1px solid black;'>Resource</td>
                        <td style='background-color:white;border:1px solid black;'>${task.resource}</td>
                     </tr>
                     <tr>
                     <td style='text-align:center;background-color:#1a237e;color:white;border:1px solid black;'>Quantity</td>
                     <td style='background-color:white;border:1px solid black;'> ${task.quantity} </td>
                  </tr>;          
          resolve(template);
        }, delay);
      });      
    }`

**Comment by abeeching1** [comment]
Did you ever come across an error saying 'template.replace is not a function'? I've tried a variety of approaches to getting custom tooltips working but am always met with this error. Cheers

**Comment by O3DigitechSolutions** [comment]
> Did you ever come across an error saying 'template.replace is not a function'? I've tried a variety of approaches to getting custom tooltips working but am always met with this error

Hi, I didnt come across such error, if you could post your code and where the error stems from.It might be easier to suggest possible corrections.

**Comment by abeeching1** [comment]
I did some digging and realised my issue. The server I am working on hosts a lot of legacy code so the version of Javascript installed is too outdated to be able to use template.replace unfortunately.

**Comment by abeeching1** [comment]
Would appreciate any help you can offer. I've tried so many approaches but any time I try to pass a function to vToolTipTemplate I always get an error saying template.replace is not a function. Here's all my code that should be relevant. I'm developing in conjunction with PL/SQL which should explain the double apostrophes all over the place. 

`<script type="text/javascript">
          
          var g = new JSGantt.GanttChart(document.getElementById(''GanttChartDIV''), ''day'');
     
          function getTooltipTemplate(taskAll) {
            return new Promise((resolve, reject) => {
              const delay = Math.random() * 300;
              setTimeout(() => {
                var task = taskAll.getAllData().pDataObject;
                console.log(task.getLevel(),task.location);
                let template = 
                `<tr>
                  <td style=''text-align:center;
                  background-color:#1a237e;
                  color:white;border:1px solid black;''>
                  Quantity</td>
                  <td style=''background-color:white;
                  border:1px solid black;''>
                  {{pName}} </td>
                </tr>`;
              resolve(template); }, delay); });
          } 
    
          vAdditionalHeaders = {
            category: {
              title: ''Category''
            },
            sector: {
              title: ''Sector''
            }
          }
          
          g.setOptions({      
            vAdditionalHeaders,
            vTooltipTemplate: getTooltipTemplate
          });  
          
            g.AddTaskItemObject({
              pID: 1,
              pName: ''Test Item half day'',
              pStart: ''2020-08-01'',
              pEnd: ''2020-08-15 12:00'',
              pPlanStart: "",
              pPlanEnd: "",
              pClass: "gtaskred",
              pLink: '''',
              pMile: 0,
              pRes: "Alex",
              pComp: 0,
              pGroup: 0,
              pParent: 0,
              pOpen: 1,
              pDepend: "",
              pCaption: "Caption text here",
              pCost: 1000,
              pNotes: "Some Notes text",
              pBarText: "Bar text here",
              category: "My Category",
              sector: "Finance",
              deadline: "2020-07-28 12:00"
            });

        g.Draw();
  </script>`

Here is the error trace  (ab:131 is the call to g.Draw() :  

Uncaught TypeError: template.replace is not a function
    at jsgantt.js:3155
    at Array.forEach (<anonymous>)
    at exports.GanttChart.exports.createTaskInfo (jsgantt.js:3146)
    at exports.GanttChart.Draw (jsgantt.js:938)
    at ab:131
(anonymous) @ jsgantt.js:3155
exports.createTaskInfo @ jsgantt.js:3146
Draw @ jsgantt.js:938
(anonymous) @ ab:131

My knowledge of Javascript and web tech in general is pretty limited so apologies if I#ve missed out anything important here.

**Comment by abeeching1** [comment]
Issue resolved. The version of jsgantt on the server I was using was out of date. I updated  it and now the error has gone.

**Comment by mariohmol** [comment]
Awesome!! Thanks for this discussion

**Comment by jonmnoj** [comment]
This custom tooltip template functionality seems to have been broken by v2.7.0, when trying to use a function to return the template the gTaskInfo div is now empty, whereas using v2.6.4 populates it correctly.

**Comment by mariohmol** [comment]
Indeed we had a change here https://github.com/jsGanttImproved/jsgantt-improved/pull/327

@joules457 . can you help?

@jonmnoj can u provide a piece of code so we can understand more the issue here
