### ISSUE TITLE
Refine dates precision to one second

### ISSUE THREAD

**Issue by lcocault** [jsGanttImproved/jsgantt-improved#311]
The precision of dates seems to be limited to one minute. It can be useful, under certain circumstances, to have a finer precision. Would it be possible to complement the DateUtils to support date formats specifying the second?

In parseDateStr, this would consist of adding a case to the existing switch:
+            case 'yyyy-mm-dd HH:MI:SS':
+                vDate = new Date(vDateParts[0], vDateParts[1] - 1, vDateParts[2], vDateParts[3], vDateParts[4], vDateParts[5]);
+                break;

In formatDateStr, this would consist of adding the following cases to the existing swicth:
+            case 'SS':
+                if (pDate.getSeconds() < 10)
+                    vDateStr += '0'; // now fall through
+            case 'ss':
+                vDateStr += pDate.getSeconds();
+                break;

A finer precision going to the millisecond would also be useful to be compliant with ISO8601.

**Comment by mariohmol** [comment]
Could you please provide PR for us?

**Comment by lcocault** [comment]
I created a feature branch from the master branch, but I cannot push my feature branch. Should I have the privileges required to push my feature branch?

**Comment by mariohmol** [comment]
I think you have to fork the repo first, then push to there, and after open a Pull Request here.. right?

**Comment by lcocault** [comment]
Thank you for the instruction. I am not very used to submitting pull request on GitHub projects. I hope this is now properly done.
See the pull request: https://github.com/jsGanttImproved/jsgantt-improved/pull/314

**Comment by mariohmol** [comment]
Well done!!

It looks great! 

Will merge, test and release a new version!

Thank you!
