### ISSUE TITLE
Wrong dates in task groups

### ISSUE THREAD

**Issue by agarciacalvo** [jsGanttImproved/jsgantt-improved#312]
As we can see in the image below:

![image](https://user-images.githubusercontent.com/18212145/92755041-bd4a7a80-f38b-11ea-92d1-47888235bd8f.png)

The 3.2 task group has a wrong start date (should be 21/01/2020) and plan end date (should be 31/01/2020).

Also, the Fase 3.1 task group shouldn't have start and end dates due that none of their tasks are started.

**Comment by mariohmol** [comment]
We have here an awesome cenario, thanking for point this out.

**Comment by agarciacalvo** [comment]
"Fortunately" it was also failing with 2.5.5 version.

![image](https://user-images.githubusercontent.com/18212145/93200063-973c2600-f74f-11ea-8a12-815b68bbcc63.png)

I'll try to figure out a fix but I still don't know how can I test my changes.

**Comment by mariohmol** [comment]
Ok.. so when u clone the project.. u can run `npm run start` and go to `http://127.0.0.1:8081/docs/demo.html`

You can run in another terminal the `npm run watch` o every change u do in source it will compile again

**Comment by mariohmol** [comment]
thanks @agarciacalvo!!

could u please double check v.2.5.10 ?

**Comment by agarciacalvo** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/18212145/93310079-9ca77800-f804-11ea-9a4e-0e39fca8a316.png)

Thanks a lot
