### ISSUE TITLE
Gantt Chart doesn't draw when task list is empty.

### ISSUE THREAD

**Issue by ThomasPCG** [jsGanttImproved/jsgantt-improved#316]
**Bug Description**
When initializing the gantt chart with an empty task list, it doesn't appear.

**To Reproduce**
1. Setup a new html page with the gantt chart css / js.
2. Initialize the gantt chart
```js 
var g = new JSGantt.GanttChart(document.getElementById('ganttChartDiv'), 'day');
//Set options accordingly.
g.Draw();
```
3. Run the html page on a browser.

**Expected behavior**
An empty gantt chart with the relevant headers should appear. The first data row should display a label stating no records found.

**Screenshots**
With tasks:
![image](https://user-images.githubusercontent.com/25073827/94370679-ed33a500-0123-11eb-81ca-676db14fae51.png)

Without tasks:
![image](https://user-images.githubusercontent.com/25073827/94370700-06d4ec80-0124-11eb-954c-9dd15c95c9e4.png)

Without tasks (expected):
![image](https://user-images.githubusercontent.com/25073827/94370796-a2665d00-0124-11eb-8a1c-f343b0fb5148.png)

**Motivation / Use Case**
Without showing an empty gantt chart, the user might be confused as to why no gantt chart was rendered and thought it is a bug.

**Comment by mariohmol** [comment]
Thats a good idea! Thank you!


This should not be hard to implement:

# Making an else

There is a if that checks when is == 0 
https://github.com/jsGanttImproved/jsgantt-improved/blob/master/src/draw.ts#L214

and We can put an else statement to deal with this case. 
https://github.com/jsGanttImproved/jsgantt-improved/blob/master/src/draw.ts#L829

But to make this work we have to separate some functions that are inside the if

# Or making the if to work with length 0

This same if pointed up where we check if th length == 0 , we can try to remove that and check where fails and code to make it work without breaking.. I think this option will be faster to implement

**Comment by mariohmol** [comment]
Hi, check v2.7.2 

thanks
