### ISSUE TITLE
Expand Cell Event needed 

### ISSUE THREAD

**Issue by MohamedGabrFadl** [jsGanttImproved/jsgantt-improved#317]
**Is your feature request related to a problem? Please describe.**
I want to lazy load the sub-nodes as I have N numbers of parents which may have a long list of children so I need an event that supports the lazy load of these children to call

**Describe the solution you'd like**
Adding an event on clicking the expand button 

**Describe alternatives you've considered**
Also would be nice if we have a flag of expanding and collapsing the parent nodes

**Comment by mariohmol** [comment]
Good idea!

Now we have the setEventClickCollapse / vEventClickCollapse

**Comment by MohamedGabrFadl** [comment]
> Good idea!
> 
> Now we have the setEventClickCollapse / vEventClickCollapse

Thanks and appreciate your fast pace development
