### ISSUE TITLE
New rendering is buggy

### ISSUE THREAD

**Issue by agarciacalvo** [jsGanttImproved/jsgantt-improved#319]
I'm sorry but after updating to 2.6.1 I get this gannt:

![image](https://user-images.githubusercontent.com/18212145/94903303-e4333280-0499-11eb-9d2b-32ecfd936606.png)

It lacks several vertical bars, other are desaligned and the footer is a mess :(

Before it was like:

![image](https://user-images.githubusercontent.com/18212145/94903418-13e23a80-049a-11eb-9fde-0341eef32170.png)

The demo also lacks vertical bars, but footer is ok:

![image](https://user-images.githubusercontent.com/18212145/94906465-cf0cd280-049e-11eb-81bd-7fb782142dbe.png)

My vertical bars are fixed if I play with F12 adding this (maybe it gives a clue):

![image](https://user-images.githubusercontent.com/18212145/94906628-1a26e580-049f-11eb-8af7-5b80c9741af9.png)

I'm afraid I can't fix the footer mess playing with F12.

**Comment by mariohmol** [comment]
Hi, this is true, I saw it last night.. going to fi today..

one question, this vertical lines on the chart area. its not cleaner to not have it?

**Comment by mariohmol** [comment]
fixed on v2.6.2!
thanks

**Comment by agarciacalvo** [comment]
I've tried with v2.6.3 and it's ok. Thanks a lot!

PD: I think I prefer vertical lines so I can see better if one task starts/ends at one week/month or another.

![image](https://user-images.githubusercontent.com/18212145/94986591-43f41100-0560-11eb-963e-3c47a9aa8084.png)

**Comment by mariohmol** [comment]
awesome!! thanks for the feedback
