### ISSUE TITLE
Min/max date, what changed in 2.5.10?

### ISSUE THREAD

**Issue by ecke101** [jsGanttImproved/jsgantt-improved#320]
I was running v2.5.5 and upgraded to the latest, but then my graph started at 1960 something no matter if I used setMinDate or not. I discovered 2.5.9 was the latest working version and can see something was changed with min/maxdate starting at 2.5.10 but can't figure out what?

**Comment by agarciacalvo** [comment]
This: #312

**Comment by ecke101** [comment]
> 
> 
> This: #312

Ok, well I'm using react and render the graph first with the task groups empty, then when the data comes in I populate the groups with tasks. Must be something strange happening there with the dates. Any idea?

**Comment by mariohmol** [comment]
canu provide a dta to simulate this?

**Comment by ecke101** [comment]
> 
> 
> canu provide a dta to simulate this?

I don't really have time to investigate this any further, but the same thing happens if I just add one group, no tasks. With the old versions the graph shows oct 2020 to feb 2021 but >=2.5.10 it starts at 1970. If I only add tasks, no groups, it works as expected.

**Comment by joules457** [comment]
I agree with @ecke101 

Bythe way @mariohmol  also happens in the demo using bigdata.json if you want to reproduce it

**Comment by agarciacalvo** [comment]
I think this is already fixed, isn't it?

![image](https://user-images.githubusercontent.com/18212145/97688746-df629e00-1a9a-11eb-8704-aa21659f3538.png)

**Comment by mariohmol** [comment]
I think it is.. please double check v2.7.0
