### ISSUE TITLE
Single cell is not rendered through all columns as in v2.5.5

### ISSUE THREAD

**Issue by DavidDomB** [jsGanttImproved/jsgantt-improved#324]
**Describe the bug**
In version 2.5.5, when useSingleCell threshold is exceeded, the single cell was rendered using the width of all days column headers, but now it only is rendered over the first column.

**To Reproduce**
1. Go to demo
2. Set UseSingleCell value to 1000
3. The single cell is rendered only over the first column

**Expected behavior**
The single cell is rendered through the row

**Screenshots**
v2.5.5
![image](https://user-images.githubusercontent.com/29315573/96177451-87049b80-0ef3-11eb-8ceb-75302c458729.png)

current:
![image](https://user-images.githubusercontent.com/29315573/96174916-af8a9680-0eef-11eb-8c8a-1c5e3cee10de.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 86.0.4240.75

**Comment by mariohmol** [comment]
released on #325 v2.6.4 

thanks to @joules457
