### ISSUE TITLE
how to set the min date(year or month) of the calendar in ganttchart

### ISSUE THREAD

**Issue by Traviata** [jsGanttImproved/jsgantt-improved#326]
i want to set the min date
i put json data which is the test in your project
and some projects don't have start date and end date
i think maybe because of that calendar start 1969year~2021year
how can i fix it
anyone have idea?
![image](https://user-images.githubusercontent.com/33504156/97275480-54568d80-1879-11eb-9f70-58270eb2652c.png)

**Comment by mariohmol** [comment]
Hi, the new version has this fix, right? thank
