### ISSUE TITLE
Highlight current day/week/month depending on the year

### ISSUE THREAD

**Issue by mishellscripts** [jsGanttImproved/jsgantt-improved#330]
Currently there is a class added for weekend dates, but can we add one for the current date as well? The use case is to be able to style the current day/week/month depending on the format. The issue is that from html/css, there is no way to figure out the current date based on the contents of the table

Refer to the below screenshot where the header of the current day cell is highlighted which is what I want to achieve:
![image](https://user-images.githubusercontent.com/18112722/99985237-c7610000-2d62-11eb-8bda-d32f6c8ad4b7.png)

**Comment by mariohmol** [comment]
Thats a very good idea! shouldn't be hard to implement.
I did a small test here including this class when its current day or week: gtaskcellcurrent

For month and years its a little more complicated.. so if someone needs this needs to open a new issue

**Comment by mariohmol** [comment]
check v2.6.5

**Comment by mishellscripts** [comment]
Can the same logic be reused to add the class for the header too? like gminortaskcurrent?
