### ISSUE TITLE
This custom tooltip template functionality seems to have been broken by v2.7.0, when trying to use a function to return the template the gTaskInfo div is now empty, whereas using v2.6.4 populates it correctly.

### ISSUE THREAD

**Issue by joules457** [jsGanttImproved/jsgantt-improved#331]
This custom tooltip template functionality seems to have been broken by v2.7.0, when trying to use a function to return the template the gTaskInfo div is now empty, whereas using v2.6.4 populates it correctly.

_Originally posted by @jonmnoj in https://github.com/jsGanttImproved/jsgantt-improved/issues/310#issuecomment-735031055_

This is due to the change:

Content of tooltip is stored in data attribute "data-tooltip" instead to be stored in the div itself

**Comment by joules457** [comment]
@mariohmol @jonmnoj 

**I was able to reproduce the issue** in demo, with dynamic tooltip activated. I'll proceed to fix it

The tooltip template was stored as data attribute instead of gTaskInfo div

**Comment by mariohmol** [comment]
Thanks a lot @joules457 !

released on 2.7.3
