### ISSUE TITLE
Duration of Months and Quarters is incorrect

### ISSUE THREAD

**Issue by RVBE** [jsGanttImproved/jsgantt-improved#337]
**Describe the bug**
When the duration for the amount of Months or Quarters are calculated, the amount of Months / Quarters doesn't add up to the actual amount of Months / Quarters. Current wrong formula:

```
const hours = (end.getTime() - start.getTime()) / 1000 / 60 / 60;
    let tmpPer;
    switch (vUnits) {
      case 'hour': tmpPer = Math.round(hours); vDuration = tmpPer + ' ' + ((tmpPer != 1) ? pLang['hrs'] : pLang['hr']); break;
      case 'day': tmpPer = Math.round(hours / 24); vDuration = tmpPer + ' ' + ((tmpPer != 1) ? pLang['dys'] : pLang['dy']); break;
      case 'week': tmpPer = Math.round(hours / 24 / 7); vDuration = tmpPer + ' ' + ((tmpPer != 1) ? pLang['wks'] : pLang['wk']); break;
      case 'month': tmpPer = Math.round(hours / 24 / 7 / 30); vDuration = tmpPer + ' ' + ((tmpPer != 1) ? pLang['mths'] : pLang['mth']); break;
      case 'quarter': tmpPer = Math.round(hours / 24 / 7 / 30 / 3); vDuration = tmpPer + ' ' + ((tmpPer != 1) ? pLang['qtrs'] : pLang['qtr']); break;
    }
    return vDuration;
  }
```

**To Reproduce**
1. Set a project with a start and enddate over a few months time.
2. Check the Gantt of Months and Quarters.

**Expected behavior**
Simply put, the 30 in Months and Quarters should be replaced by 4. In more detail;
Months are calculated correctly by : hours / 24 / 7 / **4** (or even better 4,35 if you want to get a full 12 months a year).
Quarters are calculated correctly by : hours / 24 / 7 / **12** (or even better 13 if you want a full 4 quarters a year).

**Comment by mariohmol** [comment]
Thanks for that!

let me check

**Comment by mariohmol** [comment]
good catch.. that's great!!
thanks!
