### ISSUE TITLE
Default ToolTip Error(Undefined... Duration, Resource)

### ISSUE THREAD

**Issue by bckim7065** [jsGanttImproved/jsgantt-improved#342]
Hi,
Frist I would like to say thank you very much for your jsgantt library

However, I found an Undefined error in the basic tooltip during use.

In the language setting en , Duration and Resource are displayed as Undefined In tooltip

I found that gsgantt.js is referencing the wrong key value.

===========================================================================
File : jsgantt.js 
Location : jsgantt-improved-master/dist/
Line : 3619 And 3631
Source : 
![image](https://user-images.githubusercontent.com/64826478/112432867-d396b180-8d84-11eb-9d3b-fde9d39a3f76.png)
==============================================================================

==============================================================================
Reference file : lang.ts 
Location : jsgantt-improved-master/src/
Line : 98(res), 99(dur)
![image](https://user-images.githubusercontent.com/64826478/112433117-25d7d280-8d85-11eb-8098-8c04f3dda93e.png)
==============================================================================

It seems that the source will need to be modified.

I am not sure if the meaning will be conveyed well because I am not good at English, but please check

have a nice day, Bye!

**Comment by mariohmol** [comment]
good catch! released on v2.8.2
