### ISSUE TITLE
How tu use modified JS in Angular

### ISSUE THREAD

**Issue by huseyin-bozkurt** [jsGanttImproved/jsgantt-improved#357]
Dear Developer,
I have added new features (Click event for each task bar) to jsgannt.js file and i would like to use that feature in Angular wrapper.
What do i need to do to use this new feature i added in Angular wrapper?
Best Regards.
Huseyin

**Comment by mariohmol** [comment]
yes.. we need to replicate.. if u can provide a Pull Request would be awesome
