### ISSUE TITLE
How to extend num of chars displayed for Task-Title from 50 -> ~120?

### ISSUE THREAD

**Issue by holger-dicke** [jsGanttImproved/jsgantt-improved#359]
I want to display task-names/-titles in jsgantt-improved table (1st column) which are in excess of 50 chars (task-title length can be up to 120 chars). 
I already found the part in jsgantt.css to increase the column width -> . 
_.gtaskname {
  min-width: 170px;
  max-width: 170px;
  width: 170px;
  font-size: 9px;
  border-left: none;
}_
However, still the task-title/Task name is truncated after ~50 chars, no matter whether "Configure Editable" is checked or not.  
Any help would be appreciated! ThX!

**Comment by mariohmol** [comment]
could u figure it out?
This should be a pure CSS change..  ex.: .gantt-inputtable { width: 100% }
