### ISSUE TITLE
Italian language

### ISSUE THREAD

**Issue by cristianzeni** [jsGanttImproved/jsgantt-improved#360]
**Is your feature request related to a problem? Please describe.**
Using jsgantt-improved into Angular project requires a wrapper that masks functions. I'm able to set the options but when I need to use the addLang() function for italian translations, nothing happens. Looking at previous conversations, [Internationalisation at jsGanttImproved/ng-gantt](https://github.com/jsGanttImproved/ng-gantt/issues/11), I think is better if we introduce italian translations.

**Describe the solution you'd like**
Here follow the italian translation:

`
const en = {
  'format': 'Formato',
  'hour': 'Ora',
  'day': 'Giorno',
  'week': 'Settimana',
  'month': 'Mese',
  'quarter': 'Trimestre',
  'hours': 'Ore',
  'days': 'Giorni',
  'weeks': 'Mesi',
  'months': 'Settimane',
  'quarters': 'Trimestri',
  'hr': 'Ora',
  'dy': 'G',
  'wk': 'Sett.',
  'mth': 'Mese',
  'qtr': 'Trim.',
  'hrs': 'Ora',
  'dys': 'GG',
  'wks': 'Sett.',
  'mths': 'Mesi',
  'qtrs': 'Trim.',
  'res': 'Risorsa',
  'dur': 'Durata',
  'comp': '% Compl.',
  'completion': 'Completamento',
  'startdate': 'Data inizio',
  'planstartdate': 'Piano data inizio',
  'enddate': 'Data fine',
  'planenddate': 'Piano data fine',
  'cost': 'Costo',
  'moreinfo': 'Più informazioni',
  'nodata': 'Nessun task trovato',
  'notes': 'Note',
  'january': 'Gennaio',
  'february': 'Febbraio',
  'march': 'Marzo',
  'april': 'Aprile',
  'maylong': 'Maggio',
  'june': 'Giugno',
  'july': 'Luglio',
  'august': 'Agosto',
  'september': 'Settembre',
  'october': 'Ottobre',
  'november': 'Novembre',
  'december': 'Dicembre',
  'jan': 'Gen',
  'feb': 'Feb',
  'mar': 'Mar',
  'apr': 'Apr',
  'may': 'Mag',
  'jun': 'Giu',
  'jul': 'Lug',
  'aug': 'Ago',
  'sep': 'Set',
  'oct': 'Ott',
  'nov': 'Nov',
  'dec': 'Dic',
  'sunday': 'Domenica',
  'monday': 'Lunedì',
  'tuesday': 'Martedì',
  'wednesday': 'Mercoledì',
  'thursday': 'Giovedì',
  'friday': 'Venerdì',
  'saturday': 'Sabato',
  'sun': 'Dom',
  'mon': 'Lun',
  'tue': 'Mar',
  'wed': 'Mer',
  'thu': 'Gio',
  'fri': 'Ven',
  'sat': 'Sab',
  'tooltipLoading': 'Caricamento...'
}
`

**Describe alternatives you've considered**
I accept any advice!

**Additional context**
I want to help improving this incredible project! :)

**Comment by mariohmol** [comment]
thank you.. added the italian language on new release
