### ISSUE TITLE
Display tasks calendar starting from the bottom instead of the top

### ISSUE THREAD

**Issue by FranciscoSantos97** [jsGanttImproved/jsgantt-improved#362]
It would be a good feature to be able to invert the display of the tasks in the table. Instead of having the oldest task at the top of the tables, having it at the bottom, and the subsequent tasks and flow would be drawn upwards instead of downwards. Please correct me if I'm wrong, but I don't think it's possible to do that with the current implementation. Thank you.

**Comment by mariohmol** [comment]
I think u can use the  this.getSortIdx = function () { return vSortIdx; }; for this, use the propery to give Ids and it will sort by that...

if u can try it out and help us with a better doc in a PR would be great!

thanks
