### ISSUE TITLE
Is it possible to export the current chart as JSON?

### ISSUE THREAD

**Issue by vrthra** [jsGanttImproved/jsgantt-improved#363]
Similar to `getXMLProject()` is there a way to retrieve the JSON string so that the returned string is later parsable by `JSGantt.parseJSON()`?

**Comment by mariohmol** [comment]
Check this out

https://github.com/jsGanttImproved/jsgantt-improved/blob/7d696916467dee891f2f33640fbcc7612f89a984/docs/index.js#L204
