### ISSUE TITLE
Ability to auto adjust columns

### ISSUE THREAD

**Issue by abrousseau001** [jsGanttImproved/jsgantt-improved#42]
Is there a way to auto adjust the columns, specifically the ones containing information like the task name, resource, duration, etc.? The sample file I have created have long names for some of the resources that are running over into the duration column. 

I have attached a sample xml file that contains long named resources. I would prefer if this could be done as the elements are being built rather than having css styles and javascript to determine how long the "longest" resource name or task is.

Version: 1.7.5.4
Browsers and Operating System: I have tested this in both Chrome and Internet Explorer 11 on Windows  7

[convertedProject.zip](https://github.com/jsGanttImproved/jsgantt-improved/files/1173458/convertedProject.zip)

**Comment by RickCardoso** [comment]
@abrousseau001 , I don't know how useful and practical would be to have adjustable columns. I would recommend always using simple titles (like you'd normally do in a to-do list) and add details on the notes field.

For now I'm closing this issue, but we'll keep auto adjustment in mind if we make a big update with new coding and style structure.
