### ISSUE TITLE
Click event functionality on the Gantt Chart Grid cell

### ISSUE THREAD

**Issue by vishwarup** [jsGanttImproved/jsgantt-improved#44]
How can we add click event functionality on the Gantt Chart Grid cell?

**Comment by GeekSilva97** [comment]
I added this functionality, how can I contribute?

**Comment by GeekSilva97** [comment]
I'll create a branch called issue44 with the modifications

**Comment by GeekSilva97** [comment]
Some improvements have been made to this functionality. Here's a new pull request (#70). Please close the previous pull request (#61)

**Comment by mariohmol** [comment]
Thanks.. this will be on next release =)
