### ISSUE TITLE
Baseline handling

### ISSUE THREAD

**Issue by fastcatch** [jsGanttImproved/jsgantt-improved#49]
In a project we use jsgantt-improved and it has fit the bill nicely.  Thanks for your work!

However, we will soon need to handle task baseline dates (start and finish) as well and draw them on the chart.

I very much consider coding this up (so forking is an option) but - for various reasons - I'd much prefer if it could get merged back.  Thus I have a few questions: 

- Do you have any more general plans as to how to expand the available data fields?  (There seem to be a few other feature requests to this effect as well.)  Baselines are a bit special in that they would require changes to the charting part as well but also it is two new fields.
- I have checked the code and it looks like that it is not a trivial addition; it touches many parts and it is likely to involve some internal refactoring as well.  Would you consider pulling the resulting - a bit bigger - PR (provided it meets your quality standards)?
- Would you be available to discuss refactoring directions (so that whatever direction I may take wouldn't go against your vision and then having to redo a lot of stuff)?

Please let me know what you think about this.  Thanks.

**Comment by eduardomourar** [comment]
@fastcatch, I am sorry. Me and Ricardo started a new job position recently, hence the late response.

1) My suggestion is to start only with baseline dates, and we can make a new PR later with additional fields.

2) refactoring here is very welcome. Let us try to make a initial PR small if possible and expand gradually.

3) I will gladly review your PR. And I will be available to help in any way I can to make this happen.

**Comment by fastcatch** [comment]
Cool. I have suggestions as to how to proceed but I'd rather discuss it off here (it's long and may not want to expose all of it).  If you don't mind drop me a mail (temporarily made public in my profile).

**Comment by mariohmol** [comment]
Hi there, i think this is covered now.. check it out

1. Now we have planned and executed days, perfect for baselines
2. refactored to a better structure and TS
3. Open issues for new ideas or help us coding =)

**Comment by snehad22** [comment]
Hi Mariohmol,
Can you please share documentation for using baseline?

**Comment by mariohmol** [comment]
We dont have full support of baseline.. what we have is PlanStart Date and PlanEnd Date.. they are in docs
