### ISSUE TITLE
Updating dependencies for Tasks

### ISSUE THREAD

**Issue by abrousseau001** [jsGanttImproved/jsgantt-improved#50]
This is a question/possible enhancement request.

When removing a task I understand all children of that task are also removed, but are the dependencies of other tasks also modified to remove the task from being a dependency? 

Example:
A group/top level task, [Task 4], is removed, but the next group/top level task, [Task 5] contains a dependency on [Task 4] being completed. 

This can never be fulfilled so the dependency needs to be removed. Is this possible?

**Comment by mariohmol** [comment]
I guess if u auto remove its bad to use.. because he might want to just reallocate the tasks..

and there is no feature of adding/removing using the gantt chart.. so i dont know how this could be achieved.. 

could u help out with more info?

**Comment by mariohmol** [comment]
Hi.. as soon as u get more info about this idea ... please reopen to discuss..
thanks
