### ISSUE TITLE
Month format showing wrong month

### ISSUE THREAD

**Issue by hi2pranay** [jsGanttImproved/jsgantt-improved#52]
Hi,

if i set startdate to "2016-01-01" and enddate to "2016-03-01" and display in Month format its showing bar from Jan to March, but when i set enddate has "2018-03-01" or greater then 2018, bar is shown till Jan only, how do i solve this issue.

Thanks

**Comment by thclark** [comment]
Possibly related to #48 - check that your pGroup parameter is consistent. Also, if you submit a standalone snippet that reproduces the error, it'll help everybody diagnose.

**Comment by hi2pranay** [comment]
Thanks clark, its working

**Comment by thclark** [comment]
OK great, I'd close this issue and let any further reports go into #48

**Comment by hi2pranay** [comment]
Clark i have issue here below

g.AddTaskItem(new JSGantt.TaskItem(1,   'test',     '2016-01-01',  '2017-07-29', 'ggroupblack',      '',       0, 'Brian',      0,     1,      0,      1,      '',      '',      '', g ));

For enddate when given Startdate year and Enddate year same and greater then Startdate year like 2016 and 2017, Enddate is taking current date

How can i solve this

**Comment by mariohmol** [comment]
There is an working example here, if still not working in your side please provide some example data

https://mariohmol.github.io/jsgantt-improved/docs/demo.html
