### ISSUE TITLE
Edit the start date, end date, duration on the chart

### ISSUE THREAD

**Issue by prakashraman** [jsGanttImproved/jsgantt-improved#54]
Hi,

Is it possible to edit the start, end and duration on the chart itself. I was reading through the docs, the plugin/widgets seems more of a view of the data rather than an intractable widget right?

Do let me know!
Great plugin btw 👍 !

**Comment by eduardomourar** [comment]
@prakashraman , answering your question... No, it is not possible to edit any fields directly on the chart itself. Our main goal here is to present the data to the user, but feel free to do a PR with this functionality if you want. Thanks!

**Comment by mariohmol** [comment]
This is a good idea... In the table showing the info, when clicking in a data (ex. Start Date 15/01/01 in Task Id 1 ), must open a input and after blur close the input and show the text again, updating the value and chart

**Comment by mariohmol** [comment]
check out v2.0.8
