### ISSUE TITLE
Relationships between tasks

### ISSUE THREAD

**Issue by GeekSilva97** [jsGanttImproved/jsgantt-improved#55]
Searching about the gantt chart, I saw that there are relationships between the tasks. These relationships are: FF (Finish-Finish), SF (Start-Finish), FS (Finish-Star) and SS (Start-Start).
I wonder if it's possible to do that.

**Comment by CoderBees245** [comment]
Is this possible in this? Have you tried?

**Comment by geeksilva97** [comment]
Yes, is possible. To do it you can user the **pDepend** attribute. See at doc

https://github.com/jsGanttImproved/jsgantt-improved/blob/master/Documentation.md
