### ISSUE TITLE
Headings of calendar

### ISSUE THREAD

**Issue by javg151** [jsGanttImproved/jsgantt-improved#56]
Hi, in the example located in https://jsganttimproved.github.io/jsgantt-improved/  the first task have start date 20/02/2017, but the chart is located in 19, and the end date is 29/03/2017 but the chart is located in 25. Same case for the rest of tasks.

Apparently, is caused for the headings of weekend

**Comment by javg151** [comment]
I have resolved, adding 2 units to vColWidth variable

I modified lines in Draw function

vTaskLeftPx=JSGantt.getOffset(vMinDate, curTaskStart, vColWidth+2, vFormat); //modified: before->vColWidth; after->vColWidth+2

vTaskRightPx=JSGantt.getOffset(curTaskStart, curTaskEnd, vColWidth+2, vFormat);//modified: before->vColWidth; after->vColWidth+2

**Comment by GeekSilva97** [comment]
Great! it worked perfectly

**Comment by eduardomourar** [comment]
@jvg151, could you make a pull request with this change, please? That way I can close this issue. Thanks
