### ISSUE TITLE
In month view, the alignment of task objects is sometimes off.

### ISSUE THREAD

**Issue by andy-hammond** [jsGanttImproved/jsgantt-improved#60]
Even on the demo site, if you changed the view to month you will see that the summary task of "Code Javascript" should end in September but the task is positioned shortly before the end of August.

![gantt](https://user-images.githubusercontent.com/10079521/32450362-edfd4bde-c30b-11e7-8ae4-8cf6b06ee59d.png)

**Comment by eduardomourar** [comment]
This is related to #48
