### ISSUE TITLE
gtaskgray css color is not displaying

### ISSUE THREAD

**Issue by skfaisal123** [jsGanttImproved/jsgantt-improved#62]
When i give my custom class color it is not showing in the gantt chart.
.gtaskgray {
    background: rgb(236,235,226);
    background: linear-gradient(to bottom, rgba(236,235,226,1) 0%,rgba(222,222,216,1) 20%,rgba(212,212,201,1) 40%,rgba(193,193,182,1) 70%,rgba(183,183,181,1) 100%);
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ecebe2', endColorstr='#b7b7b5',GradientType=0 );
}
Please help me out in this.

**Comment by GeekSilva97** [comment]
Add the following trunk to your CSS:

`height: 13px; filter: alpha(opacity=90); opacity:0.9; margin-top: 1px;`

The code will look this:

.gtaskgray {
     height: 13px; 
     filter: alpha(opacity=90); 
     opacity:0.9; 
     margin-top: 1px;
     background: rgb(236,235,226);
     background: linear-gradient(to bottom, rgba(236,235,226,1) 0%,rgba(222,222,216,1) 20%,rgba(212,212,201,1) 40%,rgba(193,193,182,1) 70%,rgba(183,183,181,1) 100%);
     filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ecebe2', endColorstr='#b7b7b5',GradientType=0 );
        }

You will also need to add the following code:

`.gtaskgraycomplete{
            float:left; overflow: hidden; height:5px; filter: alpha(opacity=40); opacity:0.4; background-color: #000000; margin-top:4px;
        }`

This way you can see the **comp.*. of  task. See the example in the pictures:
![git-code](https://user-images.githubusercontent.com/15680379/33023717-cf107890-cde7-11e7-8a95-b16b52f4f76f.png)
![git-show](https://user-images.githubusercontent.com/15680379/33023718-cf2d8016-cde7-11e7-8db1-784d52800a7d.png)

**Comment by skfaisal123** [comment]
Thanks alot :+1:

**Comment by skfaisal123** [comment]
Thank you very much for your support.


Best regards,



Shaikh MD Faisal

Solution Specialist

Eloqns International Co.

Think Big, Start Small & Scale Fast

faisal@eloqns.com<mailto:yourname@eloqns.com>

M: +965 50284444<tel:%2B965%2051505770>

T: +965 22619688<tel:%2B965%2022619688>

F: +965 22619677<tel:%2B965%2022619677>


________________________________

**Comment by GeekSilva97** [comment]
Glad it worked, it was a pleasure! ;)
