### ISSUE TITLE
[Urgent] Is it possible to create Gantt Chart like this?

### ISSUE THREAD

**Issue by hilfiger1014** [jsGanttImproved/jsgantt-improved#64]
Hi Expert, I appreciate you to help me sort any problems out to create Gantt by using the JavaScript. At the moment I have a question on creating advanced requirements. If I would like to create Gantt bar like this as below:

![2017-12-29_14-07-51](https://user-images.githubusercontent.com/17022215/34430654-2b5f60b0-eca2-11e7-9c88-fa3a3e4e26ba.png)

How should I do?

**Comment by UgurAsaner** [comment]
+1

**Comment by eduardomourar** [comment]
dupe #65
