### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jsGanttImproved/jsgantt-improved#7]
```
Are there any solutions to render the charts as PDF? Closest we are able to get 
there now is using window.print, but the lines do not render properly in Chrome.

```

Original issue reported on code.google.com by `jerry.r...@passagetech.com` on 20 May 2015 at 5:03

**Comment by jsGanttImproved** [comment]
As PDF printing is not core functionality and there has been no update on the other issues I'm closing this as "won't fix"
