### ISSUE TITLE
ie scroll too slowly

### ISSUE THREAD

**Issue by hyfbeetle** [jsGanttImproved/jsgantt-improved#71]
hi,dear.
i downloaded jsganttimproved.open it in ie9, scrolling is too slow.but it is ok in chrome.

**Comment by hyfbeetle** [comment]
ie11 is ok too

**Comment by eduardomourar** [comment]
we can only support Microsoft IE11 + Edge, even for security reasons (check it out [here](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support))
