### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by sunithajanapareddy** [jsGanttImproved/jsgantt-improved#72]
Bar starting from wro
![gatt](https://user-images.githubusercontent.com/19980424/35099910-bdddade2-fc7f-11e7-81f7-7100415d5dff.png)
ng start and end date butt  start date column it is showing correct

**Comment by hyfbeetle** [comment]
me too.how to solve it

**Comment by sunithajanapareddy** [comment]
please can anybody help us

**Comment by Hellboy12345** [comment]
Check your jsgantt.js file. In line 1666 should be:
"vTaskRightPx=Math.ceil((vTaskRight/24) * (pColWidth+1) );"

**Comment by sunithajanapareddy** [comment]
i didnt have this line

**Comment by sunithajanapareddy** [comment]
Thank U Hellboy it worked

**Comment by hyfbeetle** [comment]
current day display blue line, but I can accept it
