### ISSUE TITLE
bootstrap version

### ISSUE THREAD

**Issue by sunithajanapareddy** [jsGanttImproved/jsgantt-improved#73]
Gantt chart bar is showing wrong  for bootstrap3.3.7 version

**Comment by thclark** [comment]
@sunithajanapareddy perhaps you could post some screenshots or (preferably) a minimal example highlighting the discrepancy, together with the version of bootstrap which would cause it to render properly?

**Comment by eduardobelchior** [comment]
Did you solve the problem?

**Comment by sunithajanapareddy** [comment]
yes

**Comment by eduardobelchior** [comment]
As? Would you help me?

**Comment by sunithajanapareddy** [comment]
Where you are facing problem
