### ISSUE TITLE
Scrollbar in activity table

### ISSUE THREAD

**Issue by eduardobelchior** [jsGanttImproved/jsgantt-improved#75]
I just added a scrollbar in the activity table to add the dependencies column (I'll post the changes later), but I could not get the table header to go with the body.

Acabei de adicionar uma barra de rolagem na tabela de atividades para adicionar a coluna de dependencias (enviarei as mudanças depois), mas não consegui fazer com que o header da tabela acompanhe o body.

![captura de tela em 2018-01-22 13-50-33](https://user-images.githubusercontent.com/18681450/35232908-7422242c-ff7b-11e7-8811-1ca9fb4ad67c.png)

**Comment by thclark** [comment]
Lovely work, @eduardobelchior - is the heading fixed too?

**Comment by eduardobelchior** [comment]
Yes, I duplicated a scroll event and some gets and sets that "unite" the "header" with the "body" of the table
