### ISSUE TITLE
Top dates become disaligned with chart

### ISSUE THREAD

**Issue by vinciop** [jsGanttImproved/jsgantt-improved#80]
to reproduce this issue, i changed the finish date on the last finishing activity in the example: 'Make Updates' to '2017-09-09'. When changing the visualization to days, and scrolling to the right end of the chart, the top dates stop scrolling shortly before the end of the bar, while the chart keeps moving, creating a misalignment (see picture).
![image](https://user-images.githubusercontent.com/27064821/36195427-b8c5120c-116d-11e8-92bc-443873054d9b.png)
The magnitude of the misalignment depends on the end date of the last activity in the chart, i tried the following:
2017-09-09 -> 5 days
2017-09-08 -> 4 days
...
2017-09-05 -> 1 day
2017-09-04, 2017-09-03  -> no misalignment
2017-09-02 -> 5 days
2017-09-01 -> 4 days
etc.
and keeps repeating with weekly period.
This is not related to the activity, as using the same date on another activity yields the same result, provided it is the last activity in the chart.

**Comment by mariohmol** [comment]
Hi.. is this still a problem?

Could u please test using this new version?

https://codepen.io/mariomol/pen/mQzBPV

**Comment by mariohmol** [comment]
If this persists please provide example data and reopen!
thanks
