### ISSUE TITLE
Milestone symbols should be at the end date, not at start date

### ISSUE THREAD

**Issue by roestigraben** [jsGanttImproved/jsgantt-improved#82]
Is there an option to show milestone lozange symbols at the end of all child tasks?

Currently it shows at the left side (start of any child tasks)

This is not natural

<img width="588" alt="screen shot 2018-02-20 at 17 44 45" src="https://user-images.githubusercontent.com/4879307/36436882-d46ec550-1665-11e8-986d-7032fdd2cb31.png">

**Comment by mariohmol** [comment]
Good point! Check it out https://mariohmol.github.io/jsgantt-improved/docs/demo.html
