### ISSUE TITLE
Progress bar issue with date

### ISSUE THREAD

**Issue by vishalsingh119** [jsGanttImproved/jsgantt-improved#84]
https://prnt.sc/ip7q8x

To understand better, first open above screenshot URL.

1. Check the start date and progress bar carefully, because start date starting on 11th but progress bar starting on 12th(one step ahead).
2. Chart zoom level is very low. how can we increase zoom level of chart

**Comment by hilfiger1014** [comment]
the solution is [here](https://github.com/jsGanttImproved/jsgantt-improved/pull/81)....
