### ISSUE TITLE
How to delete/ disable the unused columns?

### ISSUE THREAD

**Issue by hilfiger1014** [jsGanttImproved/jsgantt-improved#85]
Hi Experts,
Some of the columns in the Gantt Chart is not to use. How should I delete it.? I don't need to use {Resource}, and {Duration} as below.

![2018-03-13_00-06-07](https://user-images.githubusercontent.com/17022215/37296406-d7d2c70a-2655-11e8-83d0-21ff67c1fb87.png)

I follow the documentation and set the parameters setShowRes and setShowDur to 0, I disable the two columns indeed. But It also present a blank space (green color) as bellow:

![2018-03-13_02-05-58](https://user-images.githubusercontent.com/17022215/37301629-0f79105c-2664-11e8-86f4-57389e11bfb0.png)

How should I sort it out.?

**Comment by hilfiger1014** [comment]
I had sort it out. Thanks for your help ...

**Comment by shawngoh87** [comment]
@hilfiger1014 Do you mind sharing how you solved it?
