### ISSUE TITLE
Implementing this Add-in into a UI5 App (Neptune)

### ISSUE THREAD

**Issue by AndreasMichaelWolf** [jsGanttImproved/jsgantt-improved#87]
Whatever I do the JSGantt will always stop at this statement:

	if (vDiv && vDiv.nodeName.toLowerCase()=='div') vDivId=vDiv.id;

Because nodeName is undefined. No Idea what that is.

Regards

**Comment by basjka** [comment]
in the full examples at the end you can found: 
`var g = new JSGantt.GanttChart('g',document.getElementById('GanttChartDIV'), 'day');`

but when look at source code or first example you can found:
first Example: `var g = new JSGantt.GanttChart(document.getElementById('GanttChartDIV'), 'day');`
source Code: `JSGantt.GanttChart=function(pDiv, pFormat) {...`

So constructor has only two parameters divElement and format.
To fix it just delete first parameter 'g' from initialization.
