### ISSUE TITLE
Compeletion and Date

### ISSUE THREAD

**Issue by hilfiger1014** [jsGanttImproved/jsgantt-improved#88]
Hi Experts,
I have questions is the Project completion percentage is calculated automatically. But is it possible to don't use this function. I just want Input my value and then my value will be shown up.

![2018-03-20_15-05-58](https://user-images.githubusercontent.com/17022215/37640602-5f71442e-2c51-11e8-9519-5f9bd1be87d3.png)

**Comment by mariohmol** [comment]
Add a Task passing the comp like ``` g.AddTaskItemObject({
  "pID": 1,
  "pName": "Define Chart <strong>API</strong>",
  "pStart": "2017-02-25",
  "pEnd": "2017-03-17",
  "pPlanStart": "2017-04-01",
  "pPlanEnd": "2017-04-15 12:00",
  "pClass": "ggroupblack",
  "pLink": "",
  "pMile": 0,
  "pRes": "Brian",
  "pComp": 66,
  "pGroup": 1,
  "pParent": 0,
  "pOpen": 1,
  "pDepend": "",
  "pCaption": "",
  "pCost": 1000,
  "pNotes": "Some Notes text"
}); ```
