### ISSUE TITLE
Multilingual support for Quarters

### ISSUE THREAD

**Issue by mcomelli** [jsGanttImproved/jsgantt-improved#90]
Multilingual support needs to custom this:
                    
    case 'qq':
        //vDateStr+='Q'; // now fall through
        vDateStr+='T'; // now fall through
        
'T' is for Italian 'Trimestre' (which means 3 months...), instead of Quarter.
Should it be added in `var vLangs` options?

**Comment by mariohmol** [comment]
Could you please provide a italian translate?  https://github.com/jsGanttImproved/jsgantt-improved/blob/master/src/lang.ts

**Comment by mariohmol** [comment]
added the translation in this part as well.. thanks
