### ISSUE TITLE
Add a Translation page to the wiki

### ISSUE THREAD

**Issue by noraj** [jsGanttImproved/jsgantt-improved#91]
Here is the french translation, can you add a **Translation** page to the wiki, and add this:

```javascript
g.addLang('fr', { 
        // Mois : http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=3619
        // Jours : http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=3617
        'january':'Janvier', 'february':'Février', 'march':'Mars',
        'april':'Avril', 'maylong':'Mai', 'june':'Juin', 'july':'Juillet',
        'august':'Août', 'september':'Septembre', 'october':'Octobre',
        'november':'Novembre', 'december':'Décembre', 'jan':'Janv',
        'feb':'Févr', 'mar':'Mars', 'apr':'Avr', 'may':'Mai', 'jun':'Juin',
        'jul':'Juil', 'aug':'Août', 'sep':'Sept', 'oct':'Oct', 'nov':'Nov',
        'dec':'Déc', 'sunday':'Dimanche', 'monday':'Lundi', 'tuesday':'Mardi',
        'wednesday':'Mercredi', 'thursday':'Jeudi', 'friday':'Vendredi',
        'saturday':'Samedi', 'sun':'Dim', 'mon': 'Lun', 'tue':'Mar',
        'wed':'Mer', 'thu':'Jeu', 'fri':'Ven', 'sat': 'Sam', 
        'resource':'Ressource', 'duration':'Durée', 'comp': '% Term.',
        'completion':'Terminé', 'startdate':'Début', 'enddate':'Fin',
        'moreinfo':"Plus d'informations", 'notes':'Notes', 'format':'Format',
        'hour':'Heure', 'day':'Jour', 'week': 'Semaine', 'month': 'Mois',
        'quarter':'Trimestre', 'hours':'Heures', 'days':'Jours',
        'weeks':'Semaines', 'months':'Mois', 'quarters':'Trimestres', 'hr':'h',
        'dy':'j', 'wk':'sem', 'mth':'mois', 'qtr':'tri', 'hrs':'h', 'dys':'j',
        'wks':'sem', 'mths':'mois', 'qtrs':'tri'
      });
```

**Comment by aliansplastby** [comment]
Here is the Russian translation
  g.addLang('ru', 
{'january': 'Январь',
'february': 'Февраль',
'march': 'Март',
'april': 'Апрель',
'maylong': 'Май',
'june': 'Июнь',
'july': 'Июль',
'august': 'Август','september':'Сентябрь',
'october':'Октябрь',
'november':'Ноябрь',
'december':'Декабрь',
'jan':'Янв',
'feb':'Фев',
'mar':'Мар',
'apr':'Апр',
'may':'Май',
'jun':'Июн',
'jul':'Июл',
'aug':'Авг',
'sep':'Сен',
'oct':'Окт',
'nov':'Ноя',
'dec':'Дек',

'sunday':'Воскресенье',
'monday':'Понедельник',
'tuesday':'Вторник',
'wednesday':'Среда',
'thursday':'Четверг',
'friday':'Пятница',
'saturday':'Суббота',
'sun':'	 Вс',
'mon':'	 Пн',
'tue':'	 Вт',
'wed':'	 Ср',
'thu':'	 Чт',
'fri':'	 Пт',
'sat':'	 Сб',
'resource':'Ресурс',
'duration':'Длительность',
'comp':'% выполнения',
'completion':'Выполнено',
'startdate':'Нач. дата',
'enddate':'Кон. дата',
'moreinfo':'Детали',
'notes':'Заметки',

'format':'Формат',
'hour':'Час',
'day':'День',
'week':'Неделя',
'month':'Месяц',
'quarter':'Кварт',
'hours':'Часов',
'days':'Дней',
'weeks':'Недель',
'months':'Месяцев',
'quarters':'Кварталов',
'hr':'ч.',
'dy':'дн.',
'wk':'нед.',
'mth':'мес.',
'qtr':'кв.',
'hrs':'ч.',
'dys':'дн.',
'wks':'нед.',
'mths':'мес.',
'qtrs':'кв.'});

**Comment by tiagocpeixoto** [comment]
Here is the portuguese (Brazil) translation:
    chart.addLang('pt', {
      'format':'Formato',
      'hour': 'Hora',
      'day': 'Dia',
      'week': 'Semana',
      'month': 'Mês',
      'quarter': 'Trimestre',
      'completion': '% Completo',
      'moreinfo': 'Mais informações',
      'notes': 'Notas',
      'resource':'Responsável',
      'duration':'Duração',
      'startdate': 'Data inicial',
      'enddate': 'Data final',
      'dys': 'dias',
      'wks': 'sem.',
      'mths': 'mes.',
      'feb':'Fev',
      'apr':'Abr',
      'may':'Mai',
      'aug':'Ago',
      'sep':'Set',
      'oct':'Out',
      'dec':'Dez',
      'january': 'Janeiro',
      'february': 'Fevereiro',
      'march': 'Março',
      'april': 'Abril',
      'maylong': 'Maio',
      'june': 'Junho',
      'july': 'Julho',
      'august': 'Agosto',
      'september': 'Setembro',
      'october': 'Outubro',
      'november': 'Novembro',
      'december': 'Dezembro'
    });

**Comment by caveman2st** [comment]
german:

var vLangDE = {
    'format': 'Ansicht',
    'hour': 'Stunde',
    'day': 'Tag',
    'week': 'Woche',
    'month': 'Monat',
    'quarter': 'Quartal',
    'hours': 'Stunden',
    'days': 'Tage',
    'weeks': 'Wochen',
    'months': 'Monate',
    'quarters': 'Quartale',
    'hr': 'h',
    'dy': 'T',
    'wk': 'W',
    'mth': 'M',
    'qtr': 'Q',
    'hrs': 'Std',
    'dys': 'Tage',
    'wks': 'Wochen',
    'mths': 'Monate',
    'qtrs': 'Quartal',
    'resource': 'Resource',
    'duration': 'Dauer',
    'comp': '%Fertig',
    'completion': 'Fertigstellung',
    'startdate': 'Erste Buchu',
    'enddate': 'Letzte Buchung',
    'moreinfo': 'Weitere Infos',
    'notes': 'Anmerkung',
    'january': 'Jänner',
    'february': 'Februar',
    'march': 'März',
    'april': 'April',
    'maylong': 'Mai',
    'june': 'Juni',
    'july': 'Juli',
    'august': 'August',
    'september': 'September',
    'october': 'Oktober',
    'november': 'November',
    'december': 'Dezember',
    'jan': 'Jan',
    'feb': 'Feb',
    'mar': 'Mar',
    'apr': 'Apr',
    'may': 'Mai',
    'jun': 'Jun',
    'jul': 'Jul',
    'aug': 'Aug',
    'sep': 'Sep',
    'oct': 'Okt',
    'nov': 'Nov',
    'dec': 'Dez',
    'sunday': 'Sonntag',
    'monday': 'Montag',
    'tuesday': 'Dienstag',
    'wednesday': 'Mittwoch',
    'thursday': 'Donnerstag',
    'friday': 'Freitag',
    'saturday': 'Samstag',
    'sun': 'So',
    'mon': 'Mo',
    'tue': 'Di',
    'wed': 'Mi',
    'thu': 'Do',
    'fri': 'Fr',
    'sat': 'Sa'
};

**Comment by mariohmol** [comment]
Check it out https://mariohmol.github.io/jsgantt-improved/demo/fixes/lang.html

**Comment by noraj** [comment]
@mariohmol https://mariohmol.github.io/jsgantt-improved/demo/fixes/lang.html => http 404 error

**Comment by noraj** [comment]
I found the correct url: https://mariohmol.github.io/jsgantt-improved/docs/fixes/lang.html

**Comment by noraj** [comment]
@mariohmol Is that not better to put translations into a separate file rather than in https://github.com/jsGanttImproved/jsgantt-improved/blob/master/docs/jsgantt.js ?

**Comment by mariohmol** [comment]
sorry. this is the correct link https://github.com/jsGanttImproved/jsgantt-improved/blob/master/src/lang.ts
