### ISSUE TITLE
When I config the pGroup = 2 (combine), the result cannot present in the IE and Edge

### ISSUE THREAD

**Issue by hilfiger1014** [jsGanttImproved/jsgantt-improved#92]
Hi Experts,

When I config the pGroup = 2 (combine), the result cannot present in the IE and Edge. How should I handle it.

**Comment by mariohmol** [comment]
Can u test with this example https://mariohmol.github.io/jsgantt-improved/docs/demo.html ?

**Comment by mariohmol** [comment]
If this still an issue please let us know
