### ISSUE TITLE
Tasks display with wrong width and position in chart

### ISSUE THREAD

**Issue by LorenzoBruschi** [jsGanttImproved/jsgantt-improved#96]
I've just used your default live example configuration of the plugin. As you can see from the screenshots, the colored horizontal lines of the tasks aren't showing in the right way. I've not touched any of your jsgantt.css nor jsgantt.js scripts, only copy-pasted your live example on my intranet.
Has it something to do with the left black sidebar I use?

![1](https://user-images.githubusercontent.com/7869564/39194738-a86012e8-47de-11e8-85ac-13139c3fd142.png)
![2](https://user-images.githubusercontent.com/7869564/39194740-a886fe8a-47de-11e8-81a4-661c40a37fad.png)

**Comment by RicardoIracheta19** [comment]
I have the same problem. There seems to be a bigger offset the further in time you go. But So far I am clueless as to what could be causing it.

**Comment by allanzi** [comment]
@RicardoIracheta19 how exactly you solved ?

**Comment by RicardoIracheta19** [comment]
@allanzi Hi. 

In file jsgantt.js, function JSGantt.getOffset, lines 1664 and 1665 calculate the width of the task.
`var tmpTaskStart=Date.UTC(curTaskStart.getFullYear(), curTaskStart.getMonth(), curTaskStart.getDate(), curTaskStart.getHours(), 0, 0);`
`var tmpTaskEnd=Date.UTC(curTaskEnd.getFullYear(), curTaskEnd.getMonth(), curTaskEnd.getDate(), curTaskEnd.getHours(), 0, 0);`

Simply change the fourth parameter by a 0 so you always have 00:00 as time for your date.

Let me know if this works for you.

**Comment by allanzi** [comment]
@RicardoIracheta19 thanks for sharing your solution, but i was able to solve with this  [pull request](https://github.com/jsGanttImproved/jsgantt-improved/pull/81)

**Comment by dustinrpatterson** [comment]
@allanzi that pull request worked for me too! Thanks for linking it to this issue.

**Comment by mariohmol** [comment]
Could u please test it in new version to see if that is fixed?
