### ISSUE TITLE
Column width adjustment

### ISSUE THREAD

**Issue by thclark** [jsGanttImproved/jsgantt-improved#98]
I've searched the docs, but can't find a reference to whether (and how) it's possible to change column widths on the left hand side. The following screenshot shows my problem (I can't change resource column width, or name column width)...

<img width="499" alt="screen shot 2018-05-08 at 14 07 19" src="https://user-images.githubusercontent.com/7223170/39759226-0a7d88d4-52ca-11e8-9fad-af158092f43a.png">

### I have:

- Checked for the same or related issues. Only related one might be #97 which is a bit vague at best.
- Checked the docs for relevant settings.

Does anyone know if it's possible to do this? Maybe there's an undocumented setting that I can change the value for?

**Comment by thclark** [comment]
OK I've come up with a workaround on this. After:
```js
g.Draw()
```
You can use the following fiddle (requires jQuery):
```js

// Draw columns at sensible widths and shunt the gantt chart across
adjustColWidths = function(){
    $( "td.gtaskname" ).css("min-width", "370px");
    $( "td.gresource" ).css("min-width", "140px");
    //$( "td.gduration" ).css("min-width", "140px");
    $( "#GanttChartDIVglisthead" ).css("width", "586px")
    $( "#GanttChartDIVglistbody" ).css("width", "586px")
};
$(document).ready(adjustColWidths);
$(document).click(adjustColWidths);
```

Which fixes my view of the above to:
<img width="899" alt="screen shot 2018-05-08 at 16 55 51" src="https://user-images.githubusercontent.com/7223170/39768278-c10a072e-52e0-11e8-9fe7-826a19e9e7a9.png">

**Comment by mariohmol** [comment]
Was added a CSS strip word to not break the design.. the tooltip can show full details or use the Task with HTML to have a link to a custom detailed tooltip
